- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkNavigationHandlerImpl.java
Because the minitype of xhtml file is "application/xhtml+xml".
It's intercepted by XWalkNavigationHandler to not handle in Crosswalk.
The default behavior for xhtml should be the same as html file, that
is loaded in the Crosswalk no matter with file schema or http schema.
BUG=XWALK-2912
> [Android] Fix file://*/*.xhtml will be opened in default browser.

- application/browser/application.cc
According to W3C Widget specific (http://www.w3.org/TR/widgets/), when a start
page is not given by config.xml, the UA should locate default start file by a
fixing order instead, which is given by "default start files
table" (http://www.w3.org/TR/widgets/#default-start-files-table) from top to
bottom. This patch will solve a mismatch with the spec.
BUG=XWALK-3264
> [Runtime] Change the default start files priority

- runtime/renderer/xwalk_content_renderer_client.cc
- runtime/renderer/xwalk_render_process_observer_generic.cc
- runtime/renderer/xwalk_render_process_observer_generic.h
Since the Chromium/Blink Access White List can not support to check service port pattern
in access rule, so need to treat it in runtime. This patch add a checking of
service port in WARP mode.
BUG=XWALK-3132
> [Runtime] Enable to support service port in WARP mode rules

- runtime/browser/android/xwalk_content.cc
This patch is to add the check for return value of GetString() in
widget_handler.cc and xwalk_content.cc.
CID=220010
Related to XWALK-2928.
(cherry picked from commit 0bc7870d527aebed3fd6b8c5108f8e931094ec4c)
> Add the check for return value of GetString().

- DEPS.xwalk
a64feb1 Merge pull request #345 from Tarnyko/Milestone-ThanksGiving
354aaae XDG-Shell: update to 1.6.0
This change is needed to handle Weston 1.6.0 nicely.
> DEPS.xwalk: Roll ozone-wayland (597c8df -> a64feb1).

- application/browser/application.cc
- application/common/constants.h
- application/common/package/wgt_package.cc
- application/common/package/wgt_package.h
- application/tools/tizen/xwalk_package_installer.cc
This patch contains function which verify name
of the widget entry file during installation.
Table contains list of proper names of the files
has been moved to constans.
BUG=XWALK-2983
> [Tizen] Verification name of a widget entry file

- DEPS.xwalk
* 5d7baa9 Rename WindowTree*Wayland as WindowManagerWayland.
* 9c19d69 Move WindowTreeHostDelegateWindow to platform/
These two commits are backports from ozone-wayland master and removes a
dependency across shared libraries on a class that is not exported and
was causing problems when building Crosswalk with
component=shared_library.
> DEPS.xwalk: Roll ozone-wayland (a64feb1 -> 5d7baa9).

- application/browser/application.cc
- application/browser/application.h
- application/browser/application_system.cc
- application/browser/application_system_tizen.cc
- application/browser/linux/running_applications_manager.cc
- runtime/common/xwalk_switches.cc
- runtime/common/xwalk_switches.h
Fullscreen is still supported in the manifest and by the fullscreen Web API.
> Remove the fullscreen command line option

- application/common/package/wgt_package.cc
This patch fixes improper order of default widget entry pages.
> [Tizen] Fix order of default widget start files

- DEPS.xwalk
* 5c8891d Merge pull request #226 from rakuco/export-NativeDisplayDelegateOzone
* 60bd47d [Temp] Export ui::NativeDisplayDelegateOzone.
This pulls a commit that exports a symbol used by ozone-wayland that was
not available before when building in shared_library mode (part of
XWALK-2571).
> DEPS.xwalk: Roll chromium-crosswalk (5557d51 -> 5c8891d).

- DEPS.xwalk
ed58c20 Merge pull request #227 from wuhengzhi/crosswalk-11/40.0.2214.28
1a2e3d3 [Temp] Make unix socket Get{Peer|Local}Address return more
rational errors.
This pulls a commit that fix the endless error logs in remote
debugging.
Related to XWALK-3188.
> DEPS.xwalk: Roll chromium-crosswalk (5557d51 -> ed58c20).

- DEPS.xwalk
13ee6cc Merge pull request #223 from wuhengzhi/master
44a8a9c [Temp] Make unix socket Get{Peer|Local}Address return more
rational errors.
This pulls a commit that fix the endless error logs in remote
debugging.
Related to XWALK-3188.
> DEPS.xwalk: Roll chromium-crosswalk (5c8891d -> 13ee6cc).

- runtime/renderer/tizen/xwalk_content_renderer_client_tizen.cc
- runtime/renderer/tizen/xwalk_content_renderer_client_tizen.h
- runtime/renderer/tizen/xwalk_render_view_ext_tizen.cc
- runtime/renderer/tizen/xwalk_render_view_ext_tizen.h
The issue is caused by injecting java script to enable firing widget preferences
storage event, and this will skip the initialization progress of extension
process. The patch will make sure inject this script just after the extension
has been initialized.
BUG=https://bugs.tizen.org/jira/browse/TC-2306
> [Tizen] Fix "Uncaught ReferenceError: tizen is not defined" error when starting an application

- runtime/browser/devtools/xwalk_devtools_delegate.cc
- test/base/in_process_browser_test.cc
The crash happened if the target page did not have thumbnail icon.
> [Tizen/Linux] Fix crash at XWalkDevToolsDelegate::ProcessAndSaveThumbnail

- application/browser/application.cc
- application/browser/application.h
- application/browser/application_service.cc
- application/browser/application_service.h
- application/browser/application_service_tizen.cc
- application/browser/application_service_tizen.h
- application/browser/application_system.cc
- application/browser/application_system_tizen.cc
- application/browser/application_tizen.cc
- application/browser/application_tizen.h
- application/browser/linux/running_applications_manager.cc
- runtime/browser/devtools/xwalk_devtools_delegate.cc
- runtime/browser/runtime.cc
- runtime/browser/runtime.h
- test/base/in_process_browser_test.cc
Drop Application::LaunchParams struct (as well as all its client code) as it contains only "shared process model"-specific data.
> Drop Application::LaunchParams struct

- runtime/renderer/tizen/xwalk_content_renderer_client_tizen.cc
- runtime/renderer/tizen/xwalk_content_renderer_client_tizen.h
- runtime/renderer/tizen/xwalk_render_view_ext_tizen.cc
- runtime/renderer/tizen/xwalk_render_view_ext_tizen.h
The issue is caused by injecting java script to enable firing widget preferences
storage event, and this will skip the initialization progress of extension
process. The patch will make sure inject this script just after the extension
has been initialized.
BUG=https://bugs.tizen.org/jira/browse/TC-2306
> [Tizen] Fix "Uncaught ReferenceError: tizen is not defined" error when starting  an application

- application/browser/application.cc
- application/browser/application.h
- extensions/browser/xwalk_extension_service.cc
- extensions/browser/xwalk_extension_service.h
- runtime/browser/xwalk_app_extension_bridge.cc
- runtime/browser/xwalk_app_extension_bridge.h
- runtime/browser/xwalk_browser_main_parts_tizen.cc
This patch disables EP on Tizen (due to the "Dual" process concept)
At the same time it fixes the issue on app start up.
> [Tizen] Disable Extension process

- runtime/browser/ui/native_app_window_tizen.cc
The IVI homescreen UI has CSS animations, but it still runs and
consume more than 35% CPU power when the UI has been hidden.
This patch allows to pause/resume CSS animations when visibilityChange
events are fired.
BUG=TC-1899
> [Tizen] Enable SetVisibilityChangeAnimations by default

- packaging/crosswalk-libs.spec
This is a leftover caused by the Tizen package split happening somewhat
concurrently with the removal of shared process model support on Tizen:
`crosswalk-libs.spec` was still specifying a flag that has no effect.
> [Tizen] packaging: Stop passing shared_process_mode=1.

- app/tools/android/customize.py
- app/tools/android/make_apk.py
- app/tools/android/make_apk_test.py
1. in case that no --arch specified, add correct ABI prefix for versionCode of each arch package
2. if neither --app-versionCode nor --app-versionCodeBase specified, try to parse out versionCode from versionName
BUG=XWALK-3329
> [Android] improve versionCode generation

- runtime/browser/media/media_capture_devices_dispatcher.cc
When failed to request device we should inform the right status to content,
since there might have some JavaScript listening to the result,  neither success or error.
BUG=https://crosswalk-project.org/jira/browse/XWALK-3133
> "OnSuccess" callback is still invoked when there is not camera

- application/extension/application_widget_storage.cc
In config.xml, if widget.preference absents read_only attribute, the corresponding item
will fail to be inserted into the db. This change will fix it.
> [Tizen] Fix read_only can't be NULL

- application/browser/application_service_tizen.cc
In XWalkContentBrowserClient::GetStoragePartitionConfigForSite, we use partition_domain
equals site.host() which is lowercase. However, in CollectUnusedStoragePartitions, the
installed app id could be case-sensitive. So, it will result in deleting installed app
storage since active_paths is case-sensitive and trash path is lowercase for app id domain.
> [Tizen] Transform app id to lowercase in active StoragePartitionPath

- tools/generate_gclient-xwalk.py
Check effective value of "XWALK_OS_ANDROID" enviroment variable before
appending android deps_contents. Otherwise it still sync "android_tools"
even if export XWALK_OS_ANDROID=0 for non-Android gclient sync.
> Add checking value of "XWALK_OS_ANDROID" during parsing xwalk deps

- runtime/browser/runtime_context.cc
- runtime/browser/runtime_context.h
- runtime/browser/xwalk_ssl_host_state_delegate.cc
- runtime/browser/xwalk_ssl_host_state_delegate.h
- xwalk.gyp
Fix bug XWALK-2498, SSL Certification Error Alert popup repeatedly after click OK.
How: Implement XWalkSSLHostStateDelegate which keeps the cert after click OK.
Test page:https://kyfw.12306.cn/otn/regist/init
BUG=XWALK-2498
(cherry picked from commit bba6fc5b4b923b9af7ee3768c0be562aa809443c)
> [Android] Fix SSL Certification Error Alert

- application/test/application_browsertest.cc
Call content::RunAllpendingInMessageLoop() in ProperMainThreadCleanup(),
otherwise we might end up finishing the main loop with pending events,
leading to this crash in debug mode:
```
[5879:5879:0128/012604:41680213612:FATAL:gpu_process_transport_factory.cc(92)] Check failed: per_compositor_data_.empty().
```
TEST=./out/Debug/xwalk_browsertest --gtest_filter=ApplicationTestApiTest.TestApiTest
> ApiTest: Process all events before tearing down the test suite.

- application/browser/linux/running_application_object.cc
When establishing a communication channel between the 2 process
we create 2 sockets endpoints and one is sent to the process we
are communicating to. After sending, we need to close this fd.
BUG=TC-2361
> Fix leaking file descriptor when a new app is launched

- application/browser/application_system.h
- application/browser/application_system_tizen.cc
- application/browser/application_system_tizen.h
Starting application should take places in RESET event.
This change is required for futher modifications
for appcontrol implementation.
BUG=XWALK-2779
> [Tizen] Use appcore RESET event as application starting point

- packaging/crosswalk-libs.spec
When crosswalk-libs and crosswalk-bin is build for the first time installation of rpms works fine. If next build is incremental libxwalk_backend_lib.so is not removed before next packaging, what causes packaging it into both crosswalk-libs and crosswalk-bin packages. This patch removes libxwalk_backend_lib.so before packaging of crosswalk-libs, when package is build with defined "BUILDDIR_NAME".
BUG=XWALK-3416
> [Tizen] Remove xwalk backend from libs packaging

- runtime/renderer/xwalk_content_renderer_client.cc
- xwalk.gyp
This patch is to fix the issue about placeholder was not cleared in
textarea when enter first character.
Invoke the construction for AutofillAgent(), it will set auto fill
client which will be used when the text was changed in textarea.
BUG=XWALK-3334
> Fix the issue about placeholder was not cleared in textarea.

- runtime/renderer/xwalk_content_renderer_client.cc
Adapt to CL https://codereview.chromium.org/707173004: the code in
3b52dd1 ("Fix the issue about placeholder was not cleared in textarea")
was correct for M40, but we moved to M41 while it was under review and
nobody checked if it still built before merging the pull request.
> Fix the build after 3b52dd1.

- runtime/browser/devtools/remote_debugging_server.cc
- runtime/browser/devtools/remote_debugging_server.h
- runtime/browser/xwalk_runner.cc
Guarantee the right time sequence of resetting TCPServerSocket inside
RemoteDebuggingServer in case of repeatedly invoke it with same tcp port
parameter which leads to the crash.
@pozdnyakov @halton 
Please spare time to help review, thank you very much.
> [Tizen] Fix the crash of RemoteDebuggingServer when repeatedly resetting

- runtime/browser/nacl_host/nacl_browser_delegate_impl.cc
- runtime/browser/runtime.h
- runtime/browser/xwalk_platform_notification_service.cc
- runtime/browser/xwalk_platform_notification_service.h
- sysapps/raw_socket/udp_socket_object.cc
1. Changed xwalk_platform_notification_service to reflect latest api changes
introduced by this change, https://codereview.chromium.org/834263004
2. Updated ppb_nacl_private.h path in nacl_browser_delegate_impl.cc
3. Removed redundant virtual from runtime.h
4. Fixed the missing assignment operator error in udp_socket_object.cc
> Fixed compilation errors on Linux

- runtime/browser/android/xwalk_settings.cc
- runtime/common/xwalk_switches.cc
- runtime/common/xwalk_switches.h
The command of "--allow-running-insecure-content" in assets directory do not effect the Webkit behavior because not set it to Webkit preference.
> [Android] Set the command line to webkit Preference

- runtime/browser/runtime.h
(cherry picked from commit b2e2f4b78f9f8df32db0e24b1b18b51ec8642b07)
> Removing unused (and uninitalized) remote_debugging_enabled_ (from issue 274840)

- app/tools/android/make_apk_test.py
- build/android/generate_xwalk_core_library.py
- build/common.gypi
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
This patch is to disable the use of external startup data for V8
for android platform.
We just disable this feature to unblock the release at present.
Next step we will evaluate the tricky then decide to ship blobs
(for x86, arm, x86-64) or not.
BUG=XWALK-3516
> [Android] Disable the use of external startup data for V8.

- DEPS.xwalk
* d391344 Merge pull request #233 from rakuco/backport-ics-fixes
* b681e58 [Backport] DeviceUtils: Prefer our unzip implementation.
* 9c04ff6 [Backport] Do not overwrite command when using the run_pie wrapper.
This roll includes some upstream backports required to get our device fixes to work again in our ICS devices.
> DEPS.xwalk: Roll chromium-crosswalk (6fcb164 -> d391344)

- DEPS.xwalk
* 0a84d48 Merge pull request #42 from rakuco/webcl-android64-build-fix
* d1c7612 WebCL: Fix the build on Android 64-bits.
* ca0d1ad Merge pull request #41 from junmin-zhu/webclfix
BUG=XWALK-3608
> DEPS.xwalk: Roll blink-crosswalk (921e4ad -> 0a84d48).

- runtime/browser/xwalk_browser_main_parts_android.cc
[Android] Don't specify compositor mode.
composite to mailbox is very old legacy. Don't specify this. CrossWalk relies
on upstream Android policy in terms of compositor mode.
BUG=XWALK-322
> [Android] Don't specify compositor mode.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
setBackgroundColor doesn't work before page loaded. This fix enabled setBackgroundColor for XWalkView.
BUG=XWALK-1910
(cherry picked from commit 54e512a817b1daa02490390f7eb4d340089fd46c)
> [Android] Fix issue with XWalkView::setBackgroundColor

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
Enable transparent XWalkView. Use XWalkView.setBackgroundColor(0) for transparent.
BUG=XWALK-3308
(cherry picked from commit 9ee81a73349e4da8e69d5cd3c1637ad1e5957c04)
> [Android] Enable transparent XWalkView

- runtime/android/core_internal_shell/src/org/xwalk/core/internal/xwview/test/XWalkViewInternalTestRunnerActivity.java
- runtime/android/core_shell/src/org/xwalk/core/xwview/test/XWalkViewTestRunnerActivity.java
`hardwareAccelerated` was always true, so there is no need to check for it, or for it to exist at all.
> XWView{Internal}TestRunnerActivity: simplify hardware acceleration check.

- tizen/mobile/sensor/tizen_platform_sensor.h
Sensor header has changed from "sensor.h" to "sensor_internal.h"
This commit should be merged and submitted to avoid build-break.
https://review.tizen.org/gerrit/#/c/29547/
> [Tizen] Sensor header has changed for new sensor API

- DEPS.xwalk
* e39380a Merge pull request #234 from axinging/xing_crosswalk-11-40.0.2214.91
* 0be529c Revert @viewport enabling patches
This roll includes a cherry-pick from an upstream commit disabling
support for the `@viewport` CSS rule, which was not supposed to be enabled
in M40 and is causing problems in web apps that use it.
BUG=XWALK-3574
> crosswalk-11: DEPS.xwalk: Roll chromium-crosswalk (9a9776f -> e39380a)

- runtime/browser/xwalk_browser_main_parts_android.cc
Enabling the entire set of web platform features currently marked
experimental in Blink is dangerous. The features in this set changes
across Chromium releases, and it can be the case that some of them just
are not ready for production at all.
Case in point: this enables support for the @viewport CSS rule, which
currently has problems and causes regressions for our users (see
XWALK-3574).
If we are interested in enabling certain features (the commit message of
the change being reverted mentions CSS Animations, for example), they
should be enabled individually.
This reverts commit 9255613355cf56547953f2ac816fbc4581659a49.
Related to: XWALK-322
BUG=XWALK-3574
> Revert "[Android] Enable Experimental WebPlatform Features"

- runtime/browser/android/xwalk_dev_tools_server.cc
Remote protocol handler should now report "inspector.html", according to
upstream change: https://crrev.com/a1409c477411b0467b4bc729d9a2c972e79347d1
BUG=XWALK-3522
> [Android] Fix remote debugging doesn't work issue after M41 rebasing

- application/browser/application.cc
- application/browser/application.h
- application/browser/application_service_tizen.cc
- application/browser/application_service_tizen.h
- application/browser/application_system_tizen.cc
- application/browser/application_tizen.cc
- application/browser/application_tizen.h
- application/common/application_data.cc
- application/common/application_data.h
- application/common/manifest_handlers/tizen_app_control_handler.cc
- application/common/manifest_handlers/tizen_app_control_handler.h
- application/common/tizen/app_control_info.cc
- application/common/tizen/app_control_info.h
- application/common/xwalk_application_common.gypi
- application/tools/tizen/xwalk_package_installer.cc
- build/system.gyp
- packaging/crosswalk-bin.spec
- runtime/browser/xwalk_runner.h
- runtime/browser/xwalk_runner_tizen.cc
- runtime/browser/xwalk_runner_tizen.h
This commit passes encoded bundle to extension server
as 'encoded_bundle' variable. This value will be used
by application tizen extension.
Loading start page will check bundle before loading
'normal' starting URL. If application was launched
from appcontrol then appcontrol src is used to
launch application.
BUG=XWALK-1490
Requires:
- https://review.tizen.org/gerrit/#/c/35215/
- https://review.tizen.org/gerrit/#/c/35689/
- https://review.tizen.org/gerrit/#/c/35700/
> [Tizen] Load application according to bundle values

- application/browser/application_tizen.cc
- application/browser/application_tizen.h
Use EventFromNative() function of chromium to emulate hardware
key events from all native platform(x/win/ozone).
Currently, HWKey doesn't work in X11 environment.
BUG=XWALK-3642
> [Tizen] Enable HWKey emulation for all native platform

- runtime/browser/linux/xwalk_notification_manager.cc
- runtime/browser/linux/xwalk_notification_manager.h
- runtime/browser/xwalk_platform_notification_service.cc
- runtime/browser/xwalk_platform_notification_service.h
- xwalk.gyp
The WebNotification of Crosswalk Linux is implemented based on 'libnotify'.
Refering to https://wiki.archlinux.org/index.php/Desktop_notifications,
the 'libnotify' is a desktop independent lib to invoke 'notification server'
through DBus named 'org.freedesktop.Notifications' (on Ubuntu it's 'notify-osd' behind).
There 3 reasons to use 'libnotify':
(1) The Chrome Linux creates 'desktop notification' by self and it's hard to port since most of
code is for 'Rich notification' proveded by extension.
refer to https://developer.chrome.com/apps/richNotifications.
(2) Firefox and WebKit using 'libnotify' to implement WebNotification.
(3) The desktop of Deepin supports 'libnotify' by default.
Add a new class 'XWalkNotificationManagerLinux' to implement logic to invoke 'libnotify':
(1) Init and …
> Implementation of W3C WebNotification for Crosswalk Linux

- runtime/browser/runtime.cc
- runtime/browser/runtime.h
- runtime/browser/xwalk_content_browser_client.cc
- runtime/common/xwalk_content_client.cc
- runtime/common/xwalk_switches.cc
- runtime/common/xwalk_switches.h
In order to support sites using Adobe Flash on desktop we need to
support loading external Flash plugins. This patch added support to
loading Pepper Flash plugin specified from command line. The code
is mostly taken from Chromium chrome/common/chrome_content_client.cc.
The command line switches are the same with Chromium:
--ppapi-flash-path: full path of plugin library
--ppapi-flash-version: optional plugin version
> Add loading Pepper Flash plugin from command line support.

- DEPS.xwalk
This is the latest Linux beta version, and has been in our master branch
for a week without any regressions.
> crosswalk-12: Roll Chromium 41.0.2272.74.

- build/android/generate_xwalk_core_library.py
This is in preparation for M42, where `content_java.zip` includes an
OWNERS file in the `res/` directory that causes apk generation with
make_apk.py to fail.
We now keep a blacklist of files that we do not want to copy in
`CopyDirAndPrefixDuplicates()`.
> generate_xwalk_core_library: Ignore certain files from resources.

- build/android/generate_xwalk_core_library.py
- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkCompressUtil.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
- runtime/android/core_shell/src/org/xwalk/core/xwview/shell/XWalkViewShellActivity.java
I pushed 2 commits for review:
1) libxwalkcore upgrade support
we could upgrade/downgrade libxwalkcore.so when it's changed.
2) a workaround for upgrade from Crosswalk to Crosswalk-lite
When do so, this will leave a unused libxwalkcore.so in lib directory(we can not delete it anyway).
Now I provide an empty libxwalkcore.so which will override the previous one after re-install.
@halton, please help review, thanks!
> libxwalkcore.so upgrade support

- extensions/test/data/iframe_using_document_write.html
- test/android/data/displayAvailableTest.html
- test/android/data/echo.html
- test/android/data/echoSync.html
- test/android/data/framesEcho.html
- test/android/data/window.close.html
This commit is in preparation for M42.
Blink has recently changed the definition of load completion, which exposed some flakiness in our HTML tests: `document.write()` keeps the document stream open and can cause Blink to never consider it has finished loading the document, causing time outs in our tests.
[Chromium bug 426520](https://code.google.com/p/chromium/issues/detail?id=426520) contains more information and a list of commits related to the Blink changes.
While `document.write()` is not strictly needed by the majority of the tests that use it, I chose to keep the calls and just explicitly close the document in most cases, those calls provide some information on what the test is doing (though we could consider replacing those calls with something similar to what Blink does in its …
> tests: Always call document.close() after using document.write().

- application/browser/application.cc
- application/common/application_data.cc
- application/common/application_data.h
- application/common/application_manifest_constants.cc
- application/common/application_manifest_constants.h
We proposed to add recommended window bounds for w3c manifest (see https://github.com/w3c/manifest/issues/310).
1, This is the implementation in crosswalk common which allows user to set window preferred bounds at launch time.
2, It also allows user to set minimum size and maximum size of the window.
> [Common]: Add window size configuration in manifest.

- packaging/gbp-flat-tree.sh
Currently NaCl support is not enabled on Tizen, so we can save a few
gigabytes in the source tarball and the extracted archive if we do not
package NaCl's `toolchain/` directory.
> [Tizen] Do not add NaCl's toolchain to the source tarball.

- DEPS.xwalk
* 903b90a Merge pull request #239 from rakuco/enable-notifications-ics
* e26b72d Merge pull request #238 from axinging/XWALK-3778-zorderontop
* 53a30c4 [Android] Implement ContentViewRenderView.setZOrderOnTop
* f9cb73b [Android] Enable support for notifications on ICS devices.
* ee65235 Merge pull request #237 from leonhsl/master
* 3da3480 [Backport] Revert of Enable ChannelMojo (patchset #3 id:40001 of https://codereview.chromium.org/857483004/)
> DEPS.xwalk: Roll chromium-crosswalk (4281fab -> 903b90a).

- runtime/browser/xwalk_browser_main_parts_android.cc
As we've fixed the root case of bug XWALK-3650 on upstream side:
https://codereview.chromium.org/1003123002/
and currently upstream side disabled ChannelMojo,
and, we've also done back port the disablement commit to Chromium-Crosswalk:
https://github.com/crosswalk-project/chromium-crosswalk/pull/237
now no need to disable ChannelMojo in XWalk side anymore.
BUG=XWALK-3650
> [Android] No need to disable ChannelMojo in XWalk

- application/common/manifest_handlers/tizen_app_control_handler.cc
- application/common/manifest_handlers/tizen_category_handler.cc
- application/common/manifest_handlers/tizen_ime_handler.cc
- application/common/manifest_handlers/tizen_metadata_handler.cc
In current execution flow, there is call of Parse() function
for each handler. Handler should be prepared for situation that
there is no value it expects.
Following handlers are broken:
- AppControl,
- Category,
- Ime,
- Metadata.
BUG=XWALK-3774
> [Tizen] Fix parser handlers

- runtime/browser/runtime_ui_delegate.cc
- runtime/browser/ui/native_app_window_views.cc
Commit above changed the way initialisation is done and expect the
application icon to be set before arriving in Init(). This commit fixes
it.
> Fix crash on startup after https://codereview.chromium.org/933893003

- application/browser/application_security_policy.cc
- application/common/application_data.cc
- application/common/application_manifest_constants.cc
- application/common/application_manifest_constants.h
- runtime/browser/runtime_platform_util_linux.cc
- runtime/browser/xwalk_content_browser_client.cc
- runtime/browser/xwalk_render_message_filter.cc
- runtime/browser/xwalk_render_message_filter.h
- runtime/common/xwalk_common_messages.h
- runtime/renderer/xwalk_content_renderer_client.cc
- runtime/renderer/xwalk_render_process_observer_generic.cc
The XPK package format should support 'scope' field in manifest.json, which is defined in spec: 
https://w3c.github.io/manifest/#scope-member, this patch will enable this feature for XPK package, and open an external link in web browser.
BUG=XWALK-3690
> Enable open external url in web browser.

- DEPS.xwalk
- tools/generate_gclient-xwalk.py
This pull request backports several commits related to XWALK-1894 (which was about tracking all Chromium dependencies with git repositories instead of SVN ones). They are present in Crosswalk >= 8, but we may need to do one additional Crosswalk 7 build, and since the 36.0.1985.144 release is not present in SVN we need those commits for the build to work.
> crosswalk-7: Backport commits that track Chromium dependencies with git.

- app/tools/android/make_apk.py
Some attributes in layout files introduced by upstream is added from
API level 21. These resources are also included in xwalk core library.
When building app by make_apk, command "ant release" will fail if API
level is lower than 21.
BUG=XWALK-3219
> [Android] Fix make_apk fail to pack app when API level is lower than 21

- app/tools/android/app_info.py
- app/tools/android/customize.py
- app/tools/android/make_apk.py
- app/tools/android/manifest_json_parser.py
- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
When crosswalk app running on shared mode, there's a built-in updater to help to download and update crosswalk library apk. By default, the updater will get library apk from Google Play Store.
By this feature, the developer of crosswalk app could self-deploy library apk according to their own requirements, and specify the download url of apk in the app. The updater will fetch the library apk using android download manager.
Setup Method 1: define a meta-data item with the name of "xwalk_apk_url" under application tag in AndroidManifest.xml. For example,
```
<application android:name="org.xwalk.core.XWalkApplication">
<meta-data android:name="xwalk_apk_url"
android:value="http://host/XWalkRuntimeLib.apk" />
...
</application>
```
Setup Method 2: use --xwalk-apk-url option for make_apk.py. …
> [Android] Configure download url of crosswalk library apk

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Use this API to control whether the XWalkView's surface is placed on top of its window.
Note this only works when XWalkPreferences.ANIMATABLE_XWALK_VIEW is false.
BUG=XWALK-3778,XWALK-3742
> [Android] Implement XWalkView.setZOrderOnTop

- runtime/browser/android/xwalk_content.cc
- runtime/browser/android/xwalk_content.h
- runtime/browser/runtime_geolocation_permission_context.cc
- runtime/browser/runtime_geolocation_permission_context.h
- runtime/browser/xwalk_content_browser_client.cc
This patch properly fixes the RequestPermission replies with
PermissionStatus instead of bool as per this patch,
https://codereview.chromium.org/955383003
> Second round of android fixes

- runtime/browser/linux/xwalk_notification_manager.cc
- runtime/browser/linux/xwalk_notification_manager.h
- runtime/browser/xwalk_platform_notification_service.cc
Due to a redundant parameter of the caller has been removed in Version Bump, the callee should be change despondently.
> Fix compiling error of WebNotification of Crosswalk for linux

- app/tools/android/make_apk.py
This is an alternative take at XWALK-3473 (compared to #2892), which is about the error messages and option descriptions we have for the `--app-version`, `--app-versionCode` and `--app-versionCodeBase` options being hard to understand.
While here, I've also simplified the code in both `MakeVersionCode()` and `TryCodeBaseFromVersionName()` and made them more Pythonic and easier to understand.
BUG=XWALK-3473
> [Android] make_apk: Improve the version handling code related messages.

- extensions/renderer/xwalk_module_system.cc
- extensions/test/data/cross_contexts_reference.html
- extensions/test/extension_in_iframe.cc
By default, crosswalk extensions are lazy loaded when they
are actually accessed through Trampoline callbacks. But cross
context reference(JS reference to the leaf extension objects
iframes' contentWindow or popup window by window.open) will
mess up the contexts in the callback which will cause runtime
crash. This commit enable the cross-context reference for
trampoline callback.
BUG=https://crosswalk-project.org/jira/browse/XWALK-3575
> [Extensions] Enable cross-context reference for lazy loading

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentVideoViewClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkWebChromeClient.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/OnShowOnHideCustomViewTest.java
This patch is to fix the crash issue when exiting fullscreen for video.
In the native code, fullscreen requests have been moved to render frame,
then tear down ContentVideoView from content-layer to reduce code
duplication.
Android content embedder has no responsibility for releasing the surface
when exiting fullscreen.
BUG=XWALK-3796
> [Android] Fix the crash issue when exiting fullscreen for video.

- application/browser/application_system.cc
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkPreferencesInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettings.java
- runtime/android/sample/src/org/xwalk/core/sample/OnCreateWindowRequestedActivity.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnCreateWindowRequestedTest.java
BUG=https://crosswalk-project.org/jira/browse/XWALK-3575
[Android] Disable multiple windows support by default
Crosswalk Android will not support multiple windows, such as window.open
by default, unless you set XWalkPreferences.SUPPORT_MULTIPLE_WINDOWS.
[Linux] do not register widget extension the app is not widget
If the application is not a widget, access to exposed "widget" object will cause crash.
> disable multiple window support on Android crosswalk by default.

- runtime/browser/runtime_platform_util_linux.cc
We should not call "std::system"
> Partial revert of #2898

- runtime/browser/xwalk_content_browser_client.cc
- runtime/browser/xwalk_content_browser_client.h
The browser can use the locale via system by default and the --lang command line flag.
BUG=XWALK-2132
> [Android] Use the locale from system by default

- runtime/browser/runtime_platform_util_linux.cc
If the default browser is Chrome, it will start zygote process with
SUID sandbox hepler which fail to check the root privilege. As by
default the prctl() has made the newly started process do not grant
any new privileges.
Also see upstream CL: https://codereview.chromium.org/235983009.
BUG=XWALK-3690
> [Linux] Fix open external URL in browser.

- DEPS.xwalk
Blink-Crosswalk :
e4aaba Fix XDK code so that it uses size_t instead of int.
V8-Crosswalk :
3b7454  [SIMD.js] Fix no exception thrown when get invalid index of
Float32x4Array
7c2b1f1 [SIMD.js] Fix offset of SIMD.Float32x4.load by adding
tarray.byteOffset.
a60b892 Fix XDK code so that it uses size_t instead of int.
> Roll DEPS.xwalk

- app/android/app_template/src/org/xwalk/app/template/AppTemplateActivity.java
Immersive Fullscreen mode does not recover after changing the volume on
the device.
Refer https://github.com/fujunwei/crosswalk-cordova-android/commit/c9e30e77cf71da2d189faecd861c29c04a1548f6
to fix this issue.
BUG=XWALK-3651, XWALK-2367
> [Android] Fix immersive full screen mode doesn't recover.

- app/tools/android/make_apk.py
Commit 2e723a9 ("[Android] make_apk: Simplify TryCodeBaseFromVersionName()") introduced a regression when run with Python 3.
In Python 3, `map()` returns an iterator, so we cannot call `extend()` on it. Fix it by using a list comprehension instead of `map()`.
BUG=XWALK-3903
> [Android] make_apk: Fix Python 3 regression after 2e723a9.

- application/browser/application_security_policy.cc
- application/common/manifest_handler.cc
- application/common/manifest_handlers/widget_handler_unittest.cc
- application/common/package/xpk_package.cc
- extensions/renderer/xwalk_extension_client.cc
- extensions/test/internal_extension_browsertest.cc
- sysapps/common/sysapps_manager_unittest.cc
- sysapps/device_capabilities/display_info_provider_unittest.cc
- sysapps/device_capabilities/storage_info_provider_unittest.cc
- sysapps/raw_socket/tcp_socket_object.cc
- sysapps/raw_socket/udp_socket_object.cc
- sysapps/raw_socket/udp_socket_object.h
Code usually uses std functions which returns a size_t and size_t
is not going to fit into an int on 64 bits. Today it triggers a
warning of potential data loss.
We could disable the warning but it's better to fix the code.
Please note that we have various casts, these are mandatory (though
unfortunate) at the moment because the API in Chromium requires
explicitely an int for example. This can be fixed upstream and
bugs have been reported (e.g. crbug.com/167187).
> Fix compilation on Windows 64 bits

- runtime/android/core_shell/src/org/xwalk/core/xwview/shell/XWalkViewShellActivity.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/NavigateTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnLoadFinishedTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/TestHelperBridge.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
This patch is to display the website's title when open multiple URLs and
press the back or forward button.
The event of update title will be fired in render frame host and title will be
compared to the one in navigation entry, if they are same, the update
title event will not be sent to Java layer.
BUG=XWALK-2333
> [Android] Fix the display for the website's title after navigation.

- DEPS.xwalk
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnRequestFocusTest.java
This also requires us to disable OnRequestFocusTest on Android due to
XWALK-3863.
> crosswalk-13: Roll Chromium 42.0.2311.68.

- app/tools/android/make_apk.py
- app/tools/android/util.py
Even though we do not provide official Crosswalk downloads for ARM64 and
x86_64, we were still nagging users to provide APKs for both
architectures whenever they used make_apk.py in embedded mode.
Stop doing that and only suggest the architectures for which we provide
official downloads (ARM and x86). The code supporting ARM64 and x86_64
remains in place, and we do allow users to specify them in the
command-line if they have build Crosswalk for those architectures
themselves.
While here, reword and improve the message listing all the APKs that
have been created by the make_apk invocation.
> [Android] make_apk: Stop suggesting architectures without downloads.

- xwalk.gyp
Android doesn't need this desktop feature.
> [Android] Fix build by excluding some minimal-ui sources.

- DEPS.xwalk
This is the first stable M42 release. In addition, we are now tracking
ozone-wayland's Milestone-Mazama, which is oz-wl's branch tracking M42.
> Move to Chromium 42.0.2311.90.

- DEPS.xwalk
While here, also make ozone-wayland track Milestone-Mazama, its
M42-based branch.
> crosswalk-13: Move to Chromium 42.0.2311.90, the first M42 stable release.

- DEPS.xwalk
* 6e19c2e Merge pull request #52 from rakuco/revert-faulty-revert
* d00a85f Revert "Revert "Merge 192508 "Focus a page only if the page is different from cu..."""
This roll is to revert a reverted upstream commit that was not supposed
to be pushed to blink-crosswalk (it was reverted temporarily while we
were debugging XWALK-3863).
> DEPS.xwalk: Roll blink-crosswalk (2a0323e -> 6e19c2e).

- build/system.gyp
- xwalk.gyp
To enable WebNotification for Linux defautly. 
Add "pkg-config --cflags gdk-pixbuf-2.0", since some header files need to include files from that patch.
> Enable WebNotification for Linux defautly.

- DEPS
- tools/empty_google_play_services_lib.py
Ever since M42, building Chromium (and consequently Crosswalk) for
Android has required installing the Google Play Services library via the
`android` tool first. However, doing so involves manually accepting an
End User License Agreement (EULA), which makes things very difficult to
automate and also breaks our checkout+configuration process for users
who are building Crosswalk for the first time.
Since that library is actually needed only by Chromium but not
Crosswalk, we have been working around this requirement. When Crosswalk
started tracking Chromium M42, we added a few changes to
chormium-crosswalk. One of them was making gyp not fail if some
directories created by the Google Play Services library were not
present.
This solution needs to be rethought for the upcoming M43, as there is …
> Add a new hook to create Google Play Services's directory structure.

- app/tools/android/make_apk.py
- app/tools/android/util.py
Even though we do not provide official Crosswalk downloads for ARM64 and
x86_64, we were still nagging users to provide APKs for both
architectures whenever they used make_apk.py in embedded mode.
Stop doing that and only suggest the architectures for which we provide
official downloads (ARM and x86). The code supporting ARM64 and x86_64
remains in place, and we do allow users to specify them in the
command-line if they have build Crosswalk for those architectures
themselves.
While here, reword and improve the message listing all the APKs that
have been created by the make_apk invocation.
(cherry picked from commit fc30d8ad1938fe9010a5e2fd7e5fdd3f5816dcd1)
Conflicts:
app/tools/android/make_apk.py
app/tools/android/util.py
> crosswalk-13: [Android] make_apk: Stop suggesting architectures without downloads.

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryListener.java
- runtime/android/core/strings/xwalk_app_strings.grd
- runtime/android/templates/XWalkSdkVersion.template
- tools/reflection_generator/reflection_generator.py
- xwalk.gyp
- xwalk_android.gypi
Before the application loading the Crosswalk runtime library, it is
necessary to make sure the library's package is not tampered and is
exactly the one we published.
The verification process is:
1. Get the binary certificates of the Crosswalk runtime library
via package manager
2. Generate the hash value with SHA256 algorithm from each certificate
3. Check against the preset hash code generated with the the public key
of the signing key
This verification is disabled by default. Use option
"./xwalk/gyp -Dverify_xwalk_apk=1" to enable it.
BUG=XWALK-3804
> [Android] Security check for shared mode

- runtime/android/core_shell/src/org/xwalk/core/xwview/shell/SectionsPagerAdapter.java
- runtime/android/core_shell/src/org/xwalk/core/xwview/shell/XWalkViewSectionFragment.java
- runtime/android/core_shell/src/org/xwalk/core/xwview/shell/XWalkViewShellActivity.java
Replace FragmentActivity with XWalkActivity.
XWalkViewShellActivity use FragmentActivity as its base Activity, this prevent it to benefit from XWalkActivity.
> XWalkViewShellActivity upgrade

- runtime/browser/runtime_url_request_context_getter.cc
- runtime/common/xwalk_switches.cc
- runtime/common/xwalk_switches.h
Limit the disk cache size with a very small number with an command line:
--disk-cache-size = N
where N is the cache is size limit, by bytes.
Zero size means use the default that is 80m.
BUG=XWALK-3821
> [Android] Limit disk cache size

- runtime/browser/xwalk_browser_main_parts_android.cc
Because of multiple profile support, from crosswalk 9 IndexedDB
will be put under profile's subfolder.
Issue is reported from https://github.com/MobileChromeApps/mobile-chrome-apps/issues/554.
BUG=XWALK-4047
(cherry picked from commit 36231eaa85f54622210f9999819cb68994d64432)
> [Android] Back port commits for dropped IndexedDB  to Crosswalk 13

- runtime/browser/xwalk_browser_main_parts_android.cc
Because of multiple profile support, from crosswalk 9 IndexedDB
will be put under profile's subfolder.
Issue is reported from https://github.com/MobileChromeApps/mobile-chrome-apps/issues/554.
BUG=XWALK-4047
(cherry picked from commit 36231eaa85f54622210f9999819cb68994d64432)
> [Android] Back port commits for dropped IndexedDB  to Crosswalk 12

- runtime/browser/xwalk_browser_main_parts_android.cc
Because of multiple profile support, from crosswalk 9 IndexedDB will be put under profile's subfolder.
Issue is reported from https://github.com/MobileChromeApps/mobile-chrome-apps/issues/554.
BUG=XWALK-4047
> [Android] Fix IndexedDB dropped after upgrade from crosswalk 8

- DEPS.xwalk
This is the latest stable Chromium release, and contains a few security
fixes.
> Move to Chromium 42.0.2311.135.

- extensions/extensions.gyp
- sysapps/sysapps.gyp
Compilation was failing in some ffmpeg headers with _rmdir not
defined. This function should be defined by os_support.h in ffmpeg
however it requires a set of defines to be properly set by
config.h. Some changes in blink now add blink headers
in the include path and the config.h of Blink was picked up by
the compiler instead of the config.h of ffmpeg. Note that this
behavior is also in 32 bits but only Windows 64 bits requires
a special set of defines. Fix is to remove the content dependency
which is not needed and depend only on blink_headers instead of the
full blink.
> Fix build on Windows 64 bits.

- runtime/browser/ssl_error_page.cc
- runtime/browser/ssl_error_page.h
- runtime/browser/xwalk_content_browser_client.cc
- xwalk.gyp
When SSL certificate error occurs, show an Interstitial Page to give user a chance to choose to proceed or just close the App.
Add "xwalk::SSLErrorPage" as a child class of "content::InterstitialPageDelegate" with these methods overridden: 
(1) Show()
Creates the instance of "content::InterstitialPage" and show it.
(2) GetHTMLContents()
Provides the html for the interstitial page. The web page includes a link to allow user to ignore the SSL error and proceed the network request.
(3)  OnProceed()
When user chooses to proceed, this function will be invoked to call the "callback" provided by "content".
BUG=https://crosswalk-project.org/jira/browse/XWALK-3668
> Add SSL error page to handle SSL certificate error

- app/android/app_template/proguard-xwalk.txt
- app/tools/android/make_apk.py
Add flag --enable-proguard, disable by default. Only works with
Embedded mode.  Approximately shrinked 150k apk size(tested in x86)
BUG=XWALK-3854
> [Android] Enable proguard for crosswalk to compress apk size

- .gitignore
- DEPS
- app/tools/android/make_apk.py
- build/android/generate_xwalk_core_library.py
- dummy/dummy.cc
- gyp_xwalk
- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryListener.java
- runtime/android/core/strings/xwalk_app_strings.grd
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkCompressUtil.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
- runtime/android/core_shell/AndroidManifest.xml
- third_party/lzma_sdk/download_lzma_sdk.py
- third_party/lzma_sdk/lzma_sdk_android.gyp
- xwalk_android.gypi
- xwalk_android_tests.gypi
- xwalk_core_library_android.gypi
- xwalk_lzma.gypi
This involve 2 commits here:
1. LZMA compression support
Use lzma compress libxwalkcore.so to reduce apk size.
This feature is backport from lite.
2. add support for runtime build flag.
Add --enable_lzma parameter into make_apk.py:
True: compress the libxwalkcore.so into libxwalkcore.so.$arch, then move it into apk's res/raw directory.
False: do not compress libxwalkcore.so (default behavior).
Besides, also include some refactor work, for the shared-mode/embedded mode/embedded mode with lzma support is too much complicated when they involved in one script.
@halton @shawngao5 @lincsoon please help review, thanks!
> Lzma backport

- runtime/browser/xwalk_platform_notification_service.cc
The function 'XWalkPlatformNotificationService::CheckPermissionOnUIThread' has been involved with patch SHA#3eec718b, in it, we should pass the permission check for WebNotification of Crosswalk for Linux also.
> Need to allow WebNotification for Linux in function 'CheckPermissionOnUIThread'

- app/tools/android/make_apk.py
Some attributes in layout files introduced by upstream is added from
API level 21. These resources are also included in xwalk core library.
When building app by make_apk, command "ant release" will fail if API
level is lower than 21.
BUG=XWALK-3219
BUG=XWALK-4103
(cherry picked from commit 541b2f1769871ce5e214ba1615453dc3944662d8)
> crosswalk-13: [Android] Fix make_apk fail to pack app when API level is lower than 21

- xwalk.gyp
Many x86 ABI devices can also run ARM binaries. This patch reorders
the version codes so that the binary with best performance runs on
each device. For example, the x86 APK has the highest version code,
followed by ARMv7. Thus x86 binaries will be preferred for x86
devices and ARMv7 binaries preferred for ARMv7 devices
> [Android] Make the version code for IA higher than for ARM

- xwalk.gyp
Many x86 ABI devices can also run ARM binaries. This patch reorders
the version codes so that the binary with best performance runs on
each device. For example, the x86 APK has the highest version code,
followed by ARMv7. Thus x86 binaries will be preferred for x86
devices and ARMv7 binaries preferred for ARMv7 devices
(cherry picked from commit 73fce35624f950acfbd79136ef27feaf0c3c11c5)
> crosswalk-14: [Android] Make the version code for IA higher than for ARM

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
This patch is to fix the filepicker crash issue on some customized ROMs.
In some ROMs, "/sdcard/Pictures" was removed, verify this directory
before create image file.
BUG=XWALK-3983
(cherry picked from commit 52ab32b1fd637e6652d9250c290b904621f035ca)
> [Android] Fix filepicker crash issue.

- runtime/renderer/pepper/xwalk_renderer_pepper_host_factory.cc
- xwalk.gyp
In order to implement some functionalties these pepper hosts are need in
renderer. These code is copied from src/chrome/renderer/pepper/.
BUG=XWALK-3670,XWALK-3791
> Add PepperFlash hosts in renderer.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
This patch is to fix the unit test errors that introduced by commit
021bfe092f22fd7e266947795f0a8a9541db2e73 "[Android] Provide
asynchronous interface for initializing the Crosswalk library"
Make XWalkViewInternal load native library by self if no external
initializer.
> [Android] Fixed unit tests for XWalkViewInternal

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
This fixes another regression introduced by 021bfe0 ("[Android] Provide
asynchronous interface for initializing the Crosswalk Library") that
caused all new canaries and betas to fail:
```
FAILED: cd ../../xwalk; javadoc -quiet -XDignore.symbol.file -d ../out/Release/xwalk_core_library_docs -classpath /home/builder/src/src/third_party/android_tools/sdk//platforms/android-22/android.jar ../xwalk/runtime/android/core/src/org/xwalk/core/JavascriptInterface.java ../xwalk/runtime/android/core/src/org/xwalk/core/XWalkActivity.java ../xwalk/runtime/android/core/src/org/xwalk/core/XWalkApplication.java ../xwalk/runtime/android/core/src/org/xwalk/core/XWalkInitializer.java ../out/Release/gen/xwalk_core_reflection_layer/wrapper/org/xwalk/core/XWalkExtension.java …
```
> [Android] Use only ASCII characters in XWalkActivity.java.

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
This fixes another regression introduced by 021bfe0 ("[Android] Provide
asynchronous interface for initializing the Crosswalk Library") that
caused all new canaries and betas to fail:
```
FAILED: cd ../../xwalk; javadoc -quiet -XDignore.symbol.file -d ../out/Release/xwalk_core_library_docs -classpath /home/builder/src/src/third_party/android_tools/sdk//platforms/android-22/android.jar ../xwalk/runtime/android/core/src/org/xwalk/core/JavascriptInterface.java ../xwalk/runtime/android/core/src/org/xwalk/core/XWalkActivity.java ../xwalk/runtime/android/core/src/org/xwalk/core/XWalkApplication.java ../xwalk/runtime/android/core/src/org/xwalk/core/XWalkInitializer.java ../out/Release/gen/xwalk_core_reflection_layer/wrapper/org/xwalk/core/XWalkExtension.java …
```
> crosswalk-14: [Android] Use only ASCII characters in XWalkActivity.java.

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
Displaying dialog causes irregular visual artifacts in background if the
default window background is null. For this case, set the background to
screen_background_dark temporarily during the initialization of shared
mode.
BUG=XWALK-4155
> [Android] Fixed visual artifacts at startup in shared mode

- runtime/browser/runtime.cc
- runtime/browser/ui/gtk2_ui.h
- runtime/browser/xwalk_browser_main_parts.cc
- xwalk.gyp
Maybe, we can make GTK2-related UI as an outside library and link to it.
At current stage, we can directly use 'libgtkui.a' (target 'gtk2ui') built by Chrome, in future, we can move these code out as an independent project to add our own code or WebUI eventraully.
With this patch, Crosswalk for Linux can support GTK-based 'File Picker', and input method context, and font to save our effort to move the code case by case.
> To link libgtk2ui of Chrome directly

- application/browser/application_service.cc
XPK file will be unzipped to a temporary directory when launch, the
app ID will change as temporary directory changes. Use package ID can
avoid this issue.
> Use package ID as the application ID when launched from XPK.

- sysapps/device_capabilities/cpu_info_provider.cc
- sysapps/device_capabilities/cpu_info_provider.h
- sysapps/device_capabilities/cpu_info_provider_android.cc
- sysapps/device_capabilities/cpu_info_provider_linux.cc
- sysapps/device_capabilities/cpu_info_provider_win.cc
- sysapps/sysapps.gyp
Implement getting the CPU load from the performance counters API.
This API needs to be initialized so I've added an init() function
which is used only on Windows (other platforms are not doing anything).
> [Windows] Fix SysApp CPU load API.

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
Originally, the application checks shared library in onStart() in order
to initialize the Crosswalk library after jumped into the install page
and switched back to the application. But on tablets, the install
process is not in full screen, so only onResume() get called after
switched back to the application. In this case, the check method won't
be invoked. This patch is to fix this issue.
BUG=XWALK-3953
> [Android] Check shared library in onResume instead of onStart

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSwitches.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
The TextureView of onSurfaceTextureAvailable can't be triggered before PictureLayerImpl::CalculateTileSize
because of using gpu rasterization, so the tile  width is unavailable to render page.
BUG=XWALK-4012
> [Android] Disable gpu rasterization when using animatable xwalk view

- DEPS.xwalk
The reference chrome builds (win/linux/mac) is not used for Crosswalk, so
simply not checking them out to save gclient sync time.
> Ignore checking out reference chrome build

- .gitignore
This is the first step to land the LZMA SDK part of Crosswalk
source tree. Taking the files away from .gitignore will make gclient
clean up the source tree of the old extracted files coming from the old
way to fetch the SDK (downloading it and then extracting it).
We should be able to import the SDK in a following commit without
the infra complaining about overwriting untracked files.
> Remove lzma SDK from .gitignore.

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
This fixes another regression introduced by 021bfe0 ("[Android] Provide
asynchronous interface for initializing the Crosswalk Library") that
caused all new canaries and betas to fail:
```
FAILED: cd ../../xwalk; javadoc -quiet -XDignore.symbol.file -d ../out/Release/xwalk_core_library_docs -classpath /home/builder/src/src/third_party/android_tools/sdk//platforms/android-22/android.jar ../xwalk/runtime/android/core/src/org/xwalk/core/JavascriptInterface.java ../xwalk/runtime/android/core/src/org/xwalk/core/XWalkActivity.java ../xwalk/runtime/android/core/src/org/xwalk/core/XWalkApplication.java ../xwalk/runtime/android/core/src/org/xwalk/core/XWalkInitializer.java ../out/Release/gen/xwalk_core_reflection_layer/wrapper/org/xwalk/core/XWalkExtension.java …
```
> crosswalk-lite: [Android] Use only ASCII characters in XWalkActivity.java.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/XWalkViewInternalTestBase.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/ZoomTest.java
This patch is to implement the zoom APIs(zoomBy, zoomIn, zoomOut,
canZoomIn, canZoomOut), add test case.
The implementation of these APIs was to call the related functions
in ContentViewCore.java
BUG=XWALK-4169, XWALK-4170, XWALK-4171
> [Android] Implement the zoom APIs and add test case.

- xwalk.gyp
Let's use gyp 'copies' to do recursive directory copy.
> Adjust gyp for locale string resource generation.

- xwalk.gyp
Ozone-wayland desktop build was broken, because it is not Tizen but needs same settings. 
We should check against ozone if gtk can be used.
Tizen is only part of platforms that needs ozone.
>  Make gyp check more generious. tizen is subset of ozone

- application/browser/application_service.cc
We do not use hash_set in the file (we use base/ version)
but the style checker complains we should include it.
Instead we can silence the warning and remove the include. I also
took the opportunity to remove some other unused includes.
> Remove unused includes in application_service.cc

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
This patch is to fix the issue that file could not be downloaded.
Download listener was registered, but the downloaded function in
listener was not called.
BUG=XWALK-3647
> [Android] Fix the file download issue.

- tizen/xwalk_tizen.gypi
This is in preparation for M44: `tizen_data_fetcher_shared_memory.h` includes `content/` headers, which in M44 end up depending on `blink_headers`. Since there was no explicit dependency on `content_browser` in the `xwalk_tizen_lib` target, Blink's include paths were not being added to the compiler.
> [Tizen] Explicitly depend on the content_browser target.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
[Android] Correctly handle package name change at build time.
Sometimes there is a need to change the package name of an application at
build time.  This is usually done when more than one version of an application
is required.  For example, a free vs a paid version of an application.
An application package name can be changed with aapt, using the
--rename-manifest-package parameter
See this page for further description:
http://www.piwai.info/renaming-android-manifest-package/
This change has that working correctly.
BUG=XWALK-3569
> XWALK-3569

- app/tools/android/make_apk.py
For Crosswalk build with default option, we only provide libxwalkcore.so.lzma, no dummy library.
BUG=XWALK-3810
> Fix dummy library issue.

- build/android/generate_xwalk_core_library.py
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkInternalResources.java
This patch is to fix the response stream crash issue on android
platform.
The validation_message_bubble.xml was not copied to xwalk_core_library,
add the related zip file to copy list to generate this resource file.
BUG=XWALK-4213
> [Android] Fix the response stream crash issue.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
Sometimes there is a need to change the package name of an application at
build time.  This is usually done when more than one version of an application
is required.  For example, a free vs a paid version of an application.
An application package name can be changed with aapt, using the
--rename-manifest-package parameter
See this page for further description:
http://www.piwai.info/renaming-android-manifest-package/
This change has that working correctly.
BUG=XWALK-3569
(cherry picked from commit 8d0511b748b0f9e41cf70f89b612090fdc95de70)
> [Android] Correctly handle package name change at build time.

- runtime/browser/ui/native_app_window_views.cc
Enable 'minimal-ui' display mode on Windows same way as we have it on Linux desktop.
> [Windows] Enable 'minimal-ui' display mode

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkResourceClientInternal.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnDocumentLoadedInFrameTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/TestHelperBridge.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
Used to notify the client that initial HTML document has been completely loaded and
parsed, without waiting for stylesheets, images, and subframes to finish loading.
This is similar to JavaScript DOMContentLoaded.
BUG=XWALK-4320
> [Android] Implement XWalkResourceClient.onDocumentLoadedInFrame.

- extensions/browser/xwalk_extension_data.cc
- extensions/browser/xwalk_extension_data.h
- extensions/browser/xwalk_extension_service.cc
At the time we reach OnRenderProcessHostClosed the IPC messaging filters are already deleted because the IPC Channel has been closed. We do not need to invalidate the ExtensionServerMessageFilter instance because it's already deleted (and the various overloads of MessageFilter are going to invalidate it) and we should not remove from the current channel because it's been already deleted (removing it will cause its deletion). In fact we do not need to hold a reference of that message filter as it's own by the IPC channel and will be deleted.
BUG=XWALK-4295
> Fix dangling pointer in xwalk extension code.

- build/android/generate_xwalk_core_library.py
Pack cordova 4.0 failed with cordova canary 15.43.355.0, this patch is
to fix it.
The resources copied from components zip file are invalid 9-patch images,
can't be used for Android studio/Maven, so copy these resources from
Chromium source folder directly to CrossWalk.
BUG=XWALK-4313
> [Android] Fix the Cordova package failed issue.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentView.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
onCreateInputConnection is never called even if override it on
XWalkView. Because the view get callbacked is the descendant
ContentView, but not the XWalkView which the user holds.
So pass the callback to the parent view step by step and finally
it can reach to the XWalkView.
BUG=XWALK-3024
> [Android] Deliver onCreateInputConnection to XWalkView

- runtime/browser/xwalk_browser_context.cc
- runtime/common/xwalk_switches.cc
- runtime/common/xwalk_switches.h
This patch is to add the function to change cache path by adding switch
to command line.
If the user data directory was specified in command line, use this path
instead of the default.
BUG=XWALK-2030
> [Android] Implement the feature to change cache path.

- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
This patch is to fix the android tests crashed issue when rebase to M44.
Transfer the wrapper context to PathUtils if the bridge context is
invalid.
BUG=XWALK-4323
> [Android] Fix the crash issue for rebase to M44.

- runtime/browser/xwalk_browser_main_parts_android.cc
WebView does not (yet) save Chromium data during shutdown, so add setting
to aggressively persist DOM Storage to minimize data loss.
http://crbug.com/479767.
Relative commit is https://github.com/crosswalk-project/chromium-crosswalk/commit/5eba2222bb5e2f70618d3fa3017d19a91504e823.
BUG=XWALK-4260
> [Android] Aggressively flush to disk

- runtime/browser/xwalk_browser_main_parts_android.cc
WebView does not (yet) save Chromium data during shutdown, so add setting
to aggressively persist DOM Storage to minimize data loss.
http://crbug.com/479767.
Relative commit is
https://github.com/crosswalk-project/chromium-crosswalk/commit/5eba2222bb5e2f70618d3fa3017d19a91504e823.
BUG=XWALK-4260
(cherry picked from commit 82d74b7dfa2b99373bc7b646682a2156229ab52b)
> Back port the commit of "Aggressively flush to disk" to crosswalk-14

- DEPS.xwalk
.81 update  skipped,
http://googlechromereleases.blogspot.com/2015/06/stable-channel-update.html
http://googlechromereleases.blogspot.com/2015/05/stable-channel-update_25.html
> Roll Chromium 43.0.2357.124

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkPreferencesInternal.java
SurfaceView provids better performance for application which does not need animating the XWalkView. So we use it as default.
BUG=XWALK-4366
> [Android] Use SurfaceView as XWalkView's default render backend.

- DEPS.xwalk
small bugfixes in chromium, v8 and blink not changed
http://googlechromereleases.blogspot.com/2015/06/stable-channel-update_11.html
> Roll chromium 	43.0.2357.125

- extensions/renderer/xwalk_v8tools_module.cc
The tests seemed to be blocked while forcing gc() in JavaScript
however it turns out that the test actually trigger an ASSERT while
calling blink::WebScopedMicrotaskSuppression suppression;
The documentation of WebScopedMicrotaskSuppression explains that you need
to stack allocate this object if you call a script context that will not
cause author script to run and the call is made on the context directly.
We do this in various places in the extension code for this particular
reason. The correct usage of WebScopedMicrotaskSuppression is enforced
in debug with various ASSERTs helping to figure out if you did the right
thing.
In the case of V8ToolsWorks, WebScopedMicrotaskSuppression was triggering
an ASSERT regarding the recursion. In our test code we have some
facilities to catch up when …
> Fix XWalkExtensionsV8ToolsTest.V8ToolsWorks asserting in debug.

- gyp_xwalk
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- runtime/app/android/xwalk_entry_point.cc
- xwalk_android.gypi
- xwalk_core_library_android.gypi
Add build flag & cocos2d init code to support cocos2d optimization
Disabled cocos2d build by default.
Enable it with build flags change in gyp_xwalk:
args.append('-Denable_webrtc=0') => args.append('-Denable_webrtc=1')
args.append('-Duse_lzma=1') => args.append('-Duse_lzma=0')
args.append('-Denable_cocos2d=0') => args.append('-Denable_cocos2d=1')
> [Android] Crosswalk Cocos2d optimization

- DEPS.xwalk
- packaging/skia-perf-regression-copy-surface-as-draw.patch
- tools/patch_skia.py
Backport https://codereview.chromium.org/1161063003 which fixes
an old Skia performance regression on popular devices like Samsung
Galaxy S3. The above CL was landed in M45 and therefore will be
part in our next rebase. However this regression is a pressing issue
for some stakeholders so they can move to newer versions of Crosswalk
(as opposed to stick with crosswalk 7 the last version where there
is no performance regression). As we do not fork Skia repository
the proposed solution is to apply a patch when running gclient. That
way it is easier to remove when rebasing to M45. Please note that the
provided patch file has been modified to apply on M44.
> Backport patch to fix an old skia regression

- DEPS.xwalk
Removed one temp patch from chromium, fixed rebase conflight in chromium,
https://crrev.com/1172453003 and removed .DEPS.git from our commits ass well,
because no used in upstream anymore.
Removed terporary fix in DEPS.xwalk
> Roll chromium 44.0.2403.52

- DEPS.xwalk
This is the latest stable release, and contains a few security fixes as
listed in the release notes here:
http://googlechromereleases.blogspot.de/2015/06/chrome-stable-update.html
> Roll Chromium 43.0.2357.130.

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkActivityDelegate.java
- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/XWalkDialogManager.java
- runtime/android/core/src/org/xwalk/core/XWalkInitializer.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryInterface.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryLoader.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
- xwalk_core_library_android.gypi
Some activities might want to integrate the initialization process but
can't extend XWalkActivity due to its limitations. So we extract this
part from XWalkActivity for other's reuse. This is especially for the
integration into Cordova Plugin.
> [Android] Extract the initialization process from XWalkActivity

- tools/installer/common/crosswalk.info
- tools/installer/common/generate-changelog.sh
- tools/installer/common/installer.include
- tools/installer/common/wrapper
- tools/installer/debian/build.sh
- tools/installer/debian/changelog.template
- tools/installer/debian/control.template
- xwalk.gyp
- xwalk_installer.gypi
This work is still experimental, so here be dragons!
The whole patch is inspired by the code in Chromium itself in
`src/chrome/installer/linux` that is used to generate RPMs and Debian
packages.
Consequently, this means that at least for now we are not following
Debian's best practices:
- We do not build from a source tarball; instead, the new gyp target
`xwalk_installer_linux_debian` creates a package out of the files
generated by the `xwalk` target.
- To achieve that, we make some fairly low-level calls to `dpkg-deb`
directly.
We may revisit the way we create packages in the future; for now, this
is the quickest way to start having Debian packages and also saves us
some work if/when we decide to ship NaCl's support files, as we do not
need to care about downloading all the toolchain …
> Add code to build Debian desktop packages.

- DEPS.xwalk
- packaging/skia-perf-regression-copy-surface-as-draw.patch
- tools/patch_skia.py
A Skia CL (https://codereview.chromium.org/607993002 ) made CrossWalk
regress on some devices such as Galaxy S3. Upstream proposed a CL to fix
the performance regression in
https://codereview.chromium.org/1161063003. Alexis backported upstream's
fix to CrossWalk master in
https://github.com/crosswalk-project/crosswalk/pull/3096. But it's hard
to backport to CrossWalk 14 due to many dependency issues in Skia
repo. Not only the real fix is needed to backport but also other
dependent CLs are needed to backport. So I propose to revert the origin
Skia CL which introduced the regression as a workaroud for CrossWalk 14.
Before the regressed CL, Skia use a fallback draw as the first choice
for surface copy.  In this CL I remove other copy methods before the
fallback draw. This is the same logic …
> Work around Skia performance regression

- runtime/common/xwalk_content_client.cc
Sencha Touch did not determined correct device type on tablet devices
by match the keyword of 'Mobile' in user agent.
There is 'Mobile' in the user agent before 'Safari' by default when
we load xwalk shell on a phone, we don't need add the 'Mobile' again
before 'Crosswalk'.
Original commit is fa1b87549450d1b2fcaee048b9acf5891deb3aa5.
BUG=XWALK-4318
> Delete the reduplicate 'Mobile' user agent

- runtime/browser/android/xwalk_content.cc
- runtime/browser/runtime_url_request_context_getter.cc
- runtime/browser/runtime_url_request_context_getter.h
- runtime/browser/xwalk_browser_context.cc
- runtime/browser/xwalk_browser_context.h
In http request header, the accept languages was set by default
value, e.g. "en-us,en", user cann't modify it, this patch is to
update the accept languages when user invoke the embedding API.
Http request header was created before the embedding API invoked,
so the accept languages could noly be updated.
BUG=XWALK-3463
> [Android] Update the accept languages in http request header.

- xwalk_installer.gypi
Depending on that file triggered a nasty and hard to debug build system
issue on non-Ozone Linux builds:
* In this configuration, we depend on the `gtk2ui` gyp target in
`src/chrome`.
* This target on its turn causes gyp to process
`src/chrome/chrome_resources.gyp`.
* The `packed_resources` target there, even if not depended upon by any
target we build, has one `copies` section where it first processes
Chromium's language files and then copies them to `locale/`.
* This is the same location where we also copy our locale files in the
`xwalk_strings` target.
This combination of factors caused a race condition where Chromium's
language files could overwrite Crosswalk's and we would then end up with
the wrong PAK files and a UI with no text.
Fix it by just removing the dependency on …
> Debian packaging: stop depending on locales/en-US.pak.

- tools/patch_skia.py
Calling "git" on Windows does not work, as the only executable that is
guaranteed to be in `%%PATH%%` because of depot_tools is `git.bat`.
Do the same thing some depot_tools scripts do and prefer the latter when
on Windows.
> [Windows] Fix patch_skia.py.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkResourceClientInternal.java
Change the API version number of XWalkResourceClient.onDocumentLoadedInFrame
to 5.0.
BUG=XWALK-4530
> [Android] Change the API version number of onDocumentLoadedInFrame

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkCookieManagerInternal.java
- runtime/browser/android/cookie_manager.cc
- test/android/core/javatests/src/org/xwalk/core/xwview/test/CookieManagerTest.java
- tools/reflection_generator/reflection_generator.py
- xwalk_android.gypi
Expose XWalkCookieManager to developer, Change the name of XWalkCookieManager
to XWalkCookieManagerInternal for generating wrapper and bridge of the class.
(cherry picked from commit c5504aa8376b80fd51877815ec69e85679f91ec7)
Conflicts:
tools/reflection_generator/reflection_generator.py
> [Android] Backport patch to export XWalkCookieManager

- runtime/common/xwalk_content_client.cc
Sencha Touch did not determined correct device type on tablet devices
by match the keyword of 'Mobile' in user agent.
There is 'Mobile' in the user agent before 'Safari' by default when
we load xwalk shell on a phone, we don't need add the 'Mobile' again
before 'Crosswalk'.
Original commit is fa1b87549450d1b2fcaee048b9acf5891deb3aa5.
BUG=XWALK-4318
(cherry picked from commit 98cee250dfbfce81787ccd2d60e305e5889bdc82)
> Backport to delete the reduplicate 'Mobile' user agent

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkUIClientInternal.java
Support css meta theme-color on Android Lollipop+(5.0+). For Android
version older than 5.0, this doesn't work.
BUG=XWALK-4305
> [Android] Support theme-color on Android Lollipop+(5.0+)

- app/android/runtime_activity/src/org/xwalk/app/XWalkRuntimeActivityBase.java
- test/android/util/runtime_client/src/org/xwalk/test/util/XWalkRuntimeClientTestGeneric.java
The test case was executed when xwalk was not ready, so the runtime view
sometimes was null. This patch is to wait for the xwalk ready then execute
test case.
BUG=XWALK-4549
> [Android] Fix the test case crash issue on runtime client.

- DEPS.xwalk
* aa27a06 Merge pull request #255 from lincsoon/ics_support
* 47c889b Revert "Remove AccessibilityInjector support."
* 23d6848 Revert "Update minSdkVersion and targetSdkVersion constants."
* a4817ef Revert "Remove ICS support from SurfaceTexture"
* 7a5b3b8 Revert "Remove unnecesary ApiCompatibilityUtils calls."
* c318f2c Revert "Remove ICS support in C++ code."
* bcacd79 Revert "Remove ICS code from Clank Cast"
* 5ef0b96 Revert "Remove ICS checks in ExternalNavigationHandler."
* 583e141 Revert "Remove ICS check in ChromeContextMenuPopulator."
* 6128913 Revert "Remove ICS check in AccessibilityUtil."
* 11652b0 Revert "Remove ICS check in SwipeRefreshHandler."
* 5a14f97 Revert "Remove ICS check in BookmarkUtil."
* 75b8c1b Revert "Remove ICS support in VSyncMonitor."
* 97de6f7 Revert "Remove …
> DEPS.xwalk: Roll chromium-crosswalk (1b72e88 -> aa27a06).

- DEPS.xwalk
- build/common.gypi
- packaging/crosswalk-do-not-build-several-chromium-dependencies.patch
- sysapps/common/sysapps_manager_unittest.cc
- sysapps/device_capabilities/av_codecs_provider_ffmpeg.cc
- sysapps/device_capabilities/av_codecs_provider_unittest.cc
This is the latest Linux beta release so far. Thanks to Olli Raula for
starting the work.
FFMPEG had to be temporarily rolled forward so that we can continue
building it as a shared library for the time being.
See https://codereview.chromium.org/1141703002 and
https://codereview.chromium.org/1198653005/ for more information.
A few commits in chromium-crosswalk were also dropped because of this
change, as the code which loaded additional ffmpeg libraries via
--proprietary-codec-lib-path does not work anymore. Users wishing to
provide a different ffmpeg version with additional codecs now need to
replace the version built by Crosswalk instead of adding it alongside
the existing library.
Related to: XWALK-3705
Related to: XWALK-4574
> Roll Chromium 44.0.2403.81.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkUIClientInternal.java
This reverts commit b1ea577cd3152dd3a522955ff5e9634062427cf1.
Reason: broke Crosswalk 14 beta build from scratch.
```
runtime/android/core_internal/src/org/xwalk/core/internal/XWalkUIClientInternal.java:105: error: method setStatusBarColor in class ApiCompatibilityUtils cannot be applied to given types;
ApiCompatibilityUtils.setStatusBarColor(view.getActivity().getWindow(),color);
^
required: Activity,int
found: Window,int
reason: actual argument Window cannot be converted to Activity by method invocation conversion
```
BUG=XWALK-4305
> Revert "[Android] Support theme-color on Android Lollipop+(5.0+)"

- build/common.gypi
- packaging/crosswalk-libs.spec
- tools/build/linux/FILES.cfg
- tools/build/win/FILES.cfg
- tools/installer/common/installer.include
- tools/installer/debian/build.sh
- xwalk.gyp
- xwalk_installer.gypi
This is a follow-up to f5be8735 ("Roll Chromium 44.0.2403.81").
That version of Chromium M44 includes changes in Chromium's version of
ffmpeg that got rid of the ffmpegsumo library: there is only
`libffmpeg.so` now, and it is a regular library.
In practice, this means the following changes had to be made for a build
from scratch to work again:
* References to `libffmpegsumo.so` in Tizen's spec files have been
dropped. `libffmpeg.so` is built in `lib/` and does not need special
treatment.
* References to `libffmegsumo.so` in the Debian packaging files have also
been dropped. This was a bit more intricate than the above, as some
code in `build.sh` had to be moved to `do_package()` because even though
the Debian packages are built with `component=static_library` the
`ffmpeg_component` …
> Stop referencing ffmpegsumo and fix usage of libffpeg.so.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkUIClientInternal.java
For Android version older than 5.0, this doesn't work. This is based on
3d89fb8.
BUG=XWALK-4305.
> [Android]Support css meta theme-color on Android Lollipop+(5.0+).

- app/android/app_hello_world/AndroidManifest.xml
- app/android/app_template/AndroidManifest.xml
- app/android/runtime_client_embedded_shell/AndroidManifest.xml
- app/android/runtime_client_shell/AndroidManifest.xml
- app/tools/android/test_data/extensions/adextension/AndroidManifest.xml
- build/android/generate_xwalk_core_library.py
- build/android/generate_xwalk_core_library_aar.py
- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkApplication.java
- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/XWalkMixedResources.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkInternalResources.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- runtime/android/core_shell/AndroidManifest.xml
- xwalk_core_library_android.gypi
XWalkApplication's role is to help the app to get resources from the
XWalkRuntimeLib.apk in shared mode, but it also cause the
inconvenience of developers. So we integrate the whole resources to
the app even in shared mode to get rid of this class.
> [Android] Deprecate XWalkApplication

- xwalk.gyp
Build pass both enable/disable use_icu_alternatives_on_android.
icu feature reducing size: 2.419M
Bug=xwalk-4520
> [Lite] ICU rebasing bug fix

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkNotificationServiceImpl.java
App will generate notifications, all of them will be cancelled when
XWalkView started, this patch is to fix this issue.
BUG=XWALK-3763
> [Android] Don't cancel the notification at startup time.

- runtime/android/core_internal/src/org/xwalk/core/internal/ClientCertLookupTable.java
- runtime/android/core_internal/src/org/xwalk/core/internal/ClientCertRequestHandlerInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/ClientCertRequestInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkResourceClientInternal.java
- runtime/browser/android/xwalk_contents_client_bridge.cc
- runtime/browser/android/xwalk_contents_client_bridge.h
- runtime/browser/android/xwalk_contents_client_bridge_base.h
- runtime/browser/xwalk_content_browser_client.cc
- runtime/browser/xwalk_content_browser_client.h
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnReceivedClientCertRequestTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/TestHelperBridge.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
- tools/reflection_generator/reflection_generator.py
- xwalk.gyp
- xwalk_core_library_android.gypi
Support for client-side SSL certificate for Android
Bug=XWALK-2697
> XWALK-2697

- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnReceivedClientCertRequestTest.java
Disable the test case for certificate request since the device can not
access network.
> [Android] Disable the certificate request test case.

- test/android/core/javatests/src/org/xwalk/core/xwview/test/CookieManagerTest.java
- tools/reflection_generator/bridge_generator.py
- tools/reflection_generator/java_class.py
- tools/reflection_generator/wrapper_generator.py
This patch is to fix the crash issue when running file transfer tests in
mobilespeck.
The exposed APIs were not initialized when the explicit constructor was
not existed in the internal java file.
Add the default constructor to call init function.
BUG=XWALK-4667
> [Android] Fix the crash issue when running file transfer.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Follow the design of chrome for android, initialize NetworkChangeNotifier after loadXWalkLibrary.
BUG=XWALK-4514
> [Android] Initialize NetworkChangeNotifier after loadXWalkLibrary

- application/browser/application_system_tizen.cc
LaunchFromAppID could returning the NULL pointer.
but it does not checked before used
> Fix crash issue when app control event was invoked

- DEPS.xwalk
1021d6 [Backport] Rather than dropping stale navigations, resurrect the navigation entry.
f19d78 [Backport] Don't discard navigations.
BUG=XWALK-4378
> DEPS.xwalk: Roll chromium-crosswalk (ecadc9->1021d6)

- build/android/merge_jars.py
- xwalk_core_library_android.gypi
Almost all the code that was present in the script is also available in
Chromium itself, so it makes no sense to have the uptenth
reimplementation of GetCommandOutput() or calls to jar(1).
Additionally, the handling of the --jars option was broken: it always
assumed that each path would be properly escaped by gyp and could be
eval()ed directly into Python. Not only does calling eval() in this
context make zero sense, but it also fails with targets such as
`android_support_v13_javalib`, which is passed as an absolute path
without escaped shell quotes. This is a problem starting with M45, as
that target is depended upon by `content_java`.
The --classes-dir option is also useless: instead of creating and
cleaning directories inside the build directory, just use a different
temporary …
> [Android] Rewrite merge_jars.py.

- build/common.gypi
- gyp_xwalk
Build with "-Ddisable_web_audio" will reduce size by 0.3M.
Details of patch:
(1) The macro 'DISABLE_WEB_AUDIO' will disable the WebAudio related
code in 'content' folder.
(2) Set the building flag 'use_openmax_dl_fft' to 0 will disable the
WebAudio related code for Android in blink eventrually, leveraging
the macro 'ENABLE_WEB_AUDIO'.
> To disable WebAudio solely.

- xwalk_core_library_android.gypi
Build entire java libraries before generate xwalk_shared_library
BUG=XWALK-4746
> [Android] Fixed building error

- xwalk_core_library_android.gypi
Build entire java libraries before generate xwalk_shared_library
BUG=XWALK-4746
(cherry picked from commit f8a31199a3ba1af8dfb72f0a08fe8a9f9a4a00de that
was mistakenly committed directly to the crosswalk-14 branch)
> crosswalk-15: [Android] Fixed building error

- app/android/runtime_client/src/org/xwalk/app/runtime/extension/JsStubGenerator.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkCoreExtensionBridge.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkExtensionBindingObject.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkExtensionBindingObjectStore.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkExtensionClient.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkRuntimeExtensionBridge.java
- app/tools/android/test_data/entry/constructor-jsStub.html
- app/tools/android/test_data/extensions/constructorJsStubGen/src/com/example/jsStub/Person.java
- extensions/android/java/src/org/xwalk/core/internal/extensions/XWalkExtensionAndroid.java
- extensions/common/android/xwalk_extension_android.cc
- extensions/renderer/xwalk_js_stub_wrapper.js
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkExtensionInternal.java
"Destroy" was being spelled "destory" in a lot of places, from comments
to variables to method names.
> Spell "destroy" correctly in several places in the code base.

- extensions/browser/xwalk_extension_function_handler.cc
- extensions/browser/xwalk_extension_function_handler.h
- extensions/browser/xwalk_extension_service.cc
- extensions/extension_process/xwalk_extension_process.cc
- runtime/browser/android/cookie_manager.cc
- runtime/browser/android/net/android_stream_reader_url_request_job.cc
- runtime/browser/runtime_url_request_context_getter.cc
- tizen/mobile/sensor/tizen_platform_sensor.cc
Chromium is deprecating MessageLoopProxy and moving towards the TaskRunner API instead. [Bug 465354](http://crbug.com/465354) contains more information.
Since we can already do this in M44, do it separately from moving to M45 so that the size of the M45 patch is smaller. Thanks to Olli Raula and Mrunal Kapade for doing the majority of the work.
Most of the changes are mechanic:
* `base::MessageLoopProxy::current()` becomes `base::ThreadTaskRunnerHandle::Get()`.
* `scoped_refptr<base::MessageLoopProxy>` becomes `scoped_refptr<base::SingleThreadTaskRunner>`.
* `base::Thread::message_loop_proxy()` becomes `base::Thread::task_runner()`.
The only noteworthy change is in `XWalkExtensionFunctionHandler`, caused by the fact that `ThreadTaskRunnerHandle::Get()` enforces an assertion that was …
> Remove use of MessageLoopProxy and deprecated MessageLoop APIs.

- application/browser/application_system_tizen.cc
- application/browser/application_tizen.cc
- application/browser/application_tizen.h
- application/common/application_manifest_constants.cc
- application/common/application_manifest_constants.h
- application/common/manifest_handlers/tizen_setting_handler.cc
- application/common/manifest_handlers/tizen_setting_handler.h
- runtime/common/xwalk_common_messages.h
- runtime/renderer/xwalk_render_process_observer_generic.cc
- runtime/renderer/xwalk_render_process_observer_generic.h
This (manually) reverts the following commits:
* 94d0859a0920b991d4294e8ab8969e61bc734888 ([Tizen][Runtime] Enable pause/resume web application JS engine)
* 3bf14f044e46f9ebe772b004a34c33eb75c201f9 ([Tizen] Enable background-support attribute in settings element)
* 01be04ccda9da53680a8e723278aa6eb5d068e41 ([Tizen] Use appcore RESET event as application starting point)
All the code relied upon suspending Blink's shared timer, which has been
removed in M45 -- see upstream bug 463143 for all related commits and
rationale.
Prepare for M45 by removing the code separately so that the change is
more visible and easier to revert in the future should we ever implement
support for it differently.
BUG=XWALK-1148
BUG=XWALK-1497
BUG=XWALK-1498
BUG=XWALK-2779
> [Tizen] Remove support for pausing and resuming the JS engine.

- app/android/runtime_client/src/org/xwalk/app/runtime/extension/JsStubGenerator.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkCoreExtensionBridge.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkExtensionBindingObject.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkExtensionBindingObjectStore.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkExtensionClient.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkRuntimeExtensionBridge.java
- app/tools/android/test_data/entry/constructor-jsStub.html
- app/tools/android/test_data/extensions/constructorJsStubGen/src/com/example/jsStub/Person.java
- extensions/android/java/src/org/xwalk/core/internal/extensions/XWalkExtensionAndroid.java
- extensions/common/android/xwalk_extension_android.cc
- extensions/renderer/xwalk_js_stub_wrapper.js
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkExtensionInternal.java
"Destroy" was being spelled "destory" in a lot of places, from comments
to variables to method names.
(cherry picked from commit fc05522563aef9ce9d6014678a0431131832a91d)
> crosswalk-15: Spell "destroy" correctly in several places in the code base.

- DEPS.xwalk
Back port from master to fix WebCL memory issues.
03513e1 Merge pull request #68 from hujiajie/crosswalk-15/44.0.2403.130
6487c8c [Android] Use RefPtr to ref the associated WebCLContext in WebCLObject.
> DEPS.xwalk: Roll blink-crosswalk(0afa83e -> 03513e1)

- extensions/common/xwalk_extension_server.cc
- extensions/common/xwalk_extension_server.h
- extensions/test/data/bulk_data_transmission.html
- extensions/test/external_extension.cc
- extensions/test/xwalk_extensions_browsertest.cc
from native to JS using the shared memory handle.
This is the second fix for this bug. The previous fix uncovered this
one.
The crash was because the memory handle we send to the extension process
was null. The fact it was null is because on Windows it was failing to
share the handle of the shared memory between the render process and
the extension process. GiveReadOnlyToProcess was failing inside
windows specific code, more exactly in DuplicateHandle, a win API
which was returning an error code of 6. 6 means the handle we're passing
is invalid. Turns out that while we store the renderer process handle
earlier (so we can share the data between the two), the open() call
on the process is too early. It seems like Windows can't work with this
handle unless the process is open right before. …
> [Windows][Extensions]Fix render process crash when sending data

- xwalk.gyp
The dependency was introduced when we moved to M42, as there was a
layering violation that introduced a dependency on extensions/ that we
had to provide ourselves (see comment #30 in http://crbug.com/449919).
This has since been fixed upstream (http://crbug.com/477096), so we can
remove the workaround and get rid of a lot of unnecessary dependencies.
> [Tizen] Stop depending on the extensions_browser gyp target.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkAPI.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentView.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- tools/reflection_generator/java_method.py
- tools/reflection_generator/wrapper_generator.py
Delegate ContentView's performLongClick() to XWalkView so that developer
can override XWalkView's performLongClick() or setOnLongClickListener() to
disable copy/paste action bar.
A new annotation XWalkAPI.delegate is used to ensure that the callback
from XWalkViewInternal to XWalkView is one-way and the actual implementation
of callback in XWalkView side is specified via XWalkAPI.preWrapperLines.
BUG=XWALK-4786
> [Android] Add support disabling copy/paste in XWalkView

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Sometimes XWalkView was created in onXWalkReady(), if the activity which
owns XWalkView was destroyed, pauseTimers() will be invoked, then
JavaScript timer was also paused. Reentry this activity, the
resumeTimers() was not called since XWalkView creation was later than
onResume().
Invoke resumeTimers() explicitly when XWalkView was created.
BUG=XWALK-4676
> [Android] Fix the javascript was not executed issue.

- runtime/android/dummy_lib/dummy_lib.cc
- xwalk_android_tests.gypi
A top-level directory called "dummy" is a terrible choice that confuses
pretty much anyone that looks at it -- there is only a single-line
explanation in the only file there giving a hint that it is something
Android-specific.
Move the directory to runtime/android and call it "dummy_lib" instead;
this way, the association with Android is clear and people can at least
know that it is a library.
> [Android] Move dummy/dummy.cc to a reasonable location, rename.

- runtime/browser/ui/native_app_window_views.cc
Ensure at least the ImageSkiaRep's for the default 1x scale is always
attached to ImageSkia's storage so that HasRepresentation for the
default 1x scale return a meaningful true then the icon updator can get
a chance to retrieve the 1x scale Rep.
BUG=XWALK-4763
> [Linux] Fix the incorrect icon update issue

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Decouple XWalkContent from FrameLayout, this can reduce the XWalkView's 4 level view hierarchy to
to 3.
BUG=XWALK-4760
> [Android] Optimizing layout hierarchy of XWalkView

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkResourceClientInternal.java
Add XWalkResourceClient.doUpdateVisitedHistory() to notify the host
application to update its visited links database.
BUG=XWALK-4739
> [Android] Add new API - doUpdateVisitedHistory()

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkResourceClientInternal.java
Toast is better option to inform user network is wrong than dialog. Dialog is very
annoying because user need to click "OK" button. Toast needs no user action.
BUG=XWALK-4804
> [Android] Change Dialog of onReceivedLoadError to Toast

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
This patch is to implement clearFormData(), this API removes the
autocomplete popup from the currently focused form field, if present.
It does not remove any saved form data from this WebView's store.
BUG=XWALK-4243
> [Android] Implement the embedding API for clearFormData().

- runtime/DEPS
- runtime/browser/xwalk_content_browser_client.cc
- runtime/browser/xwalk_permission_manager.cc
- runtime/renderer/xwalk_content_renderer_client.cc
- runtime/renderer/xwalk_content_renderer_client.h
- xwalk.gyp
- xwalk_android.gypi
Currently, crosswalk only support clearkey CDM, but doesn't support
widevine CDM. This PR will enable it in crosswalk for android.
The spec can refer https://w3c.github.io/encrypted-media/.
The steps to verify this feature:
Add "enable_widevine=1" to the GYP_DEFINES. Then run gyp and build.
The following link is for DRM testing. If 'com.widevine.alpha' keySystem
is not supported, the below video won't play.
http://shaka-player-demo.appspot.com/?dash;asset=assets/car_segmenttemplate.mpd
> [Android] Enable widevine support

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkHttpAuthHandlerInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkResourceClientInternal.java
- runtime/browser/android/xwalk_http_auth_handler.cc
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/OnReceivedHttpAuthRequestTest.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/TestHelperBridge.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/XWalkViewInternalTestBase.java
- tools/reflection_generator/reflection_generator.py
- xwalk_android.gypi
- xwalk_core_library_android.gypi
This patch is to move onReceivedHttpAuthRequest from XWalkClient to
XWalkResourceClientInternal.
Customer could override this API to display dialog or show other
customize information.
BUG=XWALK-3477
> [Android] Move onReceivedHttpAuthRequest to XWalkResourceClientInternal.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkLaunchScreenManager.java
The launch screen dialog has its own lifecycle. The main Activity's attributes
should not be directly applied to the launch screen dialog. So remove these here.
As to XWALK-4688, if you want to apply custom on xwalk_launch_screen, you need
to call window.screen.show(); in your javascript.
BUG=XWALK-4688, XWALK-4687, XWALK-4261
> [Android] Fix the launch screen not working correctly

- build/common.gypi
- gyp_xwalk
- runtime/browser/xwalk_content_browser_client.cc
- runtime/browser/xwalk_content_browser_client.h
- xwalk.gyp
To disable Web Speech
With build flag "-Ddisable_speech=1" binary size is reduced by 0.11M.
Due to syntax limitation of gyp, import 'modules_gypi_generator.py'
to synthesize the 'third_party/WebKit/Source/modules/modules.gypi'
directly to exclude the disabled '*.idl' files.
> To disable Web Speech

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Besides XWalkPreferences method, app developers want to config a single
XWalkView, to use SURFACE_VIEW or TEXTURE_VIEW by application's xml
without impact on other XWalkViews.
BUG=XWALK-4531
> [Android] Add method to config XWalkView render backend

- runtime/android/core/src/org/xwalk/core/XWalkDialogManager.java
- runtime/android/core/strings/xwalk_app_strings.grd
1. Change the wording on the positive button from “Continue” to
“Get Crosswalk”
2. Change "application store" to "app store"
3. The term “runtime” has no meaning to an end user, it is a highly
technical term. Change it to "Add-on"
BUG=XWALK-4801
> [Android] Make shared mode prompt more clearly

- app/tools/android/make_apk.py
The android project default ignores files starting with an "_" when building.
Override the default in ant.properties to include all files when package
resources.
BUG=XWALK-2223
> [Android] Fix the issue about hangonman doesn't display cloud backgroud.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
XWalkView has two constructor with two parameters,
so XWalkView(this, null) is ambiguous.
BUG=XWALK-3553
> [Android] Update XWalkView API usage example

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkLaunchScreenManager.java
The launch screen dialog has its own lifecycle. The main Activity's attributes
should not be directly apply to the launch screen dialog. So remove these here.
As to XWALK-4688, if you want to apply custom on xwalk_launch_screen, you need
to call window.screen.show(); in your javascript.
BUG=XWALK-4688, XWALK-4687, XWALK-4261
(cherry picked from commit b43c7cf68b73985130c2b3533fdda7dedfa77aff)
> [Android] Fix the launch screen not work correctly

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkLaunchScreenManager.java
If the background image was set with large resolution, it will be
crashed when "getDrawable()" on some devices.
Catch the OOM error to avoid crash.
BUG=XWALK-4778
> [Android] Fix the out of memory issue.

- DEPS.xwalk
Stop tracking OpenCL headers from Khronos's SVN repository and use our
git mirror on GitHub instead.
The OpenCL headers were the only Crosswalk dependency that required
Subversion, which meant that additional programs were required to check
out Crosswalk, and more settings had to be tuned for people behind
corporate proxies.
Discussed in:
https://lists.crosswalk-project.org/pipermail/crosswalk-dev/2015-August/003039.html
> Track OpenCL headers from our git repository.

- DEPS.xwalk
Stop tracking OpenCL headers from Khronos's SVN repository and use our
git mirror on GitHub instead.
The OpenCL headers were the only Crosswalk dependency that required
Subversion, which meant that additional programs were required to check
out Crosswalk, and more settings had to be tuned for people behind
corporate proxies.
Discussed in:
https://lists.crosswalk-project.org/pipermail/crosswalk-dev/2015-August/003039.html
(cherry picked from commit 109990fca57094d545ca58b55814cefe77e8191d)
> crosswalk-15: Track OpenCL headers from our git repository.

- DEPS.xwalk
**I do not intend to make a new Crosswalk 14 release because of this commit. My intention with it is to make sure all the branches we currently support and work on use OpenCL from git so we can remove the SVN references and instructions from the website**
Stop tracking OpenCL headers from Khronos's SVN repository and use our
git mirror on GitHub instead.
The OpenCL headers were the only Crosswalk dependency that required
Subversion, which meant that additional programs were required to check
out Crosswalk, and more settings had to be tuned for people behind
corporate proxies.
Discussed in:
https://lists.crosswalk-project.org/pipermail/crosswalk-dev/2015-August/003039.html
(cherry picked from commit 109990fca57094d545ca58b55814cefe77e8191d)
> crosswalk-14: Track OpenCL headers from our git repository.

- application/browser/application.cc
- application/browser/application.h
- application/browser/application_tizen.cc
- application/browser/application_tizen.h
- runtime/browser/runtime.cc
- runtime/browser/runtime.h
- runtime/browser/runtime_ui_delegate.cc
- runtime/browser/runtime_ui_delegate.h
- runtime/browser/ui/native_app_window.cc
- runtime/browser/ui/native_app_window.h
- runtime/browser/ui/native_app_window_desktop.cc
The 'Runtime' class overrides 'GetDisplayMode' method (from the base
'content::WebContentsDelegate' class) so that media query "display-mode"
features are initialized properly.
> Initialize media query "display-mode" features properly

- runtime/browser/ui/desktop/download_views.cc
- xwalk.gyp
And most likely on Mac as well.
https://github.com/crosswalk-project/crosswalk/pull/320 broke the
build by using classes not added to the build.
Fix the build by adding the new class from #320 to the build but it's
most likely that the Download feature doesn't yet work on Windows
because there are still code guarded in #ifdef in the original
commit. I've created XWALK-4969 to enable it which shouldn't require
much work.
> Fix build on Windows.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
There are two related changes in this patch with the same goal of paving the way for the M45 rebase, where the upstream code handling the loading of Android resources has changed. Most of what we had to do there also applies to M44, so the patch is being landed in master in order to make it clear in the commit history what is being done and why.
1. Make the code easier to understand.
* Set up the resource interception infrastructure in a separate
function.
* Also have a separate function for determining a resource ID after
XWALK-3469 made the code a bit harder to follow.
* Have variables with clear names such as `isSharedMode` and
`isTestApk` to indicate our intents and what is being checked. We
were previously relying on package name checks or ID comparisons
that did not make any sense …
> [Android] Simplify the resource interception code in XWalkViewDelegate.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- runtime/browser/android/net_disk_cache_remover.cc
- runtime/browser/android/net_disk_cache_remover.h
- runtime/browser/android/xwalk_content.cc
- runtime/browser/android/xwalk_content.h
- test/android/core/javatests/src/org/xwalk/core/xwview/test/ClearCacheForSingleFileTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
This patch is to supply an API to clear partial cache.
User could transfer the url to ClearCacheForSingleFile() to clear the
cache for this url.
Add test case for ClearCacheForSingleFile().
BUG=XWALK-4609
> [Android] Implement the API to clear cache for single file.

- app/tools/android/make_apk.py
- build/android/generate_xwalk_core_library.py
- gyp_xwalk
- xwalk_android_tests.gypi
- xwalk_core_library_android.gypi
- xwalk_lzma.gypi
Besides the runtime build option provided in make_apk.py, we enable lzma
at build time also.
Due to the architecture issue, we need involve dummy library at
build time.
BUG=XWALK-4947
> Enable LZMA function at build time.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
This reverts commit 1907a9c2b7d59765d41efab9c0a2824f8bced4f9.
Reason: broke several Android tests.
- org.xwalk.runtime.client.embedded.test.ContactsTest#testContacts
- org.xwalk.runtime.client.embedded.test.DeviceCapabilitiesTest#testDeviceCapabilities
- org.xwalk.runtime.client.embedded.test.ExternalExtensionTest#testExternalExtensionAsync
- org.xwalk.runtime.client.embedded.test.MessagingTest#testMessaging
- org.xwalk.runtime.client.embedded.test.NativeFileSystemTest#testNativeFileSystem
- org.xwalk.runtime.client.embedded.test.PauseResumeTest#testPauseAndResume
- org.xwalk.runtime.client.embedded.test.PresentationTest#testPresentationDisplayAvailable
- org.xwalk.runtime.client.embedded.test.ScreenOrientationTest#testScreenOrientation
- …
> Revert "Encode the data by base64 to load that as a data: URL"

- app/android/app_template/res/values-v14/theme.xml
- app/android/app_template/src/org/xwalk/app/template/AppTemplateActivity.java
- app/android/runtime_activity/src/org/xwalk/app/XWalkRuntimeActivityBase.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
The moment when the XWalkViewBridge is added to the XWalkView, the
screen flashes black. The reason is when the SurfaceView appears
in the window the fist time, it requests the window's parameters
changing by calling IWindowSession.relayout(). But if the window
already has appropriate parameters, it will not refresh all the
window's stuff and the screen will not blink. So we add a 0px
SurfaceView at first. This will recreate the window before the
activity is shown on the screen, and when the actual XWalkViewBridge
is added, it will just continue to use the window with current
parameters. The temporary SurfaceView can be removed at last.
BUG=XWALK-4966
> [Android] Fix the error that the screen flashes at startup

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Make it clear that the developer can use XWalkView with the old way. But
to take the advantage of shared mode, the XWalkActivity is necessary.
> [Android] Update the comment about shared mode

- xwalk.gyp
With M45, we can use upstream's newly-introduced repack_action.gypi to
simplify our work: it takes care of all the inputs/action/output
boilerplate.
Upstream CL: https://codereview.chromium.org/216013003
> gyp: Use repack_action.gypi.

- application/common/application_manifest_constants.cc
- application/common/application_manifest_constants.h
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/browser/android/xwalk_content.cc
Add xwalk_view.background_color in manifest. This supports set XWalkView's
background color in manifest.json. This can also avoid white screen on start.
Set XWalkView's background color in manifest.json:
"xwalk_view": {
"background_color": "#ff01abcd"
}
Note: Color is in Alpha/Red/Green/Blue order.
BUG=XWALK-4809,XWALK-4963
> [Android] Implement XWalkView background color in manifest

- experimental/presentation/presentation_api.js
- runtime/android/core_internal/src/org/xwalk/core/internal/extension/api/presentation/PresentationExtension.java
- runtime/android/core_internal/src/org/xwalk/core/internal/extension/api/presentation/XWalkPresentationContent.java
Modified the implementation of Presentation API on Android, according
to the new version of W3C Presentation API Spec:
http://www.w3.org/TR/presentation-api/
The major change of the new implementation is to introduced the
session object, which is responsible for representing a presentation
session, and setup a message channel between host screen and remote
display screen. And the major API (e.g. startSession) returns Promise
object instead of callback functions.
BUG=XWALK-4646
> Presentation API Reimplementation

- xwalk.gyp
- xwalk_android.gypi
The runtime code actually needs xwalk.pak to be present to work. This is
evident when building a target like xwalk_extensions_browsertest from
scratch -- it depends on xwalk_runtime, but not xwalk_pak, and tests
InternalExtensionTest.InternalExtension and
XWalkExtensionsIFrameTest.CrossContextsReferenceShouldNotCrash were
failing when xwalk.pak was absent.
BUG=XWALK-4776
> gyp: Make xwalk_runtime depend on xwalk_pak.

- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkRuntimeExtensionManager.java
- app/tools/android/make_apk.py
- extensions/android/java/src/org/xwalk/core/internal/extensions/XWalkNativeExtensionLoaderAndroid.java
- extensions/common/android/xwalk_native_extension_loader_android.cc
- extensions/common/android/xwalk_native_extension_loader_android.h
- extensions/extensions.gyp
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkNativeExtensionLoaderInternal.java
- runtime/app/android/xwalk_jni_registrar.cc
- runtime/browser/xwalk_browser_main_parts_android.cc
- runtime/browser/xwalk_browser_main_parts_android.h
- test/android/runtime_client/javatests/src/org/xwalk/runtime/client/test/NativeExternalExtensionTest.java
- test/android/runtime_client_embedded/javatests/src/org/xwalk/runtime/client/embedded/test/NativeExternalExtensionTest.java
- test/android/util/runtime_client/src/org/xwalk/test/util/RuntimeClientApiTestBase.java
- tools/reflection_generator/reflection_generator.py
- xwalk_android.gypi
- xwalk_android_tests.gypi
- xwalk_core_library_android.gypi
Before this patch, Crosswalk only supports the extensions written in
Java.
With this patch, Crosswalk can load native C++ extensions by calling a
Java API, which will tell the aboslute location to the XWalkExtensionService.
Then when the extension service starts, it will load the extension from
the proper path. To achieve this purpose, add a new option
"--native-extensions" for make_apk.py. By setting it to the location of
the folder, which contains the c++ extension library, the make_apk will
pack them into the final APK file.
Also, this patch creates two unit tests for native external extensions
for runtime client, including shared/embedded modes.
BUG=XWALK-4749
> [Android]Support external extensions written in C++ on Android

- DEPS.xwalk
caused by upstream dropping support for ICS.
> Resolve no notification on Android 4.0. It's a regression

- tools/fetch_deps.py
Fetching Crosswalk on Android with git caches is currently broken when
calling `gclient sync` without `-j1`, as two different entries in
Chromium's DEPS use the same repository and when multiple gclient jobs
are running in parallel more than one can try locking the same
repository cache at the same time. This has been reported upstream as
[http://crbug.com/516347](bug 516347).
This does not seem to affect the build.chromium.org slaves because they
all call `gclient sync` with `--ignore_locks`, so there is no
possibility of lock contention. Despite the scary name, the option looks
safe enough for our bots to use as well.
BUG=XWALK-4882
> [Tools] Pass "--ignore_locks" to gclient sync when fetching deps.

- tools/fetch_deps.py
Fetching Crosswalk on Android with git caches is currently broken when
calling `gclient sync` without `-j1`, as two different entries in
Chromium's DEPS use the same repository and when multiple gclient jobs
are running in parallel more than one can try locking the same
repository cache at the same time. This has been reported upstream as
bug 516347.
This does not seem to affect the build.chromium.org slaves because they
all call `gclient sync` with `--ignore_locks`, so there is no
possibility of lock contention. Despite the scary name, the option looks
safe enough for our bots to use as well.
BUG=XWALK-4882
(cherry picked from commit fe27485cac0ba1d6a1346e9274cb32f0074e3bfd)
[backported so that the Crosswalk Lite bots do not have locking problems when running hooks]
> [Lite][Tools] Pass "--ignore_locks" to gclient sync when fetching deps.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- test/android/util/src/org/xwalk/test/util/XWalkTestUtilBase.java
The data type of "text/html" can be parsed, so doesn't need be escaped before
loading.
BUG=XWALK-3571
> [Android] Encode the data by base64 to load that as a data: URL

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
The language's format from OS sometimes is like as "zh_CN", but the
adopted format by HTTP protocol is "zh-cn".
Replace "_" with "-" and change the alphabet to lower case.
BUG=XWALK-5045
> [Android] Refine the accept language from OS.

- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/XWalkDialogManager.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryDecompressor.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryInterface.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryLoader.java
- runtime/android/core/strings/xwalk_app_strings.grd
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
- xwalk_android.gypi
Specify the directory from where the infrastructure loads native
libraries from the package org.xwalk.core instead of
org.xwalk.core.internal. This is to support for the lite mode and future
download mode in which native libraries don't exist in the default
directory.
> [Android] Control library directory from upper level

- gyp_xwalk
Modules like Base,Skia,cc,V8 use "increase size for speed" to
run faster.In Lite we prefer to decrease size.
With lzma, 677K binary size reduced for embedded_shell.apk
Without lzma, 820K binary size reduced.
Slight performance downgrade found,it is an acceptable balance.
> Add 'Optimize for size, Os' compile option

- runtime/android/core/src/org/xwalk/core/XWalkLibraryLoader.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
This is an experimental featurea that provides developers with a way to
download the Crosswalk runtime in background silently without
interrupting the end-user.
To take a trial, you have to remove libxwalkcore.so, icudtal.dat,
xwalk.pak from xwalk_core_library, and put these files in a zip file.
Then please host this zip file, and specify the url with a meta-data
element named "xwalk_lib_url" inside the application tag in the Android
manifest.
You also must implement the interface XWalkUpdate.XWalkSilentUpdateListener.
> [Android] Experimental silent download mode

- runtime/app/android/xwalk_jni_registrar.cc
- runtime/browser/android/xwalk_dev_tools_server.cc
- xwalk.gyp
- xwalk_android.gypi
Empty the Java-bounding functions of C++, once devtools is disabled to
avoid incident invoke from Java.
BUG=XWALK-5051
> Fix occasional crash.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- test/android/util/src/org/xwalk/test/util/XWalkTestUtilBase.java
The data type of "text/html" can be parsed, so don't need be escaped before
loading.
BUG=XWALK-3571
(cherry picked from commit 776dcd72649f71c92755524f32ed4681449250c8)
> [Android] Backport patch to encode the data by base64

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentView.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Expose onTouchEvent to XWalkView so that developer can override
XWalkView.onTouchEvent to intercept touch event. Usually super.onTouchEvent
is called within onTouchEvent override method so we keep a default
onTouchEvent override in XWalkView to connect to the default touch event
handler within ContentViewCore.
BUG=XWALK-4879
> [Android] Expose onTouchEvent to XWalkView

- runtime/common/xwalk_content_client.cc
- runtime/common/xwalk_content_client.h
@seanlong can you please advise if we need to add standard url scheme after above change? As I see constants.cc already has "app" Application Scheme already defined. Not sure about the difference between standard and savable scheme.
> M46 gardening: adapt to https://codereview.chromium.org/1272113002

- DEPS.xwalk
Roll DEPS.xwalk
Chromium-Crosswalk:
39fd36ec84256d6b068c4a1c1bbe32556c9a69d4
[Lite] Remove "-fstack-protector" compile option
v8-Crosswalk:
dc8dae13d2da8b9bbbaff8ba3abe5c86c6f0fa36
Add 'Optimize for size, Os' compile option
Both "Optimize for size, Os" and "fno-stack-protector" are controlled by the "use_optimize_for_size_compile_option" flag.
So update the DEPS.xwalk rev roll for both v8 and chromium.
> [Lite] Roll DEPS.xwalk

- runtime/browser/ui/native_app_window_desktop.cc
- runtime/common/xwalk_switches.cc
- runtime/common/xwalk_switches.h
By default there is no inspector support (right click) but
when passing --enable-inspector it is possible to launch the
inspector.
We need that flag so that crosswalk-app-tools can use it to
enable/disable inspector (especially when you actually make
a release of your .msi or application, you don't want the
inspector to be enabled).
BUG=XWALK-4858
> Implement --enable-inspector command line.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentView.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Use XWalkAPI.delegate annotation for reflection generation script
to generate delegate methods in XWalkView within which View's protected
methods is invoked.
BUG=XWALK-4899, XWALK-4895
> [Android] Expose onScrollChanged/onFocusChanged to XWalkView

- runtime/browser/ui/native_app_window_desktop.cc
- runtime/browser/ui/native_app_window_desktop.h
fixed leak of the menu itself if you right click several times.
> Fix right click empty menu when inspector is disabled, also

- extensions/common/xwalk_external_extension.cc
XWalkExternalExtension.
Make sure the constructor gives a NULL value.
> Fix issue in coverity : Uninitialized pointer field in

- extensions/dotnet_extension_sample.gyp
- extensions/extensions_tests.gyp
On a machine where ninja creates a lot of parrallel tasks we were
running in some build errors :
- The .NET extensions tests depends on the .NET bridge but it was
not listed as an explicit dependency.
- In the multiple extensions tests (where we have several extensions in
the same directory with multiple bridges) we were copying multiple times
the bridge and renaming it according to each extension in the directory.
We can't do these tasks in parallel because we copy then rename the bridge for
extension 1 and then in the same time we copy and rename the bridge
for extension 2. Turns out that the bridge file may be accessed by
both actions running in parrallel. We make it sequential : we copy
the bridge for extension 1, then rename it, then copy the bridge for
extension 2 and then rename …
> Fix flakiness when building the .NET extensions tests

- xwalk_android_tests.gypi
icudtl.dat should be used only if flag
use_icu_alternatives_on_anroid == 0
> [Lite] icudtl.dat should be controlled by icu flag.

- DEPS.xwalk
- gyp_xwalk
To disable WebCL    
Leverage existing flag "enable_webcl" to disable functions and exclude
related code in Blink.    
Reduced size = 44K
> Disable webcl

- extensions/common/xwalk_external_extension.cc
Make sure the constructor gives a NULL value.
(cherry picked from commit 84cf207b398be9bb5ff8044b465fda7746fef85a)
> crosswalk-16: Fix issue in coverity : Uninitialized pointer field in XWalkExternalExtension.

- app/tools/android/customize.py
- app/tools/android/make_apk.py
- app/tools/android/make_apk_test.py
- app/tools/android/test_data/manifest/manifest_and_app_root/index.html
- app/tools/android/test_data/manifest/manifest_and_app_root/manifest.json
This patch is to fix manifest.json was always used issue.
In application's folder, if manifest.json was existed, it will be
always used even if it was not specified in command line.
e.g. if manifest.json was existed and app was packaged by "make_apk.py
--package=org.xwalk.test --name=test --app-root=path-to-app
--app-local-path=index.html", this way won't work, manifest.json will be
used.
BUG=XWALK-5131
> [Android] Fix the issue about manifest.json was always used.

- runtime/browser/ui/native_app_window_desktop.cc
- runtime/browser/ui/native_app_window_desktop.h
Fix right click empty menu when inspector is disabled, also fixed leak of the menu itself if you right click several times.
(cherry picked from commit 02474babbc8779f9c8ebb9b9e55a3ac1cf3e758c)
> crosswalk-16: Backport inspector context menu fixes.

- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryLoader.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
Please find intent to implement @ https://lists.crosswalk-project.org/pipermail/crosswalk-dev/2015-October/003133.html
This PR contains the basic silent download mode implementation.
1) The runtime APK will be downloaded in the background silently without any user interaction.
2) The essential ingredients (libxwalkcore.so, classes.dex, icudtl.dat and xwalk.pak) will be extracted from the downloaded APK and saved to application's private storage.
3) Download mode will be working exclusively, that is, at the first launch, even if the runtime APK had been installed on the device, it still requests to download the dedicated runtime APK and only load the core libraries from that APK
BUG=XWALK-5121
> [Android] Add basic silent download mode support

- build/android/generate_resource_map.py
- tools/reflection_generator/reflection_generator.py
Remove the implementations of `Touch()` that we have in our scripts and
use the one from the `build_utils` module instead.
> [Tools] Stop reimplementing Touch() in different scripts.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Android M return an empty Intent rather than a null intent to onActivityResult
from camera activity; updated the function to check for an empty Intent
if the intent is not null.
BUG=XWALK-5076
> [Android] Unable to obtain image taken from Camera on Android M

- build/android/merge_jars.py
- xwalk_core_library_android.gypi
Add a new parameter to merge_jars.py, --build-dir, and exclude JAR files
which lie outside this directory from merging.
The immediate effect is that android-support-v13.jar will not be part of
xwalk_core_library.jar anymore. The dependency on
org.apache.http.legacy.jar was already dropped with chromium-crosswalk
commit 5909ede ("[Android] Stop using org.apache.http classes in
AccessibilityInjector").
We should not bundle android-support-v13.jar in xwalk_core_library.jar,
as it can cause build problems for users of the embedding API that also
pull the same package themselves or via another dependency. Gradle, for
example, produces the following error message:
```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
at …
```
> [Android] Only merge JARs which we have built ourselves.

- DEPS.xwalk
* a49762a Merge pull request #294 from rakuco/drop-deprecated-api-from-accessibility-code
* 5909ede [Android] Stop using org.apache.http classes in AccessibilityInjector.
Related to: XWALK-5092
> DEPS.xwalk: Roll chromium-crosswalk (e23bfe2 -> a49762a)

- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
Commit 8705e6288cbdf8a93da42a181749e6c5859b8064 ("[Android] Support
XWalkRuntimeLib.apk download for multiple architectures") broke the
build:
```
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkUpdater.java:53: error: end tag missing: </code>
* <p>To download the Crosswalk runtime APK for the specified CPU architecture, <code>xwalk_apk_url<code>
^
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkUpdater.java:53: error: end tag missing: </code>
* <p>To download the Crosswalk runtime APK for the specified CPU architecture, <code>xwalk_apk_url<code>
^
```
> [Android] Fix javadoc build after 8705e628.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Android M return an empty Intent rather than a null intent to onActivityResult
from camera activity; updated the function to check for an empty Intent
if the intent is not null.
BUG=XWALK-5076
(cherry picked from commit 894f3e5bdca5174af3b078c4da6987b10fdba9f2)
> [Android] crosswalk 16: Backport patch to obtain image taken from Camera on Android M

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Android M return an empty Intent rather than a null intent to onActivityResult
from camera activity; updated the function to check for an empty Intent
if the intent is not null.
BUG=XWALK-5076
(cherry picked from commit 894f3e5bdca5174af3b078c4da6987b10fdba9f2)
> [Android] crosswalk-15:Backport patch to obtain image taken from Camera on Android M

- xwalk.gyp
In runtime/browser/devtools/xwalk_devtools_frontend.h/.cc, the class
xwalk::NativeAppWindowDesktop is needed, but the source files of this
class's implementation at:
runtime/browser/ui/native_app_window_desktop.h/.cc are excluded within
Android build. As XWalkDevToolsFrontend is not needed for Android
platform for now, we'd better exclude its source files for Android
build as well.
> Fixed the fail to build issue on Android.

- gyp_xwalk
We have not synced the gyp_xwalk script with its upstream counterpart
for a few rebase cycles, so there is some catch up to do. This change
imports the following commits to gyp_chromium, making it up-to-date with
Chromium 45.0.2454.93:
* 6248cdd [iOS] Add a repack steps to iOS upstream for unit tests
* 013831e Roll src/tools/gyp/ to 29e94a3285ee899d14d5e56a6001682620d3778f.
* bf94627 A couple of cleanups for gyp_chromium
* 9449f96 Disable circular gyp dependency check on Mac
* e6f8f83 Put 'tools' directory at front of import path.
* 0826b63 [WebView] Pack the .pak files for all the locales.
> gyp_xwalk: Sync with gyp_chromium.

- app/tools/android/make_apk.py
Uses "atexit" to print a deprecation message at the end of any invocation of make_apk.
Related to XWALK-5629
> Add deprecation message to make_apk

- DEPS.xwalk
- build/common.gypi
- gyp_xwalk
(1) to support to exclude WebAudio related code in Blink.
(2) Enable 'WebMIDI' by default due to the bug in disabling patch.
Roll DEPS.xwalk
Blink-Crosswalk:
742cd913572586a2ecb3f142f41931692c8e233e
To exclude code of WebAudio in Blink
> [Lite] Maintain gyp_xwalk

- xwalk.gyp
In runtime/browser/devtools/xwalk_devtools_frontend.h/.cc, the class
xwalk::NativeAppWindowDesktop is needed, but the source files of this
class's implementation at:
runtime/browser/ui/native_app_window_desktop.h/.cc are excluded within
Android build. As XWalkDevToolsFrontend is not needed for Android
platform for now, this fix exclude its source files for Android
build as well to make the linking pass.
This issue is brought by patch 1d1067e1 which hasn't excluded all of the
unnecessary source files for Debug build.
Error log is posted below:
[307/436] SOLINK lib/libxwalkcore.so
FAILED: if [ ! -e lib/libxwalkcore.so -o ! -e lib/libxwalkcore.so.TOC ]; then /home/jonathan/projects/crosswalk/crosswalk-android/src/third_party/android_tools/ndk//toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686 …
> [Android] Fixed the fail to link issue when building Debug build.

- runtime/browser/xwalk_content_browser_client.cc
- runtime/browser/xwalk_content_browser_client.h
- runtime/browser/xwalk_presentation_service_delegate_win.cc
- runtime/browser/xwalk_presentation_service_delegate_win.h
- xwalk.gyp
This patch contains the implementation of the W3C Presentation
API for Crosswalk on Windows.
With the current chromium-crosswalk revision (which is based on M45
upstream version) the Presentation API bindings correspond to
http://www.w3.org/TR/2015/WD-presentation-api-20150701.
Missing API features: there is no bindings for incoming presentaion
sessions and hence message exchange is also not available.
Missing implementation features (TBD in the following patches):
- CSP rules for presentation URL
- UI for presentation window selection
> [Win] Presentation API implementation

- app/tools/android/make_apk.py
- build/android/generate_xwalk_core_library.py
BUG=XWALK-5668
libxwalkcore.so.lzma is mistakenly placed in libs/
It is expected in /res/raw.
> [lite] embedding mode cannot work with lzma.

- DEPS.xwalk
- gyp_xwalk
Roll DEPS.xwalk
Blink-Crosswalk:
977d6795ee1c9b208f30ca70f1196005c5e3e381
To resolve build problem of disabling WebMIDI
> [Lite] Disable Web MIDI API by default

- xwalk.gyp
Fix Crosswalk on Windows build after e8ca4dfd65147a2474341426d448473696381b4c
> [Windows] Build fix

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientCallbackHelper.java
Originally, onPageFinished is invoked directly. In contrast,
onPageStarted is invoked through message loop. So the order of these two
methods maybe reversed.
BUG=XWALK-4849
> [Android] Put the call to onPageFinished in message loop

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkUIClientInternal.java
This is supported to work on Android >= Lollipop (5.0). Otherwise it will always show a gray background in the task switcher.
BUG=XWALK-4305
> [Android] Support theme color at task switcher on Lollipop+(5.0+)

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkAPI.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- tools/reflection_generator/java_method.py
Provide a separate function for SurfaceView to set visibility.
Keep XWalkView.setVisibility() as an embedding API, the base class's
setVisibility will be called even if xwalk is not ready.
Mark "setSurfaceViewVisibility()" as reserved function to initial later.
In XWalkViewInternal.java, "setVisibility" is just an auxiliary function
to generate XWalkView.setVisibility().
BUG=XWALK-5700
> [Android] Fix the issue of cordova 4.x app launch crash.

- build/android/lzma_compress.py
- xwalk.gyp
- xwalk_android.gypi
This runtime APK is used in silent download mode and the size is
significantly reduced by using LZMA compression to compress the
key components of the runtime APK.
We put the compressed ingredients to assets and then package them as
an APK, this is intented to utilize the APK integrity/signature
check for security concern.
This is a partial implementation for XWALK-5214
> [Android] Add build target for XWalkRuntimeLibLzma.apk

- DEPS.xwalk
- build/android/merge_jars.py
- xwalk_core_library_android.gypi
The first commit rolls `DEPS.xwalk` after crosswalk-project/chromium-crosswalk#299. The second one backports #3350.
Related to: XWALK-5092
> crosswalk-16: Backport fixes for XWALK-5092.

- build/common.gypi
Without default values, the first exec of gyp_xwalk triggered by
gclient sync would fail.
> [Lite] Add default values for new introduced flags

- extensions/common/xwalk_extension_server.cc
- extensions/common/xwalk_extension_server.h
This issue is introduced by patch e5d3b6c2, the solution only works
for Windows but crashes Android. Use defined(OS_WIN) macro to enable
it only for Windows and restore the old implementation on other
platforms.
BUG=XWALK-5029
> Fixed the bulk data transmission crash on Android

- application/browser/application_protocols.cc
Rationals:
- The ApplicationDataCache is supposed to be shared.
- This avoids crashes on exit if there are WebConents instances apart from
Application (like it happens during presentation sessions)
> Keep single instance of ApplicationDataCache

- runtime/browser/xwalk_browser_main_parts_android.cc
From 14ea977ff2e300fd131d3ca8ff6f5311f5fd1df8 in Chromium, there is a
checkpoint before executing JavaScript. The URLs that
ExecuteJavaScript can be invoked on are restricted to chrome-controlled
URLs.
This change blocks all xwalk test with evaluating JavaScript. This patch
is to add additional interface for evaluating javascript in test mode.
Related bug: XWALK-5241
> [Android] Fix test error of evaluating javascript

- build/android/maven_pom.gypi
- build/common.gypi
- runtime/android/maven/xwalk_core_library.pom.xml.in
- runtime/android/maven/xwalk_shared_library.pom.xml.in
- xwalk_core_library_android.gypi
This patch set contains two commits. The first one adds all the required
plumbing for generating the Maven POM files we have for xwalk_core_library and
xwalk_shared_library as part of our build.
Quoting the commit message:
> Currently, the Maven POM XML files part of the Crosswalk Maven repository
> in download.01.org are generated by Maven itself when we call
> `mvn deploy:deploy-file` with `-DgeneratePom=true`.
>
> While it works for most cases, it is not a flexible solution: if one needs
> to include more information in the POM file, such as a dependency
> declaration, the POM file cannot be automatically generated.
>
> This patch adds template POM files for both xwalk_core_library and
> xwalk_shared_library that are preprocessed during the build and turn into
> POM files that can be …
> [Android] Generate the Maven POM files and depend on support-v4.

- runtime/common/xwalk_content_client.cc
Adjust Crosswalk code to https://codereview.chromium.org/1272113002.
We need to make sure that the app:// scheme is added correctly
otherwise GURL will not parse it correctly and the tests are
not going to load at all.
BUG=XWALK-5650
> M46 Gardening : Fix remaining failures on Linux.

- test/base/xwalk_test_launcher.cc
It turns out that the flags were not set in V8 so gc() was not exposed.
The reason why the flag was not set is because V8 initialization happens
before AdjustChildProcessCommandLine() in TestLauncherDelegate is called.
This behavior has slighty changed in M46. It turns out that we need to
set the flags in V8 before the Content delegate is created. In a normal
xwalk run this happens automatically for us : content will pull the command
line flags and pass them to V8. But in the tests the construction is more
convulated and the content delegate is created before
AdjustChildProcessCommandLine() is called and thus V8 is already set up.
As a verification the two other tests using gc() (and thus passing
--expose-gc to the JavaScript flags) are setting the flags before
ContentDelegate is created. …
> M46 Gardening : Fix failing tests where gc() in JavaScript was undefined

- DEPS.xwalk
- runtime/browser/blink_upstream_version.h.in
- xwalk.gyp
The most notable change in this roll is that this upstream release was
made after Blink was merged into the Chromium git repository. It also
contains some security fixes, as described in the [release announcement](http://googlechromereleases.blogspot.com/2015/09/stable-channel-update_24.html).
We have inherited this change, and the blink-crosswalk repository is now
deprecated. People `gclient sync`'ing to this commit must pay attention to
gclient's output: the existing blink-crosswalk checkout in
`src/third_party/WebKit` will be moved automatically to a separate
location, and needs to be manually removed.
It is also likely that the `UPSTREAM.blink` file will contain the wrong
value the first time gclient sync is called, so people relying on it
should call gclient sync twice. Release …
> Roll Chromium to 45.0.2454.101, the last M45 stable release.

- DEPS.xwalk
Follow-up to 9d93b7d ("Roll Chromium to 45.0.2454.101, the last M45
stable release").
The original v8-crosswalk pushed with 45.0.2454.101 was faulty and
missing several commits (of our own, not upstream ones )which were
present when we were in .93.
v8-crosswalk's master branch has been re-pushed, and we need to use the
new hash.
Related to: XWALK-5762
> DEPS.xwalk: Re-roll v8-crosswalk.

- DEPS.xwalk
- runtime/browser/blink_upstream_version.h.in
- xwalk.gyp
The most notable change in this roll is that this upstream release was
made after Blink was merged into the Chromium git repository. It also
contains some security fixes, as described in [the release announcement](http://googlechromereleases.blogspot.com/2015/09/stable-channel-update_24.html).
We have inherited this change, and the blink-crosswalk repository is now
deprecated. People `gclient sync`'ing to this commit must pay attention to
gclient's output: the existing blink-crosswalk checkout in
`src/third_party/WebKit` will be moved automatically to a separate
location, and needs to be manually removed.
It is also likely that the `UPSTREAM.blink` file will contain the wrong
value the first time gclient sync is called, so people relying on it
should call gclient sync twice. Release …
> crosswalk-16: Roll Chromium to 45.0.2454.101, the last M45 stable release.

- DEPS.xwalk
* 45111a7 [Backport] Use the latest hash with a commit position as webkit version
This backport ended up being left out of 27f3d70 ("Roll Chromium to
45.0.2454.101, the last M45 stable release"), and is required for
`UPSTREAM.blink` to have a correct value in a build (the version of
lastchange.py in M45 would just choose the tip of the tree of
chromium-crosswalk, which is usually a commit of our own).
BUG=XWALK-5762
> crosswalk-16: DEPS.xwalk: Roll chromium-crosswalk (6cba28a -> 45111a7)

- extensions/browser/xwalk_extension_service.cc
The registration of xwalk extension includes file system operations,
while being executed during loading URL which is under UI thread.
In debug mode, this will violate the thread retriction and cause the
app crash. So move this procedure to the thread that dedicates to
file system operation.
BUG=XWALK-5754
> [Android] Move extension registration to file system thread

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
- runtime/browser/android/renderer_host/xwalk_render_view_host_ext.cc
- runtime/browser/android/renderer_host/xwalk_render_view_host_ext.h
- runtime/browser/android/xwalk_settings.cc
- runtime/common/android/xwalk_render_view_messages.h
- runtime/renderer/android/xwalk_render_view_ext.cc
- runtime/renderer/android/xwalk_render_view_ext.h
- test/android/core/javatests/src/org/xwalk/core/xwview/test/DefaultFixedFontSizeTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/DefaultFontSizeTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/TextZoomTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
This patch is to implement API for setTextZoom() and getTextZoom().
Adjust test case for reuse.
Add test case for setTextZoom() and getTextZoom().
BUG=XWALK-4994
> [Android] Implement the text zoom API.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Delegate scrollTo and scrollBy methods to ContentView as the
actual scroll is done in native
BUG=XWALK-3112
> [Android] Enable scrollTo/By in XWalkView

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
A View is usually in edit mode when displayed within a
developer tool, so isInEditMode() should be used inside
the corresponding XWalkView constructor.
BUG=XWALK-3568
> [Android] XWalkView should support edit mode in developer tool

- tools/reflection_generator/java_method.py
- tools/reflection_generator/wrapper_generator.py
The annotation field is used to generate methods without calling back to internal via reflection, so code like below is unused.
private ReflectMethod setUserXXX = new ReflectMethod(null, "setUserXXX");
BUG=XWALK-5792
> [Android] Remove unused code generated by disableReflectMethod

- runtime/browser/runtime_javascript_dialog_manager.cc
- xwalk.gyp
Basically adapt to https://codereview.chromium.org/1171333003, which
turned net::FormatUrl() into url_formatter:FormatUrl(). Fixes this build
error at least on Windows:
```
c:\b\b\slave\crosswalk_windows\build\src\xwalk\runtime\browser\runtime_javascript_dialog_manager.cc(56)
: error C2039: 'FormatUrl' : is not a member of 'net'
c:\b\b\slave\crosswalk_windows\build\src\xwalk\runtime\browser\runtime_javascript_dialog_manager.cc(56)
: error C3861: 'FormatUrl': identifier not found
```
> [Windows] Fix build after the move to Chromium M46.

- runtime/browser/xwalk_presentation_service_delegate_win.cc
- runtime/browser/xwalk_presentation_service_delegate_win.h
Adapt to https://codereview.chromium.org/1245443002 and make the code
more similar to what's in
chrome/browser/media/router/presentation_service_delegate_impl.{cc,h}.
Also adjust some method signatures.
https://codereview.chromium.org/1302973003 still needs to be analyzed.
```
This change gets rid of the following Windows build errors:
c:\b\b\slave\crosswalk_windows\build\src\xwalk\runtime\browser\xwalk_presentation_service_delegate_win.h(94)
: error C4430: missing type specifier - int assumed. Note: C++ does not
support default-int
c:\b\b\slave\crosswalk_windows\build\src\xwalk\runtime\browser\xwalk_presentation_service_delegate_win.h(94)
: error C2143: syntax error : missing ',' before '&'
c:\b\b\slave\crosswalk_windows\build\src\xwalk\runtime\browser\xwalk_presentation_service_delegate_ …
```
> [Windows] M46 Presentation API build fixes.

- build/android/maven_pom.gypi
- build/common.gypi
- runtime/android/maven/xwalk_core_library.pom.xml.in
- runtime/android/maven/xwalk_shared_library.pom.xml.in
- xwalk_core_library_android.gypi
Like #3397, this patch set contains two commits. The first one adds all
the required plumbing for generating the Maven POM files we have for
`xwalk_core_library` and `xwalk_shared_library` as part of our build.
The second commit leverages this infrastructure to add a dependency on
the support-v4 Android support library to the xwalk_core_library
artifact, as we have stopped bundling external JARs since #3350.
Related to: XWALK-5092
> crosswalk-16: Backport commits creating POM files in Crosswalk.

- runtime/browser/xwalk_presentation_service_delegate_win.cc
This patch does the following:
1) Immediately notifies screen listener about available displays
2) Changes the behaviour so that available displays are considered to be
the displays that may be used for starting *new* presentations (as per
http://www.w3.org/TR/presentation-api/#dfn-monitor-the-list-of-available-presentation-displays)
> [Windows] Fix detection of available presentation displays

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
In newer crosswalk, the parameter nums for loadXWalkLibrary() is
increased, this leads to older crosswalk can not invoke the right
function to load library in shared mode.
Keep the single parameter function to preserve backward compatibility.
Related to XWALK-5796
> [Android] Fix the mismatch issue.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkGetBitmapCallbackInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- tools/reflection_generator/java_method.py
- tools/reflection_generator/reflection_generator.py
- xwalk_core_library_android.gypi
Use this to capture the visible content of web page. Note: XWalkGetBitmapCallback
happens at the same thread as captureBitmapAsync, usually the UI thread.
Also enable the zero parameter constructor support in reflection layer.
BUG=XWALK-5110,XWALK-2233
(cherry picked from commit 55eceb4d089e516ea2b754a61c942cf393841374)
> [Android] Implement captureBitmapAsync to capture visible content

- tools/reflection_generator/java_method.py
In reflection layer, for those callbacks from library side, if there's
no corresponding method in app side, the library will throw an exception
then the app crashes. This happens particularly when app's version is
older than library's. By this patch, it will try to invoke default
implementation in library side instead of throwing exception.
BUG=XWALK-5796
(cherry picked from commit 557f14842ed792746ce1b32daed926519a25d771)
> [Android] Fix crash of incompatible app

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
This only produces a javadoc warning with OpenJDK6 that our bots use,
but is a fatal error at least with Fedora's OpenJDK8:
```
../out/Release/gen/xwalk_core_reflection_layer/wrapper/org/xwalk/core/XWalkView.java:671: error: @param name not found
* @param XWalkGetBitmapCallback callback when bitmap capture is done.
^
```
> [Android] Fix parameter name in captureBitmapAsync()'s documentation.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
setLayerType may be called before XWalk is ready and then UnsupportedOperationException is thrown. As we only support hardware acceleration in XWalkView, so setLayerType should be noop.
BUG=XWALK-5021, BUG=XWALK-5047
> [Android] Fix UnsupportedOperationException caused by setLayerType

- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryInterface.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
Crosswalk Runtime auto-update is enabled by default in download mode, it requires that the build version of xwalk_shared_library which developer used to bundle with the application has to match the build version of runtime APK, otherwise it will trigger an update to download a new crosswalk runtime from the server.
BUG=XWALK-5681
> [Android] Enable runtime auto-update in download mode

- app/android/runtime_client/src/org/xwalk/app/runtime/extension/BindingObjectAutoJS.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/BindingObjectStore.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/MessageHandler.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/ReflectionHelper.java
Some files in extension module used ReflectiveOperationException
which was added in Android API Level 19. So it will tigger verify
error on device with Android version below 4.4.
> [Android] Fix buildbot failure of external extension tests

- runtime/android/core/src/org/xwalk/core/XWalkLibraryDecompressor.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
We support both the original XWalkRuntimeLib.apk and the LZMA compressed XWalkRuntimeLibLzma.apk in download mode.
BUG=XWALK-5214
> [Android] Add LZMA compressed runtime support in download mode

- DEPS.xwalk
No new commits, but a few backports had to have their commit messages
edited. The original crosswalk-16/45.0.2454.101 branch in
chromium-crosswalk has been preserved as
crosswalk-16/45.0.2454.101-with-wrong-cr-commit-position-markers.
After the Blink repository was merged into the Chromium one upstream,
`src/build/util/lastchange.py` looks for the latest upstream Blink commit
that we use in the devtools URL by going through the commit messages and
finding the first with the "Cr-Commit-Position" marker.
This heuristic works most of the time (100% of the time for upstream),
but it breaks for us if we have backported commits with that marker in
the commit message, as the script will find one of those commits that do
not actually exist upstream. Consequently, remote debugging breaks
because …
> DEPS.xwalk: Re-roll chromium-crosswalk.

- tools/reflection_generator/bridge_generator.py
- tools/reflection_generator/java_method.py
Don't throw an exception when the object of new added class is created
in the library package but the app package lacks corresponding class
because of old version.
Related to XWALK-5796
> [Android] Fix error of missing class in the app package

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
For embedded arm application was installed on x86 device, the library
under folder "/data/app-lib" will be loaded successfully by houdini, for
stability reason, we don't use houdini now, so the variable
"sLibraryLoaded" was not set to "true", then try to load library from
specified url by System.load(). Load library twice will lead to crash
in houdini.
If library was loaded successfully by houdini then ignore the second
loading.
BUG=XWALK-5804
> [Android] Ignore the second loading when library was loaded by houdini.

- app/tools/android/make_apk.py
Flag "--disable-lzma" in make_apk.py cause crush.
> [Lite] App crush when use --disable-lzma flag.

- runtime/browser/devtools/xwalk_devtools_frontend.cc
This is due to https://codereview.chromium.org/1123783002 which
make javascript execution more strict and add various runtime checks.
There is a dedicated method that we should use for URLs such as the one
used by the inspector.
BUG=XWALK-5953
> [Linux][Windows] Fix crash when triggering the inspector.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
If the visibility of XWalkView is defined in layout, it will be passed
to XWalkViewInternal by AttributeSet, just invoke XWalkView.setvisibility()
will not work since it's child view(XWalkViewInternal)'s visibility was
set implicitly by AttributeSet.
Invoke the child view's setVisibility() explicitly when set the parent
view's visibility.
BUG=XWALK-5753
> [Android] Set the visibility for XWalkViewInternal.

- runtime/browser/xwalk_content_browser_client.cc
- runtime/browser/xwalk_render_message_filter.cc
- runtime/browser/xwalk_render_message_filter.h
- runtime/common/android/xwalk_render_view_messages.h
- runtime/renderer/xwalk_content_renderer_client.cc
Currently, intercepting http requests with shouldInterceptLoadRequest
is unreliable in combination with iframes, the root cause is that no
ipc message sent from renderer to browser process when subframe is
created, then the XWalkContentsIoThreadClient will not be created.
BUG=XWALK-5621
> [Android] IPC message should be setup when subframe is created

- build/system.gyp
It duplicates what is already present in src/build/linux/system.gyp, and
was only used by Tizen code.
> gyp: Remove "gio" target.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkResourceClientInternal.java
Commit 5942d33 ("[Android] Notify the host application that an HTTP
response has been received from the server") introduced invalid javadoc
markup. Build output with OpenJDK8:
```
../out/Release/gen/xwalk_core_reflection_layer/wrapper/org/xwalk/core/XWalkResourceClient.java:331: error: bad use of '>'
* The feature the same as Android WebView's onReceivedHttpError when HTTP errors have status codes >= 400
```
While here, improve the wording in the comments and, in particular, stop
saying "customers" when we just mean users. Not all users are customers.
> [Android] Fix javadoc build after 5942d33.

- build/system.gyp
Invoking pkg-config via `<(pkg-config)` instead of directly calling it
makes sure the call goes through Chromium's wrapper script that returns
appropriate values for sysroots.
This change has no effect at the moment by default, but helps when using
a sysroot such as the one provided by Chromium.
Related to: XWALK-5977
> gyp: Invoke pkg-config via Chromium's wrapper script.

- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
If the library was packaged into wrong architecture folder, e.g. library
for x86 was put in "armeabi-v7a", it will throw "UnsatisfiedLinkError"
exception when load library, this situation belongs to mismatch status
instead of incomplete library.
Check the error cause and give the right status.
BUG=XWALK-5803
> [Android] Refine the error message for mismatched architecture.

- runtime/android/core/src/org/xwalk/core/XWalkLibraryLoader.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
Use crosswalk's own download service instead of Android's DownloadManager
in download mode and this allow us to save the downloaded file to application's private storage.
BUG=XWALK-5951
> [Android]Use crosswalk's own download service in download mode

- runtime/browser/runtime_url_request_context_getter.cc
From https://codereview.chromium.org/1356933002, in
aw_browser_context.cc, we can see the proxy config service was not reset
to the casted service.
This is the part 1 to fix the core shell crashed.
BUG=XWALK-6046
> M48 gardening: Fix XWalk core shell crashed with proxy service.

- runtime/browser/runtime.cc
mediaDevices.enumerateDevices() API depends on this check.
BUG=XWALK-6060
> Allow media access permission check by default

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkDownloadListenerImpl.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/DownloadListenerTest.java
Use any cookies for the URL that is being downloaded from with the default
XWalkDownloadListenerImpl handler. This allows files that require Cookie-based
authentication to be downloaded.
BUG=XWALK-5981
> [Android] Add Cookie header to download requests.

- runtime/android/core_shell/src/org/xwalk/core/xwview/test/XWalkViewTestRunnerActivity.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/ClearHistoryTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnPageFinishedTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnUpdateTitleTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/ReloadTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/SaveRestoreStateTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
- xwalk.gyp
- xwalk_android_tests.gypi
Add XWalkSharedShell and XWalkSharedTest for shared mode test, the
package name, test cases, assets of these APKs are just like
XWalkCoreShell and XWalkCoreTest except that they must work with
XWalkRuntimeLib.
> [Android] Add test APKs for shared mode

- runtime/app/xwalk_main_delegate.cc
- runtime/app/xwalk_main_delegate.h
- runtime/common/logging_xwalk.cc
- runtime/common/logging_xwalk.h
- runtime/common/xwalk_paths.cc
- runtime/common/xwalk_paths.h
- xwalk.gyp
This PR will dump logging info into 'xwalk_debug.log' file.
This file will be saved in xwalk user data directory for a release build,
and in the binary folder(e.g. out\Debug) for a debug build.
> [Windows][Linux] Dump logging info to a log file

- DEPS.xwalk
* 7f651758 Merge pull request #307 from rakuco/backport-win-task-scheduler-launcher
* d5e7e6b [Backport] Conditionally set CREATE_BREAKAWAY_FROM_JOB when job objects are used.
BUG=XWALK-5142
> DEPS.xwalk: Roll chromium-crosswalk (326f968 -> 7f651758).

- xwalk_core_library_android.gypi
index.html ends up being generated even if javadoc has failed with
errors. Consequently, even if javadoc fails it will not be run again
because index.html will have been generated and have an up-to-date
mtime.
Instead, indicate that the entire documentation directory is the
action's output to force javadoc to run again until it exits
successfully.
> [Android] Use a better action output definition for the javadoc target.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
OpenJDK8 is stricter and produces an error instead of a warning (the
documentation would have looked wrong anyway):
```
../out/Release/gen/xwalk_core_reflection_layer/wrapper/org/xwalk/core/XWalkView.java:111:
error: malformed HTML
*               //             int statusCode, String reasonPhrase, Map<String, String> responseHeaders)
^
../out/Release/gen/xwalk_core_reflection_layer/wrapper/org/xwalk/core/XWalkView.java:111:
error: bad use of '>'
*               //             int statusCode, String reasonPhrase, Map<String, String> responseHeaders)
^
```
> [Android] Fix javadoc build after cc194840.

- application/common/manifest_handlers/widget_handler.cc
- application/common/manifest_handlers/widget_handler.h
They only manifest themselves in case `ParsePreferenceItem()` fails: in
this case, `DictionaryValue::Set()` is not called and `preference` leaks.
Fix it by turning most raw pointers in `WidgetHandler::Parse()` into
`scoped_ptr`s, even where it is not strictly necessary.
`WidgetInfo::Set()`'s prototype had to be adjusted a little to accept and
forward `scoped_ptr`s instead of `base::Value*`s, but it is a change for
the good that prevents similar mistakes in the future.
CID=323513
CID=323514
> Fix some memory leaks in the widget handling code.

- application/common/manifest_handlers/widget_handler.cc
- application/common/manifest_handlers/widget_handler.h
They only manifest themselves in case ParsePreferenceItem() fails: in
this case, DictionaryValue::Set() is not called and |preference| leaks.
Fix it by turning most raw pointers in WidgetHandler::Parse() into
scoped_ptr's, even where it is not strictly necessary.
WidgetInfo::Set()'s prototype had to be adjusted a little to accept and
forward scoped_ptr's instead of base::Value*'s, but it is a change for
the good that prevents similar mistakes in the future.
CID=323513
CID=323514
(cherry picked from commit 56450318523a98f63e9c0aeccce5110443c9b73d)
> crosswalk-17: Fix some memory leaks in the widget handling code.

- DEPS.xwalk
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentView.java
Move the methods for JellyBean to XWalkContentViewApi16 to imitate
JellyBeanContentView.
Move the mothods for AndroidM to XWalkContentViewApi23 to imitate
ContentView.ContentViewApi23.
All methods remaining in XWalkContentView is for XWalkView's usage.
XWalkContentView is a temporary solution. We are targeting to optimize
the hierarchy of XWalkView to make it more like WebView. This task can
be tracked via XWALK-6118.
BUG=XWALK-6014
> [Android] Update XWalkContentView to track ContentView

- runtime/browser/xwalk_browser_context.cc
Make sure to use the content settings only for desktop platforms
as Android does not need it.
> [Android] Fix crash.

- runtime/browser/xwalk_content_settings.cc
manifest.
As they are with the app:// protocol we need to tell content_settings
to allow it.
> [Linux][Windows] Save permissions for applications launched with the

- runtime/browser/runtime_geolocation_permission_context.cc
- runtime/browser/runtime_geolocation_permission_context.h
- runtime/browser/xwalk_browser_context.cc
- runtime/browser/xwalk_browser_context.h
- runtime/browser/xwalk_permission_manager.cc
- runtime/browser/xwalk_permission_manager.h
- runtime/browser/xwalk_runner.cc
Instead of originating URL. If an application is launched from the
manifest.json then the URL is something like app:// and it's not
really what we want to show to the user.
> [Windows][Linux] Favor application name when asking permission.

- runtime/browser/android/xwalk_content.cc
- runtime/renderer/android/xwalk_render_process_observer.cc
Prepare for the M48 update by switching away from
`JSONREader::DeprecatedRead()`, which is gone in that milestone.
In `XWalkContent::SetManifest()`, we just need to receive a `scoped_ptr`
instead, and it is also possible to simplify the code:
`manifest_dictionary` and `manifest_dictionary_ptr` are unnecessary and
only clutter the code.
> [Android] Switch to the non-deprecated version of JSONReader::Read().

- runtime/browser/android/renderer_host/xwalk_render_view_host_ext.cc
- runtime/browser/android/renderer_host/xwalk_render_view_host_ext.h
- runtime/common/android/xwalk_render_view_messages.h
- runtime/renderer/android/xwalk_render_view_ext.cc
- runtime/renderer/android/xwalk_render_view_ext.h
- test/android/core/javatests/src/org/xwalk/core/xwview/test/SetInitialScaleTest.java
Upstream has made all of the pageScaleFactor changes to browser process,
WebContentsObserver can observe the changed page scale factors.
XWalkRenderViewHostExt was inherited from WebContentsObserver, so the
changed factors were propagated to it.
The previous notification has side effects that the scale factor's changed
messages were delayed.
Modify the test case to adapt to this change.
BUG=XWALK-6046
> M48 gardening: adapt to https://codereview.chromium.org/1408393003

- gyp_xwalk
- runtime/browser/component_updater/widevine_cdm_component_installer.cc
- runtime/browser/component_updater/widevine_cdm_component_installer.h
- runtime/browser/component_updater/xwalk_component_updater_configurator.cc
- runtime/browser/component_updater/xwalk_component_updater_configurator.h
- runtime/browser/xwalk_browser_main_parts.cc
- runtime/browser/xwalk_render_message_filter.cc
- runtime/browser/xwalk_render_message_filter.h
- runtime/browser/xwalk_runner.cc
- runtime/browser/xwalk_runner.h
- runtime/common/widevine_cdm_constants.cc
- runtime/common/widevine_cdm_constants.h
- runtime/common/xwalk_common_messages.h
- runtime/common/xwalk_paths.cc
- runtime/common/xwalk_paths.h
- runtime/common/xwalk_switches.cc
- runtime/common/xwalk_switches.h
- runtime/renderer/xwalk_content_renderer_client.cc
- runtime/renderer/xwalk_key_systems.cc
- runtime/renderer/xwalk_key_systems.h
- xwalk.gyp
This PR will let xwalk register widevine CDM component and add
corresponding key system. Based on this, Xwalk will have the ability
to play content protected media with widevine CDM.
The steps to verify this feature:
1. python gyp_xwalk.py -Dmediacodecs_EULA=1
2. ninja -C ../out/Debug xwalk.exe
3. Run '../out/Debug/xwalk
http://shaka-player-demo.appspot.com/?dash;asset=assets/car_segmenttemplate.mpd'
After above three steps, you will see the video can be played well.
Notice that adding mediacodecs_EULA=1 flag is because the test video is mp4
format. If your test video is webm, this flag is not needed.(We have opened -Denable_widevine=1 in gyp_xwalk )
BUG=XWALK-6102
> [Windows] Enable widevine support

- gyp_xwalk
Sync with the upstream version of this file. This time there are not
many changes, other than the fact that the code upstream moved from
`gyp_chromium` to `gyp_chromium.py`.
List of relevant commits:
* d9aaae0 Add 'build' directory to import path of gyp_chromium.
* 1eeaa32 Move logic of gyp_chromium into gyp_chromium.py
> gyp_xwalk: Reduce delta with gyp_chromium.py.

- extensions/browser/xwalk_extension_data.h
- extensions/browser/xwalk_extension_function_handler.cc
- extensions/browser/xwalk_extension_function_handler.h
- extensions/browser/xwalk_extension_function_handler_unittest.cc
- extensions/browser/xwalk_extension_process_host.cc
- extensions/browser/xwalk_extension_service.cc
- extensions/common/xwalk_extension.h
- extensions/common/xwalk_extension_server.cc
- extensions/extension_process/xwalk_extension_process.cc
- extensions/renderer/xwalk_extension_client.cc
- extensions/renderer/xwalk_extension_module.cc
- extensions/renderer/xwalk_extension_renderer_controller.cc
- extensions/renderer/xwalk_js_module.cc
Scoped ptr is deprecated in M49 and it is easier to
fix them directly here. There will be most
probably another similar commit because it is easier to
find them from build failures.
> Change scoped_ptr.Pass() to std::move(scoped_ptr)

- DEPS.xwalk
* 28a1ef3 Merge pull request #127 from chuan9/XWALK-6190
* e417fa3 SIMD.js Resolve error on arm64 in building BUG=XWALK-6190
This finally allows M48 to build on ARM64 and unblocks our canary
builds.
BUG=XWALK-6190
> DEPS.xwalk: Roll v8-crosswalk (8b62e72 -> 28a1ef3)

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkHttpAuthHandlerInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkHttpAuthInternal.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnReceivedHttpAuthRequestTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/TestHelperBridge.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/TestHelperBridge.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/XWalkViewInternalTestBase.java
- tools/reflection_generator/reflection_generator.py
This patch is to fix the issue about onReceivedHttpAuthRequest() was not
called when this function was overridden in class of XWalkResourceClient.
Modify the attribute of XWalkHttpAuthHandlerInternal to generate right
parameter for XWalkResourceClientBridge.
Move test case from XWalkViewInternal to XWalkView.
BUG=XWALK-5117
> [Android] Fix onReceivedHttpAuthRequest() was not called issue.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkMediaPlayerResourceLoadingFilter.java
For the uri of "app://", it was converted to "file://", so the scheme
should be re-got to check.
BUG=XWALK-6173
> [Android] Fix audio can't play issue.

- build/common.gypi
- gyp_xwalk
Setting variables in gyp_xwalk was a historical mistake and likely came
from failures to understand GYP's bizantine scoping and evaluation
rules. Additionally, gyp_xwalk will not be used once we move to GN, so
this logic needs to be moved anyway.
The following variables were being set in gyp_xwalk to the values they
already have as default in `src/build/common.gypi` and have thus just been
removed from gyp_xwalk and not added to `src/xwalk/build/common.gypi`:
* `notifications`
* `use_aura`
* `use_openmax_dl_fft`
Quick explanation about GYP's weird scoping and variable evaluation
rules: one cannot set a variable in a scope and use it in a conditional
block in the same scope level, or set it in a conditional block and use
it in another check in the same block and scope level. In other …
> Move the variable setting logic from gyp_xwalk to build/common.gypi.

- application/common/application_data.cc
- application/common/id_util.cc
- application/common/manifest.cc
- application/common/package/xpk_package.cc
- application/common/package/xpk_package.h
- application/common/permission_policy_manager.h
- extensions/common/xwalk_extension_server_unittest.cc
- runtime/browser/devtools/remote_debugging_server.h
- runtime/browser/devtools/xwalk_devtools_frontend.h
- runtime/browser/devtools/xwalk_devtools_manager_delegate.cc
- runtime/browser/devtools/xwalk_devtools_manager_delegate.h
- runtime/browser/runtime.h
- runtime/browser/runtime_download_manager_delegate.cc
- runtime/browser/runtime_download_manager_delegate.h
- runtime/browser/runtime_network_delegate.h
- runtime/browser/runtime_select_file_policy.h
- runtime/browser/xwalk_browser_main_parts.h
- runtime/browser/xwalk_form_database_service.h
- sysapps/common/sysapps_manager.cc
- sysapps/common/sysapps_manager_linux.cc
- sysapps/device_capabilities/display_info_provider.cc
base/basictypes.h is deprecated and will be removed from Chromium in m49. Mostly it is not
needed, sometimes old types are replased with _t types. This do not
indlude all of them.
> Remove deprecated base/basictypes.h includes part 1

- application/browser/application_service.cc
- application/browser/application_system.cc
- application/common/application_data.cc
- application/common/application_file_util.cc
- application/common/manifest.cc
- application/common/package/package.cc
- application/common/package/wgt_package.cc
- application/common/package/xpk_package.cc
- application/extension/application_runtime_extension.cc
- application/extension/application_widget_extension.cc
- experimental/native_file_system/native_file_system_extension.cc
- runtime/browser/devtools/remote_debugging_server.cc
- runtime/browser/runtime_file_select_helper.cc
- sysapps/common/binding_object.h
- sysapps/common/binding_object_store.cc
- sysapps/common/event_target.cc
- sysapps/device_capabilities/av_codecs_provider_ffmpeg.cc
- sysapps/device_capabilities/cpu_info_provider.cc
- sysapps/device_capabilities/device_capabilities_extension.cc
- sysapps/device_capabilities/device_capabilities_object.cc
- sysapps/device_capabilities/display_info_provider.cc
- sysapps/device_capabilities/memory_info_provider.cc
- sysapps/device_capabilities/storage_info_provider_chromium.cc
- sysapps/raw_socket/raw_socket_extension.cc
- sysapps/raw_socket/raw_socket_object.cc
- sysapps/raw_socket/tcp_server_socket_object.cc
- sysapps/raw_socket/tcp_socket_object.cc
- sysapps/raw_socket/udp_socket_object.cc
Scoped ptr is deprecated in M49 and it is easier to
fix them directly here. There will be most
probably another similar commit because it is easier to
find them from build failures.
> Change scoped_ptr.Pass() to std::move(scoped_ptr) part 2

- DEPS.xwalk
* 0f31e18 Merge pull request #313 from astojilj/gamepad
* b34d261 XWALK-4992 [windows] App does not support gamepad
* dce3262 Merge pull request #314 from rakuco/webcl-define-only-for-webcl-files
* 64b4265 [Blink] WebCL: Only set ENABLE_WEBCL in the relevant files.
> DEPS.xwalk: Roll chromium-crosswalk (552b4b9 -> 0f31e18).

- extensions/common/xwalk_external_extension.cc
warning: field 'initialized_' will be initialized after
field 'library_path_' [-Wreorder]
> Fix build warning: initialize order

- build/common.gypi
With chromium-crosswalk commit 64b4265 ("[Blink] WebCL: Only set
ENABLE_WEBCL in the relevant files"), the `ENABLE_WEBCL` macro is defined
only for the relevant files in Blink.
This means we can now remove it from `target_defaults` and stop passing
it to all the 15000+ files part of Crosswalk's build since the vast
majority of them do not need to be aware of the macro at all.
> [Android] Stop setting ENABLE_WEBCL=1 in all files.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/ClearSslPreferenceTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/TestHelperBridge.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
This patch is to implement the API of clearSslPreferences().
Add test case for clearSslPreferences().
Most of the code was ported from upstream.
BUG=XWALK-5080
> [Android] Implement API: clearSslPreferences().

- build/android/generate_app_packaging_tool.py
It was thought to be used only by make_apk, so we stopped putting it in
the xwalk_app_template directory (and later publishing it in the zip
file) when make_apk was removed in commit acbf950 ("[Android] Remove
make_apk and associated tests from the tree") , but app-tools can use it
as a hint deduce Crosswalk's version number.
> [Android] Start shipping VERSION in the app-template zip file again.

- application/browser/application_security_policy.cc
This was only consumed by Tizen code that got removed in
3500f1d ("[Tizen] Remove support of Tizen"), and its presence is causing
build errors with the upcoming M49 because of -Wunused-function.
> Remove GetDefaultCSPInfo().

- application/renderer/application_native_module.cc
This function was added in 1959733 ("Add application extension and
getManifest(), getMainDocument() API support") but was never used
anywhere.
Get rid of it so that M49 builds do not fail due to `-Wunused-function`.
> Remove GetNativeModule().

- test/base/in_process_browser_test.cc
It is got unused bde9fbd
"The big in-browser tests classes clean-up"
> Remove unused GetCommandLineForRelaunch

- application/common/application_file_util_unittest.cc
- application/common/manifest_handlers/unittest_util.cc
- application/common/manifest_unittest.cc
- application/test/application_testapi.cc
- runtime/browser/linux/xwalk_notification_manager.cc
- runtime/browser/runtime_url_request_context_getter.cc
- runtime/browser/xwalk_browser_context.cc
- runtime/browser/xwalk_content_browser_client.cc
- runtime/browser/xwalk_platform_notification_service.cc
- runtime/browser/xwalk_pref_store.cc
- runtime/browser/xwalk_runner.cc
- runtime/renderer/xwalk_content_renderer_client.cc
- sysapps/common/binding_object_store_unittest.cc
- sysapps/common/common_api_browsertest.cc
- sysapps/common/event_target_unittest.cc
Scoped ptr is deprecated in M49 and it is easier to
fix them directly here. There will be most
probably another similar commit because it is easier to
find them from build failures.
> Change scoped_ptr.Pass() to std::move(scoped_ptr) part 3

- application/browser/application_service_provider_linux.cc
- extensions/common/android/xwalk_extension_android.cc
- extensions/test/in_process_threads_browsertest.cc
- extensions/test/internal_extension_browsertest.cc
- extensions/test/xwalk_extensions_browsertest.cc
- extensions/xesh/xesh_main.cc
- extensions/xesh/xesh_v8_runner.cc
- runtime/browser/android/net/android_protocol_handler.cc
- runtime/browser/android/net/android_stream_reader_url_request_job.cc
- runtime/browser/android/net/xwalk_url_request_job_factory.cc
- runtime/browser/android/xwalk_content.cc
- runtime/browser/android/xwalk_contents_client_bridge.cc
- runtime/browser/android/xwalk_dev_tools_server.cc
- runtime/browser/android/xwalk_request_interceptor.cc
- runtime/browser/android/xwalk_web_resource_response.cc
Scoped ptr is deprecated in M49 and it is easier to
fix them directly here. There will be most
probably another similar commit because it is easier to
find them from build failures.
> Change scoped_ptr.Pass() to std::move(scoped_ptr) part4

- runtime/browser/xwalk_browser_main_parts.cc
- xwalk.gyp
We started setting it in M40 with commit b37ea05 ("Roll 40.0.2214.28"),
likely to work around Chromium change 44b9ce2 ("Cleanup: Prevent usage
of various extension headers when extensions support is not compiled
in") that would otherwise cause the build to fail like this:
```
In file included from ../../extensions/browser/extension_system.h:13:0,
from ../../xwalk/runtime/browser/xwalk_browser_main_parts.cc:24:
../../extensions/common/extension.h:31:2: error: #error "Extensions must be enabled"
#error "Extensions must be enabled"
^
In file included from ../../xwalk/runtime/browser/xwalk_browser_main_parts.cc:24:0:
../../extensions/browser/extension_system.h:16:2: error: #error "Extensions must be enabled"
#error "Extensions must be enabled"
^
```
The extension_system.h include was added in …
> [Android] Stop setting |enable_extensions|.

- build/common.gypi
- xwalk.gyp
Continuing with the efforts to move all common variable settings to a
single place and also to ease the future migration to GN, start setting
`disable_nacl` and `verify_xwalk_apk` in `common.gypi` instead of
`xwalk.gyp`.
This change should not cause any changes to the build.
Related to BUG=XWALK-3674
> Move more variables to common.gypi.

- build/win/generate_crosswalk_zip.py
- xwalk.gyp
- xwalk_win_zip.gypi
The new `generate_crosswalk_win_zip` target, built as part of the
`xwalk_builder` target on Windows, invokes a script that creates a ZIP
file (called `crosswalk_win.zip`) with everything required to run
Crosswalk on Windows. In other words, it's a zip file with the same
contents we publish on download.01.org (without a version number or
signed files, though).
Doing so helps with generating Crosswalk canaries for Windows as part of
our release building process.
> [Win] Add a target to generate a Crosswalk ZIP file.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkPreferencesInternal.java
Starting in version 39 of Chrome for Android on Lollipop, it
can be able to use the theme-color meta tag to set the toolbar
color, and Crosswalk already support it now. However, it would
be nice if this feature can be configured.
BUG=XWALK-5024
> [Android] Add support to enable/disable theme color property

- runtime/browser/devtools/xwalk_devtools_frontend.cc
This will unbreak the inspector on desktop platforms. Note that
the message has been added back in September 2015
(https://codereview.chromium.org/1362943005) but only broke when we moved
to M48 (probably now required due to work on
https://code.google.com/p/chromium/issues/detail?id=529471).
BUG=XWALK-6307
> Make sure to handle all the required messages in our devtools frontend

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
The network change notifier should be registered with application context,
it depends on application status, but our notifier was registered with an
activity/service, it's wrong.
Upstream has fixed this issue by changing the network layer and
implementing the life cycle notifier in M48.
BUG=XWALK-5892, XWALK-6178
> [Android] Remove the network change notifier.

- runtime/browser/media/media_capture_devices_dispatcher.cc
- runtime/browser/media/media_capture_devices_dispatcher.h
- runtime/browser/runtime.cc
- runtime/browser/runtime_geolocation_permission_context.cc
- runtime/browser/ui/desktop/xwalk_permission_dialog_manager.cc
- runtime/browser/ui/desktop/xwalk_permission_dialog_manager.h
- runtime/browser/xwalk_browser_context.h
- runtime/resources/xwalk_resources.grd
Make sure to query the permission manager to ask permissions when
querying the APIs related to microphone and camera.
Following upstream any request originating from HTTP will be ignored.
Please note that CheckMediaAccessPermission was changed to return
false on Android (this was the default behavior before df6e38).
BUG=XWALK-6083
> Make sure to ask permissions when requesting camera or microphone

- runtime/browser/android/net/input_stream.h
- runtime/browser/android/xwalk_autofill_client_android.h
- runtime/browser/android/xwalk_contents_io_thread_client_impl.h
- runtime/browser/android/xwalk_cookie_access_policy.h
- runtime/browser/android/xwalk_dev_tools_server.cc
- runtime/browser/android/xwalk_dev_tools_server.h
- runtime/browser/android/xwalk_download_resource_throttle.h
- runtime/browser/ui/webui/file_picker/file_picker_ui.h
- runtime/browser/ui/webui/file_picker/file_picker_web_dialog.h
- runtime/browser/ui/webui/xwalk_web_ui_controller_factory.h
- runtime/renderer/android/xwalk_render_view_ext.h
- sysapps/common/sysapps_manager_android.cc
base/basictypes.h is removed from Chromium in m49. Mostly it is not
needed, sometimes old types are replased with _t types. There
is still 4 mac and win uses of these.
> [Android] Remove deprecated base/basictypes.h includes

- xwalk_core_library_android.gypi
The `xwalk_shared_library_aar` target had a missing dependency on
`xwalk_shared_library`. If one tried to build the former, it would fail
because the latter had not been build:
OSError: [Errno 2] No such file or directory: '../out/Release/xwalk_shared_library/AndroidManifest.xml'
Add the missing dependency between the two targets, and do the same for
`xwalk_core_library_aar`: while it is not broken because its dependency
on `xwalk_core_empty_embedder_apk` brings a dependency on
`xwalk_core_library`, it is better to be safe and explicitly depend on a
target whose output we use.
> [Android] Explicitly depend on target <foo> in the <foo>_aar targets.

- runtime/browser/xwalk_content_browser_client.cc
- runtime/browser/xwalk_content_browser_client.h
When launched through the manifest Crosswalk apps
are using the app:// protocol so we need to add it
as part of the allowed schemes for the API.
> Fix FileApiPersistent API SecurityError.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- runtime/browser/android/xwalk_contents_client_bridge.cc
- runtime/browser/android/xwalk_contents_client_bridge.h
- test/android/core/javatests/src/org/xwalk/core/xwview/test/ClearClientCertPreferenceTest.java
Adding a clearClientCertPreferences method similar to the one the
Android system webview has.  When called it will clear any client
certificate preferences stored in response to proceeding/cancelling
client cert requests.
BUG=XWALK-6297
> [Android] Implement embedding API of clearClientCertPreferences()

- extensions/xesh/xesh_main.cc
- extensions/xesh/xesh_v8_runner.cc
- extensions/xesh/xesh_v8_runner.h
xesh is not been built as part of the "xwalk" or "xwalk_builder"
targets, which means it has been bitrotting for a few years.
This patch adapts the code to several changes that have happened to the
Chromium code base in the meantime (`CommandLine` needs the `base`
namespace, removal of `base::MessageLoopProxy` etc).
It is not enough to get it to run without crashing though, so someone
else needs to fix it or remove it from the tree altogether.
Related to BUG=XWALK-6219
> xesh: Get it to a compilable state.

- xwalk.gyp
This was added with the initial Crosswalk commit, and no longer seems to
be necessary.
> Drop dependency on base's allocator.gyp:allocator.

- runtime/browser/xwalk_notification_manager_linux.cc
- runtime/browser/xwalk_notification_manager_linux.h
- runtime/browser/xwalk_platform_notification_service.cc
- xwalk.gyp
Doing that allows it to be automatically excluded from builds based on
the rules in `src/build/filename_rules.gypi`, and we do not have to add
those files to the build system in a special condition check.
> Add a "_linux" suffix to xwalk_notification_manager.{cc,h}.

- build/android/generate_version_code.py
- xwalk.gyp
Instead of having part of the logic in xwalk.gyp and part in the Python
script, do everything in the latter, while also taking advantage of the
fact that we've already know Crosswalk's version number by the time we
invoke the script, so we do not need to read it again.
Also update the comment describing how we derive the version code
number, as it was a bit outdated (we do not reset the build number when
we bump either the major or the minor number).
> [Android] Rewrite generate_version_code.py.

- xwalk.gyp
It was added with commit 6863ff1b ("Bump crosswalk to Chromium
34.0.1809.2"), but it is not used anywhere (the `xwalk` target it
depended on does not even work on Android).
> [Android] Remove "All" target.

- runtime/renderer/xwalk_content_renderer_client.cc
This patch brings 'user agent' values which override page
min and max zoom from meta viewport tag.
BUG=XWALK-6269
> [Windows][Linux] Limit min/max zoom from viewport meta

- extensions/renderer/xwalk_v8tools_module.cc
- extensions/test/data/test_v8tools.html
V8 is deprecating its previous `v8::PersistentBase::SetWeak()` calls
that turned a persistent object into a weak reference. The new SetWeak()
API turns the handle into a phantom reference, a concept borrowed from
Java that means a callback set when calling SetWeak() will be run
_after_ the object being referenced has already been garbage-collected.
This is happening most likely due to performance reasons, as memory can
be reclaimed in one GC cycle instead of two. Relevant CLs and bugs:
- https://bugs.chromium.org/p/v8/issues/detail?id=3246
- https://codereview.chromium.org/687003005
- https://codereview.chromium.org/753553002
- https://codereview.chromium.org/989153003
For us, this means the lifecycleTracker code needs to be rewritten, as
we were relying on the referenced lifecycleTracker …
> v8tools: Port the lifecycleTracker code to non-deprecated API.

- application/browser/application_protocols.cc
Had been broken occasionally during rebase
(at addc73750a033fb191338b31b6ae6593613966da).
BUG=XWALK-6079
> [Windows][Linux]Fix CSP HTTP request syntax

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkPreferencesInternal.java
Starting version 39 of Chrome for Android on Lollipop, the app that embeds WebView changes toolbar color if the opened web page uses theme-color. Crosswalk WebView also support it now, but in some cases, the feature is not desired, the problem is that the app developer has no control on the pages that are opened, so it would be nice if this feature can be configured in Crosswalk.
BUG=XWALK-6445
(cherry picked from commit deed2fec61e8c1eded7129b295df664626511b45)
> [Android] Add support to enable/disable theme-color property

- application/browser/application_service.cc
- application/common/application_data.cc
- application/common/application_data.h
- application/common/application_file_util_unittest.cc
- application/common/application_manifest_constants.cc
- application/common/application_manifest_constants.h
- application/common/manifest_handler_unittest.cc
- application/common/manifest_handlers/permissions_handler_unittest.cc
- application/common/manifest_handlers/unittest_util.cc
Before, the application URL origin (which is used in granting API
permissions) was generated from the installation path. Instead the
URL origin must be unique and it must remain the same for the app
wherever it is installed.
Now the application origin is generated from the upgrade id
GUID that remains the same through all the application versions.
BUG=XWALK-6442
> [Windows] Fix application origin

- extensions/extensions.gyp
- extensions/renderer/xwalk_extension_module.cc
- extensions/renderer/xwalk_js_module.cc
- extensions/renderer/xwalk_module_system.cc
- extensions/renderer/xwalk_module_system.h
- extensions/renderer/xwalk_v8tools_module.cc
In preparation for Chromium M49 (which will enable stricter compilation
flags for more code by default), port the extensions subsystem away from
deprecated V8 API calls. They will be removed soon, and it is better to
avoid being surprised late in the game.
While here, enable the `chromium_code` variable in `extensions.gyp` so
that we build all targets there (currently, only `xwalk_extensions`)
with more compiler warnings and errors so that we catch uses of
deprecated APIs earlier in the future.
Related BUG=XWALK-6276
BUG=XWALK-6372
> extensions: Port away from deprecated V8 APIs.

- application/common/application_data.cc
Commit ec0720da ("[Windows] Fix application origin") introduced an
ordering issue when initializing `ApplicationData`'s members which
causes build failures with stricted compiler flags (as it happens by
default in M49):
```
../../xwalk/application/common/application_data.cc:109:7: error: field 'application_id_' will be initialized after field 'path_' [-Werror,-Wreorder]
application_id_(id),
```
> Fix a -Wreorder error after ec0720da.

- runtime/browser/xwalk_runtime_browsertest.cc
Upstream is moving towards removing `test_server()` and moving everything
to `embedded_test_server()`. See, for example, https://codereview.chromium.org/1486633002.
Do the same for `xwalk_browsertest`. There should be no visible effects
after this change.
BUG=XWALK-6288
> xwalk_browsertest: Port to embedded_test_server.

- application/common/application_manifest_constants.cc
- application/common/application_manifest_constants.h
- runtime/browser/xwalk_runner.cc
- runtime/browser/xwalk_runner.h
- runtime/browser/xwalk_runner_win.cc
- runtime/browser/xwalk_runner_win.h
- xwalk.gyp
them as environment variables.
When packing a crosswalk app with app-tools and a developer provided
their keys to access the Google APIs they are going to be added
in the registry. Make sure to fetch them in Crosswalk and set them
as env variables so they can be used later on during requests (such
as geolocation.)
> [Windows] Read the Google API keys from the registry to set

- runtime/browser/runtime_platform_util_aura.cc
This file, contrary to the other `runtime_platform_util_*.cc` ones, was
including `chrome/browser/platform_util.h` instead of our own
`runtime/browser/runtime_platform_util.h`, leading to build failures in
M49:
```
In file included from ../../xwalk/runtime/browser/runtime_platform_util_aura.cc:5:
../../chrome/browser/platform_util.h:13:10: fatal error: 'chrome/common/features.h' file not found
```
BUG=XWALK-6287
> Include the right header in runtime_platform_util_aura.cc.

- extensions/extension_process/xwalk_extension_process.cc
- warning C4800: 'xwalk::extensions::RuntimePermission' : forcing value to bool 'true' or
'false' (performance warning)
- warning C4701: potentially uninitialized local variable 'result'
used
> [Windows] Build fix.

- extensions/renderer/xwalk_v8tools_module.cc
- extensions/test/data/test_v8tools.html
- sysapps/common/common_api_browsertest.html
- sysapps/raw_socket/raw_socket_api_browsertest.html
`SysAppsRawSocketTest.SysAppsRawSocket` was crashing on M49 after commit
92bdf3c ("v8tools: Port the lifecycleTracker code to non-deprecated API") when
built in debug mode.
It turns out our weak callbacks (before and after turning them into phantom
callbacks in the commit mentioned above) are run between Blink's garbage
collection prologue and epilogue. The prologue forbids script execution, and
the epilogue reenables it. In debug mode, when all asserts are on, the checks
for whether JS code is being run fail and Crosswalk crashes.
Commit d43f001 ("Fix XWalkExtensionsV8ToolsTest.V8ToolsWorks asserting in
debug") was an early indication of this issue, and was working around the issue
by somewhat blindly disabling some of those checks. That was not enough, and
doing something as simple as …
> v8tools: Run the lifecycleTracker destructor asynchronously.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkExternalExtensionManagerInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- tools/reflection_generator/java_class.py
- tools/reflection_generator/reflection_generator.py
New XWALK APIs are added in Crosswalk-18, accordingly the Cordova
Plugin uses those APIs. It complains compile error because in Lite-17
those new added APIs are not exist.
So we add fake APIs into Lite-17 to make it compatible with Cordova Plugin.
This modification is not needed in Lite-19.
BUG=XWALK-6488
> [Lite]Add fake APIs to make Lite-17 compatible with Cordova Plugin 1.7.0

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
[Android] re-implement captureBitmapAsync based on WebContents
Now that upstream has moved ContentReadbackHandler related feature into WebContents.
We re-implement this api based on WebContents.
BUG= XWALK-6370
> [Android] re-implement captureBitmapAsync based on WebContents

- DEPS.xwalk
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
If set the WindowBackground of Activity to RED, and webpage page's backgroudn to RED,
when application starts or resumes after click back key, it will showup a white screen
shortly. We can change the first screen to a fix color by setting the root layer color
of ContentViewCore. This can help to avoid white screen.
BUG=XWALK-4809, XWALK-4995
> [Android] Change color of root layer to avoid white screen on startup

- runtime/app/xwalk_main.cc
Not that important as xwalk build target is not used for Android
but I thought it's still good to fix it for Android. Without this patch
you will see following build error,
../../xwalk/runtime/app/xwalk_main.cc: In function 'int main(int, const char**)':
../../xwalk/runtime/app/xwalk_main.cc:82:10: error: 'struct content::ContentMainParams' has no member named 'argc'
params.argc = argc;
^
../../xwalk/runtime/app/xwalk_main.cc:83:10: error: 'struct content::ContentMainParams' has no member named 'argv'
params.argv = argv;
^
../../xwalk/runtime/app/xwalk_main.cc:85:10: error: 'ContentMain' is not a member of 'content'
return content::ContentMain(params);
^
ninja: build stopped: subcommand failed.
BUG=XWALK-6531
> [Android] Fix the xwalk build target on android

- runtime/android/core/src/org/xwalk/core/extension/MessageInfo.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkPresentationHost.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkResourceClientInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/extension/api/DisplayManagerJBMR1.java
- runtime/android/core_internal/src/org/xwalk/core/internal/extension/api/DisplayManagerNull.java
- runtime/android/core_internal/src/org/xwalk/core/internal/extension/api/XWalkDisplayManager.java
- runtime/android/core_internal/src/org/xwalk/core/internal/extension/api/device_capabilities/DeviceCapabilitiesDisplay.java
- runtime/android/core_internal/src/org/xwalk/core/internal/extension/api/device_capabilities/MediaCodec.java
- runtime/android/core_internal/src/org/xwalk/core/internal/extension/api/presentation/PresentationViewJBMR1.java
Some new APIs were used without runtime checks, app will be crashed when
it runs on lower API level devices.
Add the checks for new APIs.
BUG=XWALK-6296, XWALK-6495
> [Android] Fix the NewApi warnings.

- application/renderer/application_native_module.cc
Prepare for M49 by switching to non-deprecated versions of some V8 API
calls:
```
../../xwalk/application/renderer/application_native_module.cc: In static member function 'static void xwalk::application::ApplicationNativeModule::GetViewByIDCallback(const v8::FunctionCallbackInfo<v8::Value>&)':
../../xwalk/application/renderer/application_native_module.cc:31:42: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at ../../v8/include/v8.h:7942): Use maybe version [-Wdeprecated-declarations]
int main_routing_id = info[0]->ToInt32()->Value();
^
../../xwalk/application/renderer/application_native_module.cc: In constructor 'xwalk::application::ApplicationNativeModule::ApplicationNativeModule()':
../../xwalk/application/renderer/application_native_module.cc:66:76: …
```
> application_native_module: Stop using deprecated V8 API.

- runtime/android/core/src/org/xwalk/core/extension/XWalkExternalExtensionManagerImpl.java
- tools/reflection_generator/wrapper_generator.py
The initialization of external extension manager is embedded into the
constructor of XWalkView, but corresponding class doesn't exist in
Crosswalk versions prior to 18. So the Crosswalk apps with shared mode
will crash when running on old versions of runtime library.
BUG=XWALK-6385
> [Android] Fixed crash of extension manager in shared mode

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkHttpAuthHandlerInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkHttpAuthInternal.java
The Android HttpAuthHandler exposes if this is the first auth attempt
through the method useHttpAuthUsernamePassword. The Crosswalk
XWalkHttpAuthHandler also has this information but it is
currently not made available to the public API.
BUG=XWALK-6389
> [Android] Add isFirstAttempt as part of public XWalkHttpAuthHandler API

- build/common.gypi
This is a no-op in M48, but starting with M49 `use_sysroot` is enabled
by default on Linux. This means the build will use a Debian Wheezy
chroot to build and use as few system dependencies as possible.
It is a nice idea, but we cannot use it with Crosswalk at the moment
because we have an additional dependency on libnotify that is not part
of the Wheezy chroot shipped by Chromium.
BUG=XWALK-5806
> build: Disable use_sysroot by default.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
- runtime/browser/android/xwalk_settings.cc
- runtime/renderer/xwalk_content_renderer_client.cc
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnPageFinishedTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/SetInitialScaleTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
For OnReceivedErrorTest#testCacheMiss, the related resource id was
removed in
https://github.com/crosswalk-project/crosswalk/commit/29838edb08b71e49c43eff580ac02f4709d1cfaa, this leads to the description is null.
For SetInitialScaleTest#testSetInitialScale1, the clobber initial scale
should works in quirks mode, please refer to https://codereview.chromium.org/67193002,
but crosswalk has no API to set quirks mode. Meanwhile the previous
CriteriaHelper.poll* did not check the result inside function, it was fixed in
https://codereview.chromium.org/1491063002, then initial scale issue was
exposed.
For OnPageFinishedTest#testOnPageFinishedNotCalledForJavaScriptUrl, it
was caused by https://codereview.chromium.org/1304373007, the return
value of GetLoadingUrl() was reset to data url instead of …
> [Android] Fix the failed android tests on M49.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkInternalResources.java
The classloader used to load internal classes should be the same
as XWalkInternalResources'.
BUG=XWALK-6566
BUG=XWALK-6599
> [Android] Fix the resoures IDs reset in download mode

- runtime/browser/ui/desktop/exclusive_access_bubble_views.cc
Follow-up to 44b2e8a ("Add a popup window to exit full screen mode"). In
the upcoming Chromium M49 it is not possible to use
`scoped_ptr::Pass()`. Prepare beforehand by using `std::move()` instead.
> Use std::move instead of scoped_ptr::Pass().

- build/common.gypi
This is in preparation for M49 and http://crrev.com/1570193002, which
stopped passing -Wno-reserved-user-defined-literal except for ChromeOS
builds.
We need that at the moment for Linux builds that do not use
`use_sysroot==1` because at least our bots are using Ubuntu Precise,
whose dbus 1.14.18 breaks the build like this:
```
/usr/include/dbus-1.0/dbus/dbus-protocol.h:459:77: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
#define DBUS_INTROSPECT_1_0_XML_DOCTYPE_DECL_NODE "<!DOCTYPE node PUBLIC \""DBUS_INTROSPECT_1_0_XML_PUBLIC_IDENTIFIER"\"\n\""DBUS_INTROSPECT_1_0_XML_SYSTEM_IDENTIFIER"\">\n"
^
/usr/include/dbus-1.0/dbus/dbus-protocol.h:459:126: error: invalid suffix on literal; C++11 requires a space between …
```
> build: Explicitly pass -Wno-reserved-user-defined-literal.

- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
The app shows the message of "mismatch of CPU architecture" once
UnsatisfiedLinkError is encountered when loading native library.
Donot distinguish the error message anymore. The message of "incomplete
library" is not used temporarily.
BUG=XWALK-6622, XWALK-6619
> [Android] Fixed wrong message when run x86 apps on ARM devices

- runtime/common/xwalk_common_message_generator.h
`xwalk_common_message_generator.h` does not have include guards, and
according to a comment there this seems to be on purpose.
Add a `NOLINT` entry to it to avoid cpplint a build/header_guard error.
RELATED BUG=XWALK-1853
> Add a NOLINT to avoid a build/header_guard cpplint warning.

- DEPS.xwalk
* c9cd89c Merge pull request #337 from rakuco/backport-checkperms-fix
* 123d118 [Backport] PRESUBMIT: Determine checkperms.py's path using input_api.
* 8222364 Merge pull request #335 from darktears/build-fix
* 58751e9 [Windows] Fix build.
* 96132b6 Merge pull request #332 from pozdnyakov/web_audio
* 4a0b6c0 [Windows] Implementation of 'AudioDestinationNode.devicePosition' attribute
* 4ff4032 Merge pull request #334 from rakuco/import-opencl-headers
* 8cb422b Import Khronos' OpenCL headers into chromium-crosswalk.
* 1db0eb3 .gitignore: Stop ignoring third_party/khronos/CL.
This also includes the removal of the OpenCL headers entry in
`DEPS.xwalk`, as it is now part of chromium-crosswalk itself (see
crosswalk-project/chromium-crosswalk#334 for details).
> DEPS.xwalk: Roll chromium-crosswalk (b15365d -> c9cd89c).

- PRESUBMIT.py
- runtime/resources/xwalk_resources.grd
Enable the check after fixing the existing violations:
** Presubmit Warnings **
Found a tab character in:
***************
runtime/resources/xwalk_resources.grd:97
runtime/resources/xwalk_resources.grd:98
***************
> PRESUBMIT: Enable check for tabs in .grd files.

- application/test/data/api/main.js
`main.js` stopped being used with commit 7514f134 ('Drop "Main document"
support'), so we can remove it and get rid of an unlicensed file.
> application: Remove unused JavaScript file.

- runtime/browser/xwalk_browser_main_parts.cc
- runtime/browser/xwalk_browser_main_parts_android.cc
- runtime/renderer/xwalk_content_renderer_client.cc
Viewport is not supported on desktop platforms in Chromium, there
are multiple issues with it which won't be solved (see crbug.com/591326)
BUG=XWALK-6514
> Disable viewport on desktop platforms

- experimental/native_file_system/native_file_system.idl
- experimental/native_file_system/native_file_system_api.js
- experimental/native_file_system/native_file_system_api_browsertest.html
- experimental/native_file_system/native_file_system_extension.cc
- experimental/native_file_system/native_file_system_extension.h
- experimental/native_file_system/virtual_root_provider.cc
- xwalk.gyp
Oh boy, where do I even start? This extension has been pretty much
unmaintained since 2014, does not really implement any actual spec and
was using the `Promises` polyfill from the sysapps code. It was the
latter that prompted me to take a look at it, and this is what I came up
with.
All the commits but the last one are small groundwork, and the last
change is where the big cleanup is actually performed. Quoting this last
commit's commit message:
Make the code more readable and trim all the unnecessary fat from both the
C++ and the JS sides to the extent that keeping backwards compatibility
allows us (i.e. synchronous functions remain synchronous, async functions
that use callbacks instead of Promises continue doing so etc).
- Remove all the pseudo-Promises silliness: manually keeping a …
> native filesystem extension: Clean up the code.

- build/android/generate_app_packaging_tool.py
- xwalk_android_app.gypi
Simplify the script a lot by not trying to deduce if an entry is a file
or a directory. Instead, keep two separate lists with directories and
files we want to copy to the `xwalk_app_template` directory.
Also stop hardcoding some paths and let gyp pass all the directory
information to the script.
> [Android] Rewrite generate_app_packaging_tool.py.

- runtime/browser/runtime_notification_permission_context.cc
- runtime/browser/runtime_notification_permission_context.h
- runtime/browser/xwalk_content_settings.cc
- runtime/browser/xwalk_notification_manager_win.cc
- runtime/browser/xwalk_notification_manager_win.h
- runtime/browser/xwalk_notification_win.cc
- runtime/browser/xwalk_notification_win.h
- runtime/browser/xwalk_permission_manager.cc
- runtime/browser/xwalk_permission_manager.h
- runtime/browser/xwalk_platform_notification_service.cc
- runtime/browser/xwalk_platform_notification_service.h
- runtime/resources/xwalk_resources.grd
- xwalk.gyp
- Ask permissions to the user (previously it was not granted). Android
will not grant permissions because it works differently.
- Hook up the notification support in content to the Windows C++ API. It
comes with some limitation such as not being able to have URL based
icons part of the notification. Workaround is to copy it in a temporary
file before firing the notification.
- Windows 7 is not supported as there is no notification center.
Known limitations which I plan to fix in a following patch : persistent
support (aka it says in the notification center), activation even when
Crosswalk is closed.
BUG=XWALK-4990
> [Windows] Implement support for native notifications.

- runtime/browser/runtime_download_manager_delegate.cc
The former is less costly than than the latter, which requires
thread-safe access and a singleton. We just need an empty `std::string()`
after all.
> Use a standard std::string() constructor instead of base::EmptyString.

- runtime/browser/runtime_download_manager_delegate.cc
The former is less costly than than the latter, which requires
thread-safe access and a singleton. We just need an empty std::string()
after all.
(cherry picked from commit c1e8610f455a18574697cf73e0f902b0b8e776e3)
> crosswalk-18: Use a standard std::string() constructor instead of base::EmptyString.

- build/android/generate_app_packaging_tool.py
Fix a regression introduced by 7209eee ("[Android] Rewrite
generate_app_packaging_tool.py") which ended up putting
`lib/xwalk_app_runtime_java.jar` into the top-level app_template
directory. It must be under `template/`.
BUG=XWALK-6744
> [Android] Fix xwalk_app_runtime_java.jar's location in the app template.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkCookieManagerInternal.java
Since M46, there is a change in upstream to match the comments
in CookieManager "Note that calls to this method will have no
effect if made after a WebView or CookieManager instance has
been created". For XWalkCookieManager, the function can't be
defined static for reflection limitation, so the comment is
not correct.
BUG=XWALK-6274
> [Android] Update warning in setAcceptFileSchemeCookies's API documentation

- runtime/browser/xwalk_presentation_service_delegate_android.cc
`xwalk_presentation_service_delegate_android.cc`, as the name says, is
only built on Android so there is no reason to have checks for the
`OS_ANDROID` macro there.
While here, fix a typo in a function name ("Andorid" -> "Android") and
adjust the coding style in surrounding regions.
> [Android] Remove OS_ANDROID checks from an Android-specific file.

- runtime/android/core_internal/res/values/colors.xml
- runtime/android/core_internal/src/org/xwalk/core/internal/SwipeRefreshHandler.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkWebContentsDelegate.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkWebContentsDelegateAdapter.java
- runtime/android/core_internal/strings/android_xwalk_strings.grd
- runtime/browser/android/xwalk_web_contents_delegate.cc
- runtime/browser/android/xwalk_web_contents_delegate.h
- xwalk_android.gypi
[Android] Enable pull-to-refresh
With this enabled, when user pull from the page top, page will be reloaded.
This can be disabled by flag --disable-pull-to-refresh-effect.
Pull-to-refresh differs from edge effect. For the edge effect, it is from
android and it "performs the graphical effect used at the edges of scrollable
widgets when the user scrolls beyond the content bounds in 2D space.".
Detailed documents is here:
http://developer.android.com/reference/android/widget/EdgeEffect.html.
As to the pull-to-refresh, it is from google chrome. It means reload the page
when user vertically overscrolling content at page top.
BUG=XWALK-6277
> [Android] Enable pull-to-refresh

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkDownloadListenerImpl.java
When open a link to download file in XWalkView, it's better the downloading
is visible and shows in the notifications while in progress and after
completion, so the downloaded file can be opened.
BUG=XWALK-6678
> [Android] Add notification while downloading is in progress and finished

- DEPS.xwalk
- build/common.gypi
Disable WebVR support on Android by default, since it depends on
`third_party/cardboard-java` which in turn needs
`third_party/android_protobuf`.
The dependency on `android_protobuf` means `xwalk_core_library_java.jar`
bundle Protobuf and cause build conflicts for users depending on Protobuf
themselves (or using other libraries that pull it).
The WebVR code is still in a very experimental state, even more so in M48,
so disabling it altogether is the best solution to get Crosswalk 18 out of
the door. We will try to think of a better solution for Crosswalk 19 and
above.
RELATED BUG=XWALK-6597
BUG=XWALK-6746
> crosswalk-18: Build with enable_webvr=0 by default.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/browser/android/xwalk_contents_client_bridge.cc
- runtime/browser/android/xwalk_contents_client_bridge.h
- runtime/browser/android/xwalk_contents_client_bridge_base.h
- runtime/browser/xwalk_render_message_filter.cc
- runtime/browser/xwalk_render_message_filter.h
- runtime/common/android/xwalk_render_view_messages.h
- runtime/renderer/xwalk_content_renderer_client.cc
- runtime/renderer/xwalk_content_renderer_client.h
- test/android/core/javatests/src/org/xwalk/core/xwview/test/ShouldOverrideUrlLoadingTest.java
Current implementation of shouldOverrideUrlLoading has confliction
with the original design intent. In native side, handle
shouldOverrideUrlLoading should via a sync IPC instead of current
scheme, which is only used to post onPageStarted in Android WebView.
And then, the test case also need to make corresponding changes,
for example, loading "file:///android_asset" and iframe will not
trigger shouldOverrideUrlLoading.
See CreateThrottlesForNavigation in xwalk_content_browser_client.cc
and HandleNavigation in xwalk_content_renderer_client.cc for more
details.
BUG=XWALK-6630
> [Android] Refine the implementation of shouldOverrideUrlLoading

- PRESUBMIT.py
This protects us from changes in depot_tools that cause problems for us.
For example, https://codereview.chromium.org/1897153003 breaks our use
case in the Buildbot slaves: Crosswalk is checked out inside the
chromium-crosswalk directory, which is checked out inside our Buildbot
git repository. That CL makes FileInfo.RepositoryName() find the
outermost git repository, which is the Buildbot one. In the end, the
suggested include guards will be wrong and look like this:
XWALK_SLAVE_CROSSWALK_LINUX_BUILD_SRC_XWALK_RUNTIME_BROWSER_XWALK_PRESENTATION_SERVICE_HELPER_ANDROID_H_
Since we know our repository layout, we can take a shortcut and just
return the path we want with the right prefix by doing some string
manipulation.
> PRESUBMIT: Stop relying on cpplint.FileInfo.RepositoryName().

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- runtime/browser/android/xwalk_content.cc
- runtime/browser/android/xwalk_content.h
- test/android/core/javatests/src/org/xwalk/core/xwview/test/ClearSslPreferenceTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
This patch is to implement the embedding api of getCertificate().
Refine the test case to cover getCertificate().
BUG=XWALK-6734
> [Android] Implement the embedding API: getCertificate().

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Show special option was fixed in https://github.com/crosswalk-project/crosswalk/pull/3520,
there is an exception that is the write external permission was not
added, then select the wrong option even if the accept type was correct.
BUG=XWALK-6430
> [Android] Fix the wrong choice for input element.

- runtime/browser/media/media_capture_devices_dispatcher.cc
- runtime/browser/runtime.cc
We just follow upstream and ease local debugging, regular
http is still disallowed, only https.
BUG=XWALK-6562
> [Windows][Linux] Allow localhost for media capture APIs

- runtime/android/core_internal/src/org/xwalk/core/internal/UrlUtilities.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkNavigationHandler.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkNavigationHandlerImpl.java
This patch is to support the custom url scheme, e.g. "whatsapp://",
"intent://".
For "intent://", if the related app, e.g. Barcode Scanner, was
installed, then start the activity to launch this scanner, if it was
not installed, XWalkView will load the fallback url if it was specified.
For "whatsapp://", if whatsapp was installed, start the activity to
launch it, if it was not installed, then try to install it from market
according to the package name. If the package name is null, will report
"ERR_UNKNOWN_URL_SCHEME".
BUG=XWALK-6690
> [Android] Implement the feature about custom url scheme.

- runtime/browser/android/xwalk_settings.cc
- test/android/core/javatests/src/org/xwalk/core/xwview/test/WideViewportTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
This patch is to enable wide viewport quirks mode default. Without
enabling, the page is zoom out which is different from WebView.
Porting the test case for wide viewport from Android WebView.
Please refer to https://chromiumcodereview.appspot.com/23496047
BUG=XWALK-6762
> [Android] Enable the wide viewport quirks mode default.

- runtime/browser/runtime_download_manager_delegate.cc
- runtime/common/xwalk_paths.cc
- runtime/common/xwalk_paths.h
Implement download support for Windows as it was already almost finished.
I removed the code when not built with Aura because it's dead code
(Windows, Linux are built with Aura by default). I also put the code
to figure out the Download path in the common place with other key paths.
BUG=XWALK-4969
> [Windows] Download support

- runtime/browser/xwalk_render_message_filter.cc
- runtime/browser/xwalk_render_message_filter.h
Currently shouldOverrideUrlLoading happens at the IO thread. But this
was assumed to happen at the UI thread. Also, this will lead to crash
in debug build. This commit ensures shouldOverrideUrlLoading happens
at the UI thread and avoids debug crash.
BUG=XWALK-6866
> [Android] Move IO thread's shouldOverrideUrlLoading to UI thread

- application/browser/application_security_policy.cc
- application/browser/application_security_policy.h
- runtime/common/xwalk_common_messages.h
- runtime/renderer/xwalk_render_process_observer_generic.cc
- runtime/renderer/xwalk_render_process_observer_generic.h
This patch enables manifest CSP rules containing '*' such as:
'http://*/' or 'https://*.example.com'.
BUG=XWALK-6745
> [Windows][Linux] Support of '*' CSP rules for applications

- DEPS.xwalk
The original ffmpeg uses the system call "posix_memalign" that
doesn't exist on Android 4.0. So fetch forked repo to fix this issue.
BUG=XWALK-6740
> [Android] Fix the issue that ffmpeg is incompatible on ICS device

- extensions/browser/xwalk_extension_data.cc
- extensions/browser/xwalk_extension_data.h
- extensions/browser/xwalk_extension_service.cc
- extensions/browser/xwalk_extension_service.h
When either of these two processes are dying then it may be that there
are still messages being filtered in the IPC channel. If so then the filter
may have dangling pointers to the extension thread server or the ui thread
server (as those have been deleted already). The solution is to invalidate
the filter when deleting the XWalkExtensionData object. Please note that
this commit partially revert XWALK-4295 beside the call to RemoveFilter in
OnRenderProcessHostClosed which was the cause of the crash (double delete
because RemoveFilter also delete the filter).
BUG=XWALK-6856
> Fix race condition when RenderProcess or ExtensionProcess dies.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
- runtime/browser/android/xwalk_settings.cc
- test/android/core/javatests/src/org/xwalk/core/xwview/test/LoadWithOverviewModeTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
This patch is to implement the embedding API of
setLoadWithOverviewMode() and getLoadWithOverviewMode().
Import test cases for overview mode.
BUG=XWALK-6859
> [Android] Implement embedding API about loading with overview mode.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Make a few APIs of XWalkView reservable, which means the developer can
invoke these methods before xwalk is ready.
> [Android] Make a few APIs of XWalkView reservble

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
Implement new interface, onXWalkFailed, to handle the error when the
initialization of Crosswalk Project runtime has failed.
> [Android] Implement new interface for XWalkActivity

- runtime/browser/runtime_url_request_context_getter.cc
This is a regression after moving to M50 and the actual refactor due
to CookieMonster being hidden as an API.
https://github.com/crosswalk-project/crosswalk/commit/e1f52c3660f3868a11cccbae67593b435672160d
landed an incorrect change.
BUG=XWALK-6934
> Make sure default schemes (https, http...) are allowed to store cookies.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
- runtime/browser/android/xwalk_settings.cc
- test/android/core/javatests/src/org/xwalk/core/xwview/test/LoadWithOverviewModeTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/SetInitialScaleTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/UseWideViewportTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/XWalkViewInternalTestBase.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/ZoomTest.java
Enable the wide viewport quirk by default.
Implement embedding APIs: setLoadWithOverviewMode(), getLoadWithOverviewMode().
Patch for overview mode should be merged after enabling wide viewport quirk, otherwise will lead to one test case(testSetInitialScale2) failed.
BUG=XWALK-6762
BUG=XWALK-6859
> [Android] Enable the wide viewport quirk and implement APIs about loading overview mode.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkCookieManagerInternal.java
Some customers complain long debug time to know that url without scheme is invalid
when using XWalkCooikeManager, which isn't required in Android WebView.
This is because CookieManager already use WebAddress to add scheme into the url.
For the different design, xwalk will not do the same implementation, but it's better
to throw an exception to user in this case.
BUG=XWALK-6766
> [Android] Indicate that a malformed URL isn't accepted by XWalkCooikeManager

- runtime/browser/android/cookie_manager.cc
After rebaseing to M50, a cross-thread wrapper had been
implemented to around CookieStore. this patch is to correct
a rebase missing, while also fix an issue that deleted cookies
are resurrected in some cases.
BUG=XWALK-6321
> [Android] Optimize cookie store task runner

- runtime/android/core_internal/src/org/xwalk/core/internal/ReflectField.java
XWalkViewBridge will try to get the member mAnimatable from XWalkView.
But if the class type in the layout file is XWalkView's subclass, the
member can't be found and a exception is thrown. This patch will look
for the member by going up the class hierarchy.
> [Android] Fix crash when setting surface type through layout

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Fix build errors caused by commits 5505ef4 ("[Android] Refactor download
mode") and 1c6ecad ("[Android] Implement the method to set compositing
surface type for single XWalkView"):
```
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkActivity.java:60: error: header used out of sequence: <H5>
* <h5>Shared Mode</h5>
^
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkUpdater.java:172: error: header used out of sequence: <H5>
* <h5>Shared Mode</h5>
^
../out/Release/gen/xwalk_core_reflection_layer/wrapper/org/xwalk/core/XWalkView.java:96: error: text not allowed in <ol> element
*   </li></ul></li>
^
```
> [Android] Fix javadoc build with JDK 1.8.

- DEPS.xwalk
Use new rev for chromium-crosswalk repo. 
The chromium-crosswalk had been changed to resolve duplicated 
resource issues.
@heke123 @PeterWangIntel @halton
> [Lite] update chromium-crosswalk rev in DEPS.xwalk

- application/browser/application_security_policy.cc
This PR fixes handling of URLs without separtors e.g. "frame-src https://crosswalk-project.org"
BUG=XWALK-6906
> Handle URLs without seperators in CSP rules properly

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkActivityDelegate.java
The user can't set external dialog manager to XWalkActivity anymore.
Instead, they can get internal manager and modify the dialog.
> [Android] Change the inteface for setting dialog manager

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
The old version of XWalkView doesn't have the private member
mAnimatable. When those versions of shared app are trying to link to
newest library, XWalkViewBridge in the library side can't find the
member and will throw an exception which causes the app crash.
> [Android] Fix a crash issue of shared mode

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/browser/android/xwalk_contents_client_bridge.cc
- runtime/browser/android/xwalk_contents_client_bridge.h
- test/android/core/javatests/src/org/xwalk/core/xwview/test/EnterAndLeaveFullscreenTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
This issue was introduced by
https://github.com/crosswalk-project/crosswalk/commit/6761e07c3e7fa54d2766d8d94ffeafa40603b9ae
mNativeWebContents was not initialized, so it's value is invalid, can't
get the web contents from it.
Refine test case to catch this issue.
BUG=XWALK-3889
> [Android] Fix the issue that failed to exit fullscreen.

- runtime/browser/xwalk_browser_context.cc
We were getting following error on all of the browsertests,
[109919:109919:0602/121714:FATAL:browser_context.cc(350)] Check failed: browser_context->GetUserData(kMojoWasInitialized). Attempting to get the mojo user id for a BrowserContext that was never Initialize()ed
becasue we were not initilizing the BrowserContext. This patch fixes it by
calling BrowserContext::Initialize() with appropriate path.
adapted from,
https://codereview.chromium.org/1741953002
BUG=XWALK-6951
> M51: Fix browsertests on linux

- DEPS.xwalk
* b15d01e Merge pull request #357 from rakuco/xw20-remove-dot-gclient
* 6956b58 Remove .gclient and .gclient_entries.
BUG=XWALK-6961
> DEPS.xwalk: Roll chromium-crosswalk (0732335 -> b15d01e).

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Fix build errors caused by commits 5505ef4 ("[Android] Refactor download
mode") and 1c6ecad ("[Android] Implement the method to set compositing
surface type for single XWalkView"):
```
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkActivity.java:60: error: header used out of sequence: <H5>
* <h5>Shared Mode</h5>
^
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkUpdater.java:172: error: header used out of sequence: <H5>
* <h5>Shared Mode</h5>
^
../out/Release/gen/xwalk_core_reflection_layer/wrapper/org/xwalk/core/XWalkView.java:96: error: text not allowed in <ol> element
*   </li></ul></li>
^
```
(cherry picked from commit f6943eea83a478a167a08053210ac3ffcc41e0c8)
> crosswalk-20: [Android] Fix javadoc build with JDK 1.8.

- DEPS.xwalk
- build/common.gypi
**IMPORTANT**
We actually intend to fix this properly. We are cherry-picking
this commit from the crosswalk-18 branch first in order to have a stable
baseline with no WebVR support propagating from Crosswalk 21 to 20 to 19.
After that, we can start working on fixing this in 21 and 20 and, if there
is enough time, 19 too.
*From the original commit message:*
Disable WebVR support on Android by default, since it depends on
`third_party/cardboard-java` which in turn needs
`third_party/android_protobuf`.
The dependency on `android_protobuf` means `xwalk_core_library_java.jar`
bundle Protobuf and cause build conflicts for users depending on Protobuf
themselves (or using other libraries that pull it).
Related BUG=XWALK-6597
> Build with enable_webvr=0 by default.

- DEPS.xwalk
- build/common.gypi
**IMPORTANT**
We actually intend to fix this properly. We are cherry-picking
this commit from the crosswalk-18 branch first in order to have a stable
baseline with no WebVR support propagating from Crosswalk 21 to 20 to 19.
After that, we can start working on fixing this in 21 and 20 and, if there
is enough time, 19 too.
*From the original commit message:*
Disable WebVR support on Android by default, since it depends on
`third_party/cardboard-java` which in turn needs
`third_party/android_protobuf`.
The dependency on `android_protobuf` means `xwalk_core_library_java.jar`
bundle Protobuf and cause build conflicts for users depending on Protobuf
themselves (or using other libraries that pull it).
Related BUG=XWALK-6597
> crosswalk-20: Build with enable_webvr=0 by default.

- DEPS.xwalk
- build/common.gypi
**IMPORTANT**
We actually intend to fix this properly. We are cherry-picking
this commit from the crosswalk-18 branch first in order to have a stable
baseline with no WebVR support propagating from Crosswalk 21 to 20 to 19.
After that, we can start working on fixing this in 21 and 20 and, if there
is enough time, 19 too.
*From the original commit message:*
Disable WebVR support on Android by default, since it depends on
`third_party/cardboard-java` which in turn needs
`third_party/android_protobuf`.
The dependency on `android_protobuf` means `xwalk_core_library_java.jar`
bundle Protobuf and cause build conflicts for users depending on Protobuf
themselves (or using other libraries that pull it).
Related BUG=XWALK-6597
> crosswalk-19: Build with enable_webvr=0 by default.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
BUG=XWALK-6840
XWalk would destroy contentViewRenderView first and then cleanupReference which points
other native object such as exitFullScreen, it will use contentViewRenderView
when in full screen. So app would cause crash. The correct behavior is that exit full
screen first and then destroy contentViewRenderView.
> Refine destroy order in XWalkContent.java

- DEPS.xwalk
This corrects the commit hashes of chromium-crosswalk and v8-crosswalk
when I rolled Chromium 51.0.2704.84 earlier.
> DEPS.xwalk: Roll chromium-crosswalk and v8-crosswalk

- DEPS.xwalk
They need to be rolled in tandem because we are reverting the XDK
patches present in both repositories.
chromium-crosswalk:
* d5ea4e0 Merge pull request #362 from rakuco/revert-xdk-bits
* 2e10ac6 Revert "[XDK] Add in-depth allocation tracker"
v8-crosswalk:
* 78a7e24 Merge pull request #157 from rakuco/fix-standalone-build
* 4e54260 Adjust coding style in files touched by e236921.
* e236921 Revert "XDK Heap Profiler collector and XDK CPUProfiler"
* fb55f85 Merge pull request #152 from chuan9/xwalk-7000
* f1292ef Add Bool32x4ExtractLane on x64 Bug=XWALK-7000
BUG=XWALK-7000
> DEPS.xwalk: Roll chromium-crosswalk and v8-crosswalk.

- RELEASENOTES.md
Updating the release notes to reflect the fact that Crosswalk 19 is stable. The same change will be applied to the 19 and 20 branches.
> Update release notes for Crosswalk stable

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
Commit 266c02a0 ("[Android] Refine the class description of embedding
API") broke the javadoc build again:
```
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkActivity.java:75: error: malformed HTML
* properties. </pn.>
^
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkActivity.java:75: error: bad use of '>'
* properties. </pn.>
^
```
> [Android] Fix OpenJDK 8 javadoc build after 266c02a0.

- extensions/extension_process/xwalk_extension_process.cc
The IPC::AttachmentBroker must be initialized within
any process that uses IPC channel, however this was not
done so far for extension process in Crosswalk.
This patch initializes the attachment brocker for extension
process with an 'AttachmentBrokerPrivileged' instance as 
extension process is privileged.
BUG=XWALK-7021
> Init IPC attachment broker for extension process

- build/android/merge_jars.py
- xwalk_core_library_android.gypi
This builds upon the initial work done in commit 862201b ("[Android]
Only merge JARs which we have built ourselves").
That commit filtered the JARs being merged based on whether they were
located inside our build directory. That is not enough, as we sometimes
build a few JARs that contain classes in packages that can clash with
other JARs a user may use:
* `jsr_305_javalib.jar` has classes in the `javax.annotation` package.
* `protobuf_nano_javalib.jar` has classes in the
`com.google.protobuf.nano` package.
The latter in particular is built as a dependency for the
`cardboard.jar` blob (itself a dependency for WebVR support) and causes
conflicts with LibPhoneNumber.
So instead of filtering JARs by their location, we now inspect each JAR
and skip those with classes outside the package …
> [Android] Filter JARs being merged by the classes they contain.

- DEPS.xwalk
* a198c47 Merge pull request #365 from rakuco/backport-binutils-roll
* 7015049 [Backport] Update third_party/binutils to 2.26, add ICF fix
Rolling binutils to 2.26 fixes linker issues with Ubuntu 16.04 when
Chromium's clang and binutils are used (the default).
BUG=XWALK-7062
> DEPS.xwalk: Roll chromium-crosswalk (d3001c4 -> a198c47)

- DEPS.xwalk
https://codereview.chromium.org/2099153003 has recently switched the
default value of the `managed` option to False instead of True.
Since we did not explicitly set that option in `.gclient-xwalk` before,
it means that for the last few days existing `src/` checkouts were not
being automatically updated to match `chromium_crosswalk_rev` any
longer, which was particularly bad for the bots, which were not testing
the commits they should.
> DEPS.xwalk: Explicitly set `managed` to True in .gclient-xwalk.

- DEPS.xwalk
https://codereview.chromium.org/2099153003 has recently switched the
default value of the `managed` option to False instead of True.
Since we did not explicitly set that option in `.gclient-xwalk` before,
it means that for the last few days existing `src/` checkouts were not
being automatically updated to match `chromium_crosswalk_rev` any
longer, which was particularly bad for the bots, which were not testing
the commits they should.
(cherry picked from commit e9f19a987c604f30b46420fcbdb679e5f977fb98)
> crosswalk-20: DEPS.xwalk: Explicitly set `managed` to True in .gclient-xwalk.

- build/common.gypi
This issue was caused by https://codereview.chromium.org/1577433004
The condition of 'OS=="android"' was removed, this leads to
'proprietary_codecs' was always 0, then mp4 and other codecs could not
be added to related 'MediaFormatMappings'.
'proprietary_codecs' was defined in the condition in src/build/common.gypi,
so in src/xwalk/common.gypi, 'proprietary_codecs' should also be moved
to condition to keep same scope level.
BUG=XWALK-7032
> Fix the video play issue after M51 rebase.

- .gitignore
- DEPS.xwalk
This is the easiest solution the problem of getting depot_tools to find
`clang-format` and `gn`: our checkout process is structured in such a
way that `gclient_utils.GetBuildtoolsPath()` fails to find the binaries
in `src/buildtools` since `src` is actually checked out via
`.gclient-xwalk`, not `.gclient`.
This was causing our bots to fail on presubmit checks such as
`CheckGNFormatted` and `CheckPatchFormatted` because the binaries which
actually perform those checks were not being found correctly: the
detection only worked if the commands were invoked from `src`.
While we could set the `CHROMIUM_BUILDTOOLS_PATH` environment variable
in the bots, the problem would resurface locally for any developer who
tried to run the presubmit checks (or the binaries directly to format
their patches …
> Start fetching a copy of src/buildtools.git into src/xwalk/buildtools.

- RELEASENOTES.md
Update release notes for Crosswalk 20. This should be merged before branching CW 20.
Note that the date for Crosswalk 19 stable will need to be added in all active branches when Crosswalk 19 is promoted.
> Update release notes for Crosswalk 20

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/SettingsTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
XWalk already has the implementation of them, there just expose
them, and add the test cases.
BUG=XWALK-7055
> [Android] Expose set/getDomStorageEnabled in XWalkSettings

- runtime/browser/runtime.cc
- runtime/browser/runtime.h
- runtime/browser/xwalk_browser_context.cc
- runtime/browser/xwalk_browser_context.h
- runtime/renderer/xwalk_content_renderer_client.cc
- runtime/renderer/xwalk_content_renderer_client.h
So they can change color appropriately if you already navigated that URL.
Mostly borrowing the work already done for Android.
BUG=XWALK-6935
(cherry picked from commit 98d737fb480d8f718702df6cb00d37cf1050f76f)
> [Linux][Windows] Implement navigation history of links.

- runtime/android/core_internal/src/org/xwalk/core/internal/SslUtil.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/strings/android_xwalk_strings.grd
- test/android/core/javatests/src/org/xwalk/core/xwview/test/ClearSslPreferenceTest.java
For SSL errors, if user allows it, native layer will keep the host and
the error num, the future communications with same host and error will
not trigger the onReceivedSslError callback. Even if the certificate is
invalid, all of requests will also be passed, its vulnerable for some
serious SSL error.
Especially with MITM, the sensitive messages will be stolen, e.g.
passwords, credit cards.
Deny the invalid requests for some serious SSL error to avoid this issue.
For keeping the host and error num, please refer to
https://codereview.chromium.org/794023002
We also have the same implementation.
BUG=XWALK-6986
> [Android] Fix the potential vulnerability issue.

- app/android/app_hello_world/AndroidManifest.xml
- app/android/app_template/AndroidManifest.xml
- app/android/runtime_client_embedded_shell/AndroidManifest.xml
- app/android/runtime_client_shell/AndroidManifest.xml
- build/android/xwalk_shared_library_template/AndroidManifest.xml
- build/android/xwalkcore_library_template/AndroidManifest.xml
- runtime/android/core_internal_empty/AndroidManifest.xml
- runtime/android/core_internal_shell/AndroidManifest.xml
- runtime/android/core_shell/AndroidManifest.xml
- runtime/android/runtime_lib/AndroidManifest.xml
- runtime/android/sample/AndroidManifest.xml
- test/android/core/javatests/AndroidManifest.xml
- test/android/core_internal/javatests/AndroidManifest.xml
- test/android/runtime_client/javatests/AndroidManifest.xml
- test/android/runtime_client_embedded/javatests/AndroidManifest.xml
Since we've dropped Android 4.0 support from Crosswalk-20, change the
minSdkVersion from 14 to 16.
> [Android] Change minSdkVersion to 16

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/SettingsTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
These APIs include set/getJavaScriptEnabled, and
set/getJavaScriptCanOpenWindowsAutomatically.
In additation, this commit also correct some mistakes in
commit b4db96745c5114fc861df9411f1a15b18f6210dd.
BUG=XWALK-7080
> Expose setJavaScript related APIs

- runtime/browser/xwalk_browser_context.h
- runtime/browser/xwalk_content_browser_client.cc
- runtime/browser/xwalk_content_browser_client.h
prompt.
Bug is a regression after M51 and incorrect patch of
8d0c7a657433574edc397e2dbebe8dcc690e45c1 which removes the functions
CreateRequestContext and CreateRequestContextForStoragePartition from
XWalkContentBrowserClient as they moved to BrowserContext (so
XWalkBrowserContext). The problem is that they were setting the
url_request_context_getter_ member before calling XWalkBrowserContext.
The URL request context is then used afterwards inside xwalk to query
things like geolocation. With that accidental removal it was always null
so it was crashing/asserting later in the geolocation code. Fix is to
setup a getter from the browser context to access the URL request context
when creating the AccessTokenStore.
BUG=XWALK-7067
> [Windows][Linux] Fix Geolocation crashing after the user accept the

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
As a frequently used feature, it is also enabled in Chrome in default.
And change the value may cause potential risk, so reset it to original.
BUG=XWALK-7082
> [Android] Reset the default value of setDomStorageEnabled

- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
Support more outputs when detecting the CPU architecture of the device.
(cherry picked from commit 92ccf0558274dc5637f51a06ab8159501034fb0f)
> [Android] Support more outputs of ABI

- runtime/android/core_internal/src/org/xwalk/core/internal/SslUtil.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/strings/android_xwalk_strings.grd
- test/android/core/javatests/src/org/xwalk/core/xwview/test/ClearSslPreferenceTest.java
This reverts commit 4b3000b18cb9f80b5cb41a412b0588758644834a.
The build broke:
```
test/android/core/javatests/src/org/xwalk/core/xwview/test/ClearSslPreferenceTest.java:92: error: cannot find symbol
assertNull(getCertificateOnUiThread());
^
symbol:   method getCertificateOnUiThread()
location: class ClearSslPreferenceTest
test/android/core/javatests/src/org/xwalk/core/xwview/test/ClearSslPreferenceTest.java:96: error: cannot find symbol
assertNull(getCertificateOnUiThread());
^
symbol:   method getCertificateOnUiThread()
location: class ClearSslPreferenceTest
```
BUG=XWALK-6986
> Revert PR#3810.

- runtime/browser/ui/color_chooser_aura.cc
The original implementation with CreateWindowWithContext may cause
X receive a bad window parameter and the ColorChooserView is placed
at a fixed position but not bundled with the root window.
> The program 'xwalk' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
(Details: serial 1767 error_code 3 request_code 3 minor_code 0)
(Note to programmers: normally, X errors are reported asynchronously;
that is, you will receive the error a while after causing it.
To debug your program, run it with the --sync command line
option to change this behavior. You can then get a meaningful
backtrace from your debugger if you break on the gdk_x_error() function.)
Now we use CreateWindowWithParent to parent the …
> [Linux] Fix the crash in ColorChooser

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
- runtime/browser/android/xwalk_settings.cc
- runtime/renderer/android/xwalk_permission_client.cc
- runtime/renderer/android/xwalk_permission_client.h
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnCreateWindowRequestedTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/SettingsTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/util/ImagePageGenerator.java
In this commit, five set APIs are exposed with their test cases.
They are set/getLoadsImagesAutomatically, set/getBlockNetworkImage,
set/getDatabaseEnabled, set/getMediaPlaybackRequiresUserGesture,
and set/getSupportMultipleWindows.
The key point is that here fix the issue of setgetLoadsImagesAutomatically
not works. The background is in crbug.com/224317.
BUG=XWALK-7054
> [Android] Expose some APIs in XWalkSettings

- extensions/common/xwalk_extension_messages.h
To fix build failure on Linux
```
../../xwalk/extensions/common/xwalk_extension_messages.h:79:1: error: [chromium-ipc] IPC tuple references banned type 'size_t'.
```
> Build fix for m52 on Linux

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
The background is XWalkView has been refactored in the commit 9808ed4.
Here correct the endless loop error which will cause crash.
BUG=XWALK-7099
> [Android] Fix the crash bug of setOnTouchListener

- runtime/android/core/src/org/xwalk/core/XWalkEnvironment.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
Returns null instead of false when getting boolean value of the meta
data in the Android manifest.
BUG=XWALK-7115
> [Android] Fixed the bug of getting wrong meta data

- DEPS.xwalk
d4a8f69 Merge pull request #160 from chuan9/xwalk-6040-release
99f0e62 Add SIMD.Bool32x4.allTrue in crankshaft, use SIMD.Int32x4 to represent result of SIMD.Float32x4.lessThanOrEqual to accelerate mandlebrot, wirte testcase for SIMID.Bool32x4.anyTrue and SIMD.Bool32x4.allTrue. It's a workaround and needed to be refined
e7ca202 [SIMD.Bool32x4] Modify parameter of SIMD.Int32x4.select in crankshaft, and change the method of constructor of SIMD.Bool32x4 for ia32 and x64 Correct type to SIMD128_VALUE_TYPE in HanleTaggedToSIMD128
ef916fc Adjust coding style in files touched by e236921
BUG=XWALK-6040
> DEPS.xwalk: Roll v8-crosswalk (ef916fc->d4a8f69)

- runtime/browser/xwalk_presentation_service_helper.cc
- runtime/browser/xwalk_presentation_service_helper.h
When creating the monitors list we need to make sure that they are
initialized first as not in use. In order to do that we're removing the
user defined DisplayInfo constructor and thanks to C++11 the field in_use
will be set to false. Before the field was not initialized by default
and was being affected a random value (which then resolve as true) and
all monitors becomes in use and the API never let you choose one.
BUG=XWALK-7098
> [Windows] Presentation API : Fix bug where no screens would be listed as available.

- runtime/browser/xwalk_presentation_service_helper.cc
- runtime/browser/xwalk_presentation_service_helper.h
Chromium style requires us to define an explicit out-of-line constructor
so we can't use the C++11 trick. Let's just use old school initialization.
> [Linux] Fix build after 630ba8e

- build/common.gypi
Upstream Chromium has not supported Ubuntu Precise as a build host for a
while now, and all our bots and builders have been upgraded to Ubuntu
Trusty since this change was introduced.
> gyp: Drop build flag workaround for Ubuntu Precise.

- build/common.gypi
Changing it used to make sense because we used to enable it on Windows
by default before reverting that change. We're now always setting it to
the same value it has by default upstream.
Related BUG=XWALK-6207
> Stop changing |enable_widevine| in gyp.

- runtime/common/xwalk_content_client.cc
- runtime/common/xwalk_content_client.h
- runtime/common/xwalk_content_client_unittest.cc
Inspector.
It turns out that the Renderer was crashing so the inspector would stop
working. The Resources tab lists for example the application cache, as
well as the IndexedDb or the ServiceWorker. Chromium now requires these
values to be coming from a secured origin (such as HTTPS) but in the case
of Crosswalk it was failing (and thus sending a bad IPC message which
would trigger the shutdown of the renderer) because we use the app://
protocol. This scheme is trusted so we can safely add it as such.
BUG=XWALK-7194
> [Windows][Linux] Fix crash when clicking the Resources tab in the

- runtime/browser/xwalk_ssl_host_state_delegate.cc
- runtime/browser/xwalk_ssl_host_state_delegate.h
- runtime/common/xwalk_runtime_features.cc
- runtime/common/xwalk_runtime_features.h
The two commits in this pull request are required to fix the Linux build
when `use_sysroot` is enabled (which we use for our release builds)
after moving to M52.
Something in the old libstdc++ classes in the Debian Wheezy sysroot end
up causing Chromium's chromium-style clang plugin to complain; when
`use_sysroot` is disabled (as is the case by default and what our
Buildbot slaves build), the libstdc++ version used is much more recent
and does not trigger Chromium's plugin.
BUG=XWALK-7022
> Add copy-constructors to some classes to fix the sysroot build.

- application/common/manifest_handlers/csp_handler_unittest.cc
- application/common/manifest_handlers/permissions_handler_unittest.cc
- application/common/manifest_handlers/widget_handler_unittest.cc
- application/test/application_test.cc
- extensions/browser/xwalk_extension_function_handler_unittest.cc
- sysapps/common/binding_object_store_unittest.cc
- sysapps/common/event_target_unittest.cc
With "-Wsign-compare" build option, errors are found:
error: comparison of integers of different signs: 'const unsigned long'
and 'const int' [-Werror,-Wsign-compare]
error: comparison of integers of different signs: 'const int' and
'const unsigned int' [-Werror,-Wsign-compare]
> Eliminate comparisons between size_t and int, different signs in unittest code

- runtime/app/xwalk_main_delegate.cc
- runtime/app/xwalk_main_delegate.h
- runtime/common/xwalk_resource_delegate.cc
- runtime/common/xwalk_resource_delegate.h
- xwalk.gyp
- xwalk_win_zip.gypi
Both Crosswalk and Chrome they place the en-US.pak into folder
"locales" in build of Linux and windows. Potientially there is
conflicts, so it's better to set Crosswalk's locale-path as
"locales/xwalk".
Add a "xwalk_resource_delegate" class which indicates the right
locale pack file to load for Crosswalk.
> Change locale path from "locales" to "locales/xwalk"

- runtime/app/xwalk_main_delegate.cc
- runtime/app/xwalk_main_delegate.h
- runtime/common/xwalk_resource_delegate.cc
- runtime/common/xwalk_resource_delegate.h
- xwalk.gyp
- xwalk_win_zip.gypi
Both Crosswalk and Chrome they place the en-US.pak into folder
"locales" in build of Linux and windows. Potientially there is
conflicts, so it's better to set Crosswalk's locale-path as
"locales/xwalk".
Add a "xwalk_resource_delegate" class which indicates the right
locale pack file to load for Crosswalk.
> Change locale-path from "locales" to "locales/xwalk"

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentView.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- runtime/android/core_internal_shell/res/layout/testshell_activity.xml
- runtime/android/core_internal_shell/src/org/xwalk/core/internal/xwview/shell/XWalkViewInternalShellActivity.java
- runtime/browser/android/xwalk_contents_client_bridge.cc
- runtime/browser/android/xwalk_contents_client_bridge.h
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/RendererResponsivenessTest.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/XWalkViewInternalTestBase.java
This reverts commit 9808ed4cf8bf9b35f312fb5b04fc16cdde692932, it caused
the compatibility in shared mode.
After refactor XWalkView, XWalkViewInternal and ContentViewRenderView
need to be added to XWalkView concurrently. If the older XWalkView was
used, ContentViewRenderView was not added, so leads to the black screen
issue.
Related=XWALK-7217
BUG=XWALK-7100
> Revert "[Android] Refactor XWalkView to receive events directly."

- runtime/browser/android/net/android_stream_reader_url_request_job.cc
This DCHECK should have been removed in commit e1f52c3 ("Roll Chromium
50.0.2661.102") to adapt to https://codereview.chromium.org/1563633002:
the upstream code was refactored and we need to follow the changes that
were done to android_webview's version of this file, otherwise a debug
build crashes at least whenever a media file is being played.
> AndroidStreamReaderURLRequestJob: Remove leftover DCHECK.

- RELEASENOTES.md
SSIA. Note that cherry-pick alone wasn't enough because of some conflicts
> Update release notes for Crosswalk 20 stable

- OWNERS
- app/OWNERS
- build/android/OWNERS
- experimental/presentation/OWNERS
- extensions/OWNERS
- runtime/android/OWNERS
- runtime/android/core_internal/src/org/xwalk/core/internal/extension/api/presentation/OWNERS
- runtime/app/android/OWNERS
- runtime/common/android/OWNERS
- runtime/renderer/android/OWNERS
- sysapps/OWNERS
- test/android/OWNERS
Drop people who have not contributed to the Crosswalk Project in a long
time. When they were the sole OWNERS in a given directory, the file
itself was removed.
> Clean up our OWNERS files.

- xwalk_android.gypi
This was added back in 2013 with commit dd2dbba7 ("[Android] Merge
initial files for native library (libxwalkcore) build") and is no longer
necessary.
> [Android] Stop passing -Wl,--no-fatal-warnings when linking libxwalkcore

- DEPS.xwalk
e9a937d Merge pull request #379 from wuhengzhi/xwalk_7221_widewine_crash
57c7bcc [Backport] Change back to destroy the CDM synchronously
e477547 Merge pull request #366 from halton/quic_assert
[Backport] Disable static_assert about TransmissionInfo size to pass
Rolling to destroy CDM synchronously and disable static_assert.
BUG=XWALK-7221
> DEPS.xwalk: Roll chromium-crosswalk (a198c47 -> e9a937d)

- DEPS.xwalk
Roll our dependencies in order to be able to build Crosswalk with GN in M52. Most of the commits are backports from newer Chromium/V8 releases.
chromium-crosswalk:
* 31733c8 Merge pull request #378 from rakuco/v8-external-data-backport
* f3fb6c0 Merge pull request #375 from heke123/gn-linux-1
* bde5610 Preparation for adding GN build support in Crosswalk.
* 0908bc7 [Backport] gn: Remove unnecessary v8 defaults
* b5d9bfd Merge pull request #377 from rakuco/local-android-commits-gn
* 2462584 [Backport] GN: Set |enable_webvr| in the declare_args() block.
* 70c7fe9 [Android] Add ApplicationStatusManager.java to the GN build.
* b3d3e4d [Temp] Make |enable_webvr==false| work in GN.
v8-crosswalk:
* a91989e Merge pull request #164 from rakuco/backport-gn-fix
* d09d8a9 [Backport][gn] Turn on …
> DEPS.xwalk: Roll chromium-crosswalk (7e0c695..31733c8) and v8-crosswalk (edf5696..a91989e)

- BUILD.gn
- application/BUILD.gn
- application/common/BUILD.gn
- build/common.gni
- build/linux.gni
- build/version.gni
- build/xwalk.gni
- experimental/BUILD.gn
- extensions/BUILD.gn
- extensions/test/BUILD.gn
- resources/BUILD.gn
- resources/locales.gni
- sysapps/BUILD.gn
- test/BUILD.gn
- test/base/BUILD.gn
As Chromium will deprecate GYP build system since M54, we need to enable
GN build support for Crosswalk as soon as possible.
This PR only implements most part of Crosswalk-Linux.
See comments in xwalk/build/linux.gni on how to build.
TODO: Add web_notification, installer support
BUG=XWALK-7180
> Add gn build support for crosswalk-linux

- runtime/android/core_internal/src/org/xwalk/core/internal/CustomViewCallbackHandlerInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/CustomViewCallbackInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentVideoViewClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkUIClientInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkWebChromeClient.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/GeolocationPermissionTest.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/OnShowOnHideCustomViewTest.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/XWalkViewInternalTestBase.java
- tools/reflection_generator/java_method.py
- tools/reflection_generator/reflection_generator.py
The onShow/HideCustomView() was implemented in Crosswalk by default and
not exposed, it could not be overrided by customer to implement the video
fullscreen.
This patch is to expose onShow/HideCustomView().
BUG=XWALK-6939
> [Android] Expose embedding apis for video fullscreen.

- DEPS.xwalk
This fixes a configuration issue with GN introduced by previous commits
to chromium-crosswalk.
See crosswalk-project/chromium-crosswalk#378.
chromium-crosswalk:
* 0a4d8d4f Merge pull request #381 from rakuco/gn-external_snapshot-arg
* 44aed2e [Temp] Declare v8_use_external_startup_data in build_overrides/v8.gni
v8-crosswalk:
* 9e7fe2b Merge pull request #166 from rakuco/gn-external_snapshot-arg
* 92973b7 [Temp] Declare v8_use_external_startup_data in build_overrides/v8.gni
> DEPS.xwalk: Roll chromium (31733c8..0a4d8d4f) and v8 (a91989e..9e7fe2b)

- BUILD.gn
- tools/installer/BUILD.gn
Use the same target name for the gyp and the GN versions, otherwise this
needlessly complicates the release build process and confuses everyone
trying to build Debian packages.
While here, add Chromium's missing copyright to `tools/installer/BUILD.gn`.
BUG=XWALK-7180
> [gn] Rename xwalk_installer_package_deb to xwalk_installer_linux_debian

- tools/reflection_generator/java_method.py
The order of constructing object is parent member variables => parent constructor => child member variables => child constructor, so it will be crash when parent constructor using child override reflected method.
> [Android] Crash when parent construct using child reflected method

- tools/reflection_generator/reflection_generator.py
- xwalk_android.gypi
`reflection_generator.py` expects to receive an integer for the
`--verify-xwalk-apk` argument, which does not make sense. It was likely
added as a shortcut because gyp uses 1 and 0 instead of booleans, so one
could just do `--verify-xwalk-apk=<(my_int_var)` in gyp. Unfortunately,
that does not integrate so well with GN, so revamp how the argument is
handled:
* Turn the `--verify-xwalk-apk` into a boolean argument that does not
require a value; if it is passed in the command line, its value is
true, otherwise it is false.
* Adapt xwalk_android.gypi to follow suit and only pass that argument
when `verify_xwalk_apk` is on.
> reflection_generator: Stop requiring an int for a boolean option.

- tools/reflection_generator/reflection_generator.py
This pull request contains several commits, but the main goal is to make
it work correctly with GN.
With gyp, we are just generating a lot of .java files in the build
directory and depending on the directory where they are written in
`xwalk_core_internal_java`. Depending on a directory does not work with
GN, depending on all those new files directly also fails [1], so we now
follow Chromium's approach of writing those files into zip files called
`.srcjar`s and making `xwalk_core_internal_java` depend on that instead.
This is done by introducing a `--use-srcjars` option (off by default)
while we have to support both gyp and GN.
[1] https://groups.google.com/a/chromium.org/forum/#!topic/gn-dev/GokFp6TorgI
All the commits before the one described above are cleanups to make the
script look …
> Clean up reflection_generator.py and make it work with GN.

- app/android/app_hello_world/AndroidManifest.xml
- app/android/app_template/AndroidManifest.xml
- app/android/runtime_client_embedded_shell/AndroidManifest.xml
- app/android/runtime_client_shell/AndroidManifest.xml
- runtime/android/core_internal_empty/AndroidManifest.xml
- runtime/android/core_internal_shell/AndroidManifest.xml
- runtime/android/core_shell/AndroidManifest.xml
- runtime/android/runtime_lib/AndroidManifest.xml
- test/android/core/javatests/AndroidManifest.xml
- test/android/core_internal/javatests/AndroidManifest.xml
- test/android/runtime_client/javatests/AndroidManifest.xml
- test/android/runtime_client_embedded/javatests/AndroidManifest.xml
When building the APK with stricter options (default in GN), the
following lint warning is shown:
AndroidManifest.xml:26 `<uses-sdk>` tag appears after `<application>` tag: ManifestOrder [warning]
<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="21" />
Fix it by reordering the tags in the files.
> Android: Fix lint warning in AndroidManifest.xml across the tree

- xwalk_core_library_android.gypi
* `generate_resource_maps`: Use `direct_dependent_settings` to set
variables that should be available to targets, there is no reason to
make the variables available to targets that depend on it indirectly.
While here, define `generated_src_dirs` instead of leaving it up to
targets that depend on it to take care of it.
* `xwalk_core_empty_embedder_apk`: Stop depending on
`generate_resource_maps`, it's not used.
> [Android] Clean up xwalk_core_{internal_}empty_embedder_apk

- xwalk_android_tests.gypi
Nothing in `runtime/android/core_internal_shell` seems to have ever
depended on Android's support-v13 library, so remove the dependency.
> [Android] Remove dependency on support_v13 xwalk_core_internal_shell_apk

- runtime/android/core/src/org/xwalk/core/XWalkFileChooser.java
- runtime/browser/android/xwalk_web_contents_delegate.cc
- Fixed crash when no file is uploaded after the file chooser is launched.
- Do not invoke RuntimeFileSelectHelper when the uploaded file is null.
BUG=XWALK-7278
BUG=XWALK-7271
> [Android] Fix crash on file chooser

- DEPS.xwalk
* af36cc3 Merge pull request #384 from rakuco/backport-java_library-gn-fix
* 1f8518af [Backport] GN: Fix java_library() when supplied with a generated .java
* fc6762c Merge pull request #380 from mrunalk/remove_device_position
* fd8c95a Remove unused private field device_position_
> DEPS.xwalk: Roll chromium-crosswalk (fd8c95a..af36cc3)

- runtime/android/core/src/org/xwalk/core/XWalkFileChooser.java
- runtime/android/core/src/org/xwalk/core/extension/XWalkExtensionContextClient.java
- runtime/android/core/src/org/xwalk/core/extension/XWalkExternalExtension.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkCookieManagerInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkResourceClientInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkUIClientInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
This patch completes the method's descriptions that are missing the
field @param or @return.
BUG=XWALK-5643
> [Android] Fix the warnings when generating java docs

- build/android/generate_xwalk_core_library.py
- xwalk_core_library_android.gypi
This makes `xwalk_core_library_android.gypi` stop depending on
`xwalk_android_tests.gypi`; the latter contains just test targets and
thus should not be required by anything not related to tests.
Instead, we now obtain the list of native libraries we want to copy from
the build system itself, which makes a lot more sense than having to
figure out what's in gyp/GN and what's hardcoded in an obscure Python
script.
`gdbserver` is also no longer copied (even in a debug build): the whole
xwalk_core_library thing targets a deprecated IDE (Eclipse) and I
honestly doubt people are debugging their debug Crosswalk builds with
the gdbserver binary from xwalk_core_library.
> [Android] Stop depending on xwalk_core_shell from xwalk_core_library

- BUILD.gn
- app/android/app_hello_world/BUILD.gn
- app/android/app_template/BUILD.gn
- app/android/runtime_client/BUILD.gn
- app/android/runtime_client_embedded_shell/BUILD.gn
- app/android/runtime_client_shell/BUILD.gn
- build/android.gni
- build/version.gni
- build/xwalk.gni
- extensions/BUILD.gn
- extensions/android/BUILD.gn
- extensions/test/BUILD.gn
- resources/BUILD.gn
- runtime/android/core/BUILD.gn
- runtime/android/core_internal/BUILD.gn
- runtime/android/core_internal_shell/BUILD.gn
- runtime/android/core_shell/BUILD.gn
- runtime/android/dummy_lib/BUILD.gn
- runtime/android/runtime_lib/BUILD.gn
- runtime/android/sample/BUILD.gn
- runtime/app/android/BUILD.gn
- test/android/core/javatests/BUILD.gn
- test/android/core_internal/javatests/BUILD.gn
- test/android/runtime_client/javatests/BUILD.gn
- test/android/runtime_client_embedded/javatests/BUILD.gn
- test/android/util/BUILD.gn
- third_party/lzma_sdk/BUILD.gn
In this patch:
1) Inits the GN build configuration for Crosswalk-Android.
2) Build out all of the APKs.
3) Make sure Instrumentation tests pass in GN.
4) Generate xwalk_core_librarys, javadocs, AARs.
TODO: xwalk_core_unittest. lzma support for download mode.
BUG = XWALK-7285
> Enable GN build for crosswalk-android.

- runtime/common/android/xwalk_core_tests.cc
- xwalk_android_tests.gypi
The "xwalk_core_unittests" and "xwalk_core_unittests_apk" are totally
dead code, There is 'java_in_dir': 'test/android/unittestjava' in this
target,but we cannot find it in xwalk src project. Those targets are
not referenced at all.
> [Android] Remove dead code of "xwalk_core_unittests_apk"

- app/android/runtime_client_embedded_shell/BUILD.gn
- runtime/android/core_internal_shell/BUILD.gn
- runtime/android/core_shell/BUILD.gn
- runtime/android/runtime_lib/BUILD.gn
- runtime/android/sample/BUILD.gn
Instead of repeating the same checks for `icu_use_data_file` and
`v8_use_external_startup_data` along with changes to `sources` and
`deps` in many different files, we can leverage the existing upstream
targets whose purpose is to do the exact same thing.
> gn: Use existing targets to manipulate icudtl.dat and V8 snapshots

- runtime/android/core/BUILD.gn
- runtime/android/core_internal/BUILD.gn
Starting with M53, https://codereview.chromium.org/2109293003 enforces a
naming convention for certain Android targets, and if a target name
matches it's assumed to have a `.build_config` file with it.
* Rename `xwalk_app_strings` to `xwalk_app_strings_grd` so GN accepts it
as a valid target that generates a `.build_config`.
* Rename `xwalk_core_reflection_layer_java_gen` to
`xwalk_core_reflection_layer_gen` to achieve the opposite and have GN
_stop_ assuming the target produces a `.build_config` (the "java" part
was making it fall into a naming whitelist).
> gn: Rename a few targets to prepare for M53.

- app/android/runtime_client_embedded_shell/BUILD.gn
- resources/BUILD.gn
- runtime/android/core_internal_shell/BUILD.gn
- runtime/android/core_shell/BUILD.gn
- runtime/android/runtime_lib/BUILD.gn
- runtime/android/sample/BUILD.gn
Get rid of a lot of repetition in the Android `BUILD.gn`s. There were 4
targets doing the exact same thing: calling `android_assets()` to pack
`xwalk.pak` and `xwalk_100_percent.pak` along with ICU and V8 blobs.
Some of those targets were then being depended on in other files,
leading to a needless entanglement in the build system.
Additionally, many `*_apk` targets were duplicating the dependency on
the `xwalk_pak` and `xwalk_resources_100_percent_pak` targets that were
already part of the `*_assets` targets.
We now unify all those targets into `//xwalk/runtime:pak_file_assets`,
and only depend on it from the `*_assets` Android targets (which is also
what upstream does with its targets).
> gn: Unify packing of xwalk{_100_percent}.pak into a single target

- build/android/generate_app_packaging_tool.py
Since we do a simple shutil.copytree() to copy `app/android/app_template`
to `xwalk_app_template/template`, we end up including the `BUILD.gn`
present in the former.
Explicitly ignore `*.gn` files when copying to avoid that.
> [Android] Do not include BUILD.gn in xwalk_app_template/

- BUILD.gn
- build/android/generate_android_project.gni
- build/android/generate_xwalk_core_library.py
- build/android/merge_jars.py
- runtime/android/core/BUILD.gn
- xwalk_core_library_android.gypi
In gyp, they are `xwalk_core_library`, `xwalk_shared_library`,
`xwalk_core_library_aar` and `xwalk_shared_library_aar`.
The GN implementation requires more lines of code, but is hopefully a
lot easier to understand: developers only have to care about the
`xwalk_{core,shared}_library` targets. Everything else is internal to
their implementation.
Thanks to GN's architecture, we can use `build_config` files to write
down a lot of dependency information for each target and use that file's
contents when specifying which resources we want or certain JARs we want
to work or generate. For example, we do not need to manually specify any
of the zipped resource files we use, nor their corresponding paths in
the source tree; we also do not have to hardcode paths to certain JARs,
such as …
> gn: Implement project and AAR generation targets for Android

- BUILD.gn
- app/android/app_template/BUILD.gn
- build/android/generate_app_packaging_tool.py
This is fairly simple after commit cadbd11 ("[Android] Rewrite
generate_app_packaging_tool.py"): we just need to depend on the
recently-added `xwalk_core_library` and `xwalk_shared_library` targets
and specify the paths to everything we want to copy.
We also leverage GN's build_configs to determine the path to the runtime
JAR without having to hardcode it anywhere.
> gn: Implement the xwalk_app_template target

- build/android/generate_xwalk_core_library.py
This is a regression introduced in 4b928d3 ("[Android] Rewrite
generate_xwalk_core_library.py"), where we stopped adding `README.md` to
the `src/` in the projects we create and just left `src/` as an empty
directory.
That works fine when calling app-tools and passing the
`xwalk_app_template` directory to it, but not when using a zipped
version, as app-tools does not create the empty directory and the build
fails like this:
/Users/fbalestr/Devel/adt/sdk/tools/ant/build.xml:597: The following error occurred while executing this line:
/Users/fbalestr/Devel/adt/sdk/tools/ant/build.xml:649: The following error occurred while executing this line:
/Users/fbalestr/Devel/adt/sdk/tools/ant/build.xml:655: /private/var/folders/rv/6r78mqbs5cl8zysfzz_1vmp40000gp/T/NsLBXU/org.foo.bar/prj/android/xwalk_co …
> Add back an empty file to xwalk_{core,shared}_library/src

- BUILD.gn
- build/android/maven_pom.gni
- build/xwalk.gni
- runtime/android/core/BUILD.gn
Port maven_pom.gypi to a GN template, `maven_pom`, which takes care of
calling `version.py` with the appropriate values.
While here, move the declaration of
`xwalk_{core,shared}_library_artifact_id` to
`runtime/android/core/BUILD.gn` which is the only place they are used.
This makes it follow GN's style more closely.
> gn: Add xwalk_{core,shared}_library_pom_gen

- xwalk_core_library_android.gypi
This fixes a regression introduced in commit 8f3c7d3 ("[Android] Stop
depending on xwalk_core_shell from xwalk_core_library"), where
`libxwalkdummy.so` and `libxwalkcore.so` were not being stripped and
added to `xwalk_core_library/` (which is then used for the AAR and
`xwalk_app_template`) in incremental builds, leading to outdated,
existing versions being used instead.
The bug was caused by us not explicitly depending on both unstripped
shared libraries in the action that includes
`strip_native_libraries.gypi`: we were previously only depending on
`native_libraries.json` being updated whenever those shared libraries
changed, but `write_ordered_libraries.py` only updates the JSON file if
its contents are actually different (if we started depending on other
shared libraries, for example). …
> [Android] Directly depend on the .so's we want to strip

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
In the patch #3857(decouple XWalkView from the activity), we need
use WindowAndroid instead of ActivityWindowAndroid as the top window
of XWalkView, but that will prevent DateTimeChooserAndroid activity
to to launched.
Here we create WindowAndroid or ActivityWindowAndroid according to
the context type.
BUG=XWALK-7269
> [Android] Fix the issue that date picker is not work

- BUILD.gn
- build/android/lzma_compress.py
- runtime/android/runtime_lib/BUILD.gn
- xwalk_android.gypi
This was hopefully the last missing Android target in the gyp->GN
conversion, and it is an ugly one: we are forced to keep a hardcoded
list of all the files we want to compress and ship as assets, which
makes the change to `runtime/android/runtime_lib/BUILD.gn` bigger than
usual.
Since `android_assets()` in GN requires a list of all files being
shipped as assets, we can simplify `lzma_compress.py` and get rid of its
different operation modes: instead of passing `--mode=show-output-names`
we just list all files that are being compressed in gyp.
While here, also use a temporary directory to perform the compressions
in `lzma_compress.py`, as it's then removed automatically in case
something goes wrong and we are not left with dangling files in the
build tree.
BUG=XWALK-7285
> gn: Implement the "xwalk_runtime_lib_lzma_apk" target

- runtime/browser/xwalk_browser_main_parts_android.cc
This workaround will not work for long once Chromium makes this
the only code path. So after finding the solution, this patch should
be reverted.
BUG=XWALK-7231
> [Android] Temporary disable the unified media pipeline by default

- DEPS.xwalk
* f3c69fc Merge pull request #385 from rakuco/crt-gn
* 8596c69 [Backport][Windows] Pass "/MD" and variants outside the "runtime_library" target
> DEPS.xwalk: Roll chromium-crosswalk (af36cc3..f3c69fc)

- experimental/wifidirect/wifidirect_extension.gyp
Synchronously running a command to check if `Windows.winmd` is present
makes it more difficult to port Crosswalk on Windows to GN, as we would
at the very least need to do the same thing through a Python script and
a synchronous script call.
We can safely assume that `Windows.md` is always present though, as it
is installed by the Windows 10 SDK required by Chromium as a build
dependency.
> [Windows] wifidirect: Stop checking for Windows.md

- build/msbuild.gypi
- experimental/wifidirect/wifidirect_extension.gyp
- extensions/dotnet_extension_sample.gyp
- tools/msbuild_dotnet.py
Instead of manually calling `msbuild_dotnet.py` and then renaming
`xwalk_dotnet_bridge.dll` every time one wants to build a .NET
extension, do that only once in `msbuild.gypi`: the other targets just
need to define a few variables and include the new gypi file, which then
takes care of doing all the rest.
This considerably reduces the size of the other gyp files and avoids a
lot of duplication.
Clean up `msbuild_dotnet.py` itself a little:
* Stop invoking `MSBuild` from `//xwalk/extensions/test/win`, which
creates some needless complications in the WiFi Direct gyp code.
Instead, just invoke it from the root of the build directory (the
default).
* Use `argparse` instead of `optparse` to avoid having to manually
validate required arguments.
* Pass `/nologo` and `/verbosity:quiet` to …
> [Windows] Add a msbuild.gypi and clean up the MSBuild Python wrapper

- dotnet/xwalk_dotnet_bridge.cc
This avoids the following type of error when building the bridge code
with stricter flags (on by default with GN):
xwalk_dotnet_bridge.cc(388): error C2220: warning treated as error -
no 'object' file generated
xwalk_dotnet_bridge.cc(388): warning C4189: 'returnValue': local
variable initialized but not referenced
> [Windows] Remove unreferenced variables in the .NET bridge code

- build/android/generate_android_project.gni
We were previously creating the Android AARs using the
`AndroidManifest.xml` specified via `invoker.android_manifest`.
While that is correct for all other usages in the
`generate_android_project` template, using it in the AARs we create is
wrong, as the manifest specified via `invoker.android_manifest` is
generally the one in `//xwalk/runtime/android/core_internal_empty`
instead of the one
`//xwalk/build/android/xwalk{core,_shared}_library_template`. The ones
in `build/` specify a different package name and don't have an
`<application>` tag. This tag conflicts with the ones in the manifest
generated by Cordova when building an app, meaning Android GN builds
were not working with Cordova at all.
BUG=XWALK-7348
> gn: Use the AndroidManifest.xml from the template when creating AARs

- DEPS.xwalk
* b53bd1c Merge pull request #386 from rakuco/gn-rssdk
* f1476d3 [Windows] GN: Add missing RSSDK files in media/.
> DEPS.xwalk: Roll chromium-crosswalk (f3c69fc..b53bd1c)

- runtime/android/core/BUILD.gn
- runtime/android/core_internal/BUILD.gn
- runtime/android/core_internal/chromium_java_deps.gni
It is not clear if this is a bug or due to some odd design, but the
xwalk_shared_library Android project needs resources from both
`runtime/android/core_internal` (due to its usage of the reflection
layer wrapper classes) as well as resources from Chromium itself that
the core_internal code depends on.
These same dependencies are also part of `XWalkRuntimeLib` itself, so it
means we need to duplicate them.
For now, introduce a new variable, `core_internal_java_chromium_deps` to
make it clear that this is hopefully something provisional and add some
informative comments instructing people to not add non-//xwalk
dependencies to `xwalk_core_internal_java`s `deps` list.
BUG=XWALK-7350
BUG=XWALK-7358
RELATED BUG=XWALK-7366
> gn: Make xwalk_shared_library depend on additional resource targets

- BUILD.gn
- build/win/generate_crosswalk_zip.py
When GN support for Crosswalk on Windows was landed, I thought there
would be no need to mimic what gyp does and copy //xwalk/VERSION to
`$root_out_dir`.
It turns out this is necessary because `generate_crosswalk_zip.py`
assumes all paths it stores in the zip archive are inside the build
directory. This means the zip file being generated with GN so far had a
relative path inside for `VERSION` (`../../xwalk/VERSION`) which did not
play well with `unzip` and other tools that need to extract it.
A sanity check has been added to `generate_crosswalk_zip.py` to make
sure this does not happen in the future.
While here, drop the `is_win` check from the
`generate_crosswalk_win_zip` target: it just needlessly complicates the
code with a check and another level of indentation.
> gn: Copy //xwalk/VERSION to the build dir for generate_crosswalk_win_zip

- build/win/generate_crosswalk_zip.py
The sanity check introduced in f4a0f97 ("gn: Copy //xwalk/VERSION to the
build dir for generate_crosswalk_win_zip") broke the gyp build.
gyp passes relative paths to the script and mixes "/"s and "\"s, which
broke the os.path.commonprefix check. Fix it by normalizing all paths
first.
> [Windows] Fix gyp build after f4a0f97

- DEPS.xwalk
* cbf42ea Merge pull request #391 from rakuco/xw22-build-fix
* 14d1804 crosswalk-22: Fix the build after e762df3
RELATED BUG=XWALK-7030
RELATED BUG=XWALK-7226
> crosswalk-22: DEPS.xwalk: Roll chromium-crosswalk (1e13f90..cbf42ea)

- runtime/browser/runtime_url_request_context_getter.cc
Add some missing verifiers for TLS/QUIC sockets, following what upstream
has done.
This makes
org.xwalk.core.xwview.test.ClearSslPreferenceTest#testDeniedRequestForSslError
as well as regular SSL connections to websites on any platform (Android
and others) stop crashing.
RELATED BUG=XWALK-7325
> M53 gardening: adapt to https://codereview.chromium.org/2067843003

- extensions/BUILD.gn
- extensions/extensions.gyp
blink_headers is supposed to be used when targets only need access to
Blink structs and enums, which is not the case here, as
`xwalk_v8tools_module.cc` actually calls Blink code.
This was preventing `xwalk_extensions_unittest` from linking in debug
mode with GN and `is_component = true`. gyp was not affected because the
`xwalk_extensions` target there is always built as a static library, but
the code was updated there too for completeness.
> Depend on blink, not blink_headers, in the extensions target

- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
This is a backport of the same android_webview commit from
M53 (afc3aed86 in Chromium, "Fix android webview unit tests to dispatch
correct click event"). It is being landed separately into M52 to reduce
the size of the M53 pull request and to make it easier to identify in
the history that this is being done.
Starting with M53, creating a generic event will not cause a click to be
generated as per Chromium bug 520519, so adjust the code to create a
`MouseEvent` instead.
RELATED BUG=XWALK-7325
> [Android] Dispatch a mouse event when faking a click in the tests

- runtime/browser/android/cookie_manager.cc
Another file copied from upstream, another crash in debug mode. This
`DCHECK` was removed from the android_webview version of `CookieManager`
in 2013 (commit 23dc0bb, "Android WebView: Allow CookieManager to be
used without starting Chromium").
Since then the upstream version has undergone several modifications
while ours remained mostly unchanged. After so many years it's very
likely the `DCHECK` is just wrong and can be removed, otherwise the
following the `CookieManager` Android tests crash in debug mode.
> [Android] Remove DCHECK from CookieManager

- runtime/browser/android/find_helper.cc
- runtime/browser/android/find_helper.h
Incorporate changes that went into the upstream versions of
`find_helper.{cc,h}`:
* 1cfca29 Fix for problem with activating find-in-page match via find
tickbar.
* c0b762b Implement a shell of FindRequestManager, and hook it up to
WebContentsImpl.
In addition to reducing the delta to upstream and making updating the
code in the future easier, it actually makes the code work in debug
mode (we were hitting some DCHECKs because the code had not been
updated).
RELATED BUG=XWALK-7325
> [Android] Sync find_helper.{cc,h} copies with upstream

- runtime/android/core_internal/BUILD.gn
- tools/reflection_generator/reflection_generator.py
- xwalk_android.gypi
We were previously not declaring any `sources` or `inputs`, which means
the target was not being run when any of the files it processes was
modified. In practical terms, it means changing files in `core_internal`
did not run the reflection scripts, which lead to a disconnect between
`core` and `core_internal` and build failures.
Fix it by manually declaring all files this target depends on (the
authors of the gyp side cheated by calling `find(1)`). Since these files
are also used by `xwalk_core_internal_java`, some new variables were
introduced to avoid duplication and to make sure the list is kept
up-to-date.
BUG=XWALK-7385
> gn: Add more dependencies to the xwalk_core_reflection_layer_gen target

- tools/installer/BUILD.gn
`is_ffmpeg_component` is defined there, but we were not importing the
file, which leads to an error in M54.
> tools/installer: Import ffmpeg_options.gni

- build/android/generate_android_project.gni
This fixes a regression introduced in 02104a7 ("Roll Chromium
53.0.2785.143"). Specifically, when the code in `build/android` was
updated due to https://codereview.chromium.org/2082453003 upstream
callers of `generate_android_project` no longer needed to have targets
such as `libxwalkcore` in `deps`, but the `generate_android_project`
itself was not depending on them at all. In practice, this could lead to
failures where `generate_xwalk_core_library.py` would try to operate on
shared libraries that had not yet been built.
> [Android] Depend on the native library targets when generating a project

- BUILD.gn
- extensions/test/BUILD.gn
- sysapps/BUILD.gn
The fix in ba159bc ("tools/installer: Import ffmpeg_options.gni") needs
to be extended to avoid breaking the upcoming M54 build -- that file
needs to be imported in all locations that make use of
`is_component_ffmpeg`.
> Import ffmpeg_options.gni in more locations

- build/android.gni
- runtime/android/core/BUILD.gn
- runtime/android/runtime_lib/BUILD.gn
We were importing the latter to access `v8_use_external_startup_data`.
However, we also had to import http://crrev.com/2058033002 in order to
override its value in `build/android.gni`, which means the value is
actually coming from `//v8/gni/v8.gni` instead.
Import the latter now to avoid errors in the M54 build.
> gn: Import //v8/gni/v8.gni, not //build_overrides/v8.gni

- DEPS.xwalk
* 28e7279 Merge pull request #397 from rakuco/revert-mediacodec-commit
* 00de194 Revert "Revert "Replace WebAudio MediaCodec usage with FFmpeg" commit"
This fixes all the regressions introduced by the previous roll (50c8f93,
"DEPS.xwalk: Roll chromium-crosswalk (ee335c1..e6fb49d)"). See also:
crosswalk-project/chromium-crosswalk#397.
RELATED BUG=XWALK-7307
> DEPS.xwalk: Roll chromium-crosswalk (e6fb49d..28e7279)

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkPreferencesInternal.java
Everytime XWalkPreference.sevValue() is invoked, it checks if previous
listeners exist, if exist and the key is ANIMATABLE_XWALK_VIEW, if
will throw an runtime exception.
The listener is registered when an XWalkView is created and unregistered
when an XWalkView is destroyed. But after XWalkView is decoupled from
the activity, XWalkView can not be destroyed automatically when an
activity is closed. So previous listeners are still remaining  and have
the app crashed.
This patch changs the behavior on this situation, warning that this
setting is not effective to previous XWalkViews instead of throwing the
exception.
BUG=XWALK-7309
> [Android] Fixed crash of XWalkPreferences

- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/OnShowOnHideCustomViewTest.java
The test case of OnShowOnHideCustomViewTest is to test whether the video
is played after click the play button. Bug sometimes the page is not
loaded completely when the click action is performing. By this patch, it
tries to click for more times to make sure the click action is effective.
BUG=XWALK-7197
> [Android] Fixed test errors

- tools/reflection_generator/java_class.py
- tools/reflection_generator/java_method.py
When generating the reflection layer, if a method that is marked as
@XWalkAPI is markd as @Deprecated as well, the @Deprecated annotation
will also appears in the new generated wrapper class. This will help to
make the javadoc display more precise method information.
BUG=XWALK-7384
> [Android] Reflection generator supports the @Deprecated annotation

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
Add assertions on holding the lock into getters called from native code.
BUG=XWALK-5635
> [Android]Fix thread unsafety in accessing Java side getters

- build/android/generate_android_project.gni
- build/android/generate_xwalk_core_library.py
- build/android/generate_xwalk_core_library_aar.py
Contrary to what one would expect, having a dependency on a shared
library target such as `libxwalkcore` does not cause an action to be
re-run whenever the aforementioned shared library changes -- the .ninja
file only depends on the library's .TOC file, so the action is called
only if the library's symbol list changes.
In practice, this means rebuilding `libxwalkcore.so` would not cause
`xwalk_core_library` and its respective AAR to be regenerated, leading
to all sorts of problems.
We work around the issue by adding `depfile`s to the GN actions, and
then adding those native libraries (as well as some other files like the
.js ones in xwalk_core_library) to them. GN can then use their contents
and trigger the actions when the files there change (in addition to the
ones regularly tracked by …
> [Android] Use depfiles when generating projects and AARs

- build/android/generate_android_project.gni
- build/android/generate_xwalk_core_library.py
- build/android/generate_xwalk_core_library_aar.py
Contrary to what one would expect, having a dependency on a shared
library target such as `libxwalkcore` does not cause an action to be
re-run whenever the aforementioned shared library changes -- the .ninja
file only depends on the library's .TOC file, so the action is called
only if the library's symbol list changes.
In practice, this means rebuilding `libxwalkcore.so` would not cause
`xwalk_core_library` and its respective AAR to be regenerated, leading
to all sorts of problems.
We work around the issue by adding `depfile`s to the GN actions, and
then adding those native libraries (as well as some other files like the
.js ones in xwalk_core_library) to them. GN can then use their contents
and trigger the actions when the files there change (in addition to the
ones regularly tracked by …
> crosswalk-23: [Android] Use depfiles when generating projects and AARs

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkPresentationHost.java
The developer who want to use presentation has to add the permission:
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
BUG=XWALK-7270
> [Android] Make the presentation support the application context

- runtime/browser/android/cookie_manager.cc
- runtime/browser/xwalk_browser_main_parts_android.cc
- runtime/browser/xwalk_browser_main_parts_android.h
CookieManger isn't used at starting crosswalk, so the datas need to be
moved early.
https://codereview.chromium.org/71583002
BUG=XWALK-7368
(cherry picked from commit 22170137e73de48c0750810f663c9d0cf484e6e9)
> [Android] Backport presented user data to Crosswalk-23

- BUILD.gn
- runtime/browser/xwalk_browser_context.cc
- runtime/browser/xwalk_browser_context.h
- runtime/browser/xwalk_special_storage_policy.cc
- runtime/browser/xwalk_special_storage_policy.h
- runtime/common/xwalk_switches.cc
- runtime/common/xwalk_switches.h
When this switch is added to the crosswalk command-line, a SpecialStoragePolicy
is enabled which allows crosswalk to use the total free space available on the
device, instead of Chromium's standard of 10% of available space.
Implementation of https://crosswalk-project.org/jira/browse/XWALK-7413
> Implement --unlimited-storage switch for crosswalk

- runtime/browser/xwalk_browser_main_parts_android.cc
SQLite Databases that are created using the window.openDatabase with
System WebVieware not accessible in Crosswalk, the databases need to
be moved to Crosswalk profile directory.
BUG=XWALK-7368 XWALK-4488
(cherry picked from commit 136cf6e6b6ffdaa308326366f5096e0853fd007b)
> [Android] Back port the feature of preserving websql databases to Crosswalk 23

- runtime/browser/runtime_url_request_context_getter.cc
Chromium started enforcing some Certificate Transparency policies by default
in M53, and refuses to load certain websites when the CT verification fails
while establishing the TLS connection; this affected Crosswalk because we
were using the default CT verifier and policy enforcer, but we did not add
any of the logs approved by the Chromium project (see
net/cert/ct_known_logs_static-inc.h).
Instead of doing so, stop requiring websites to pass Chromium's Certificate
Transparency checks altogether after getting some clarification from
upstream. The biggest impediment to us following Chromium's policy is that
Crosswalk's release cycle would need to match Chromium's very closely to
avoid two risks:
1) Chromium approves new CT logs, they start being used in new certificates,
Crosswalk does not …
> crosswalk-23: Stop enforcing Certificate Transparency verification

- runtime/common/xwalk_runtime_features.cc
features will just be marked as experimental so they can be enabled via a command line option instead of completely disabling them.
BUG=XWALK-7461
> If building with DISABLE_BUNDLED_EXTENSIONS

- runtime/android/core/src/org/xwalk/core/XWalkEnvironment.java
Error happened when user clicks Get Crosswalk button on Crosswalk dialog.
> Fix: Unexpected os.arch: armv8l

- tools/fetch_deps.py
As per
https://groups.google.com/a/chromium.org/d/msg/infra-dev/Cwc6jsitAEA/Dwy3xweSAAAJ,
gclient has recently started validating the syntax of DEPS files.
This is a problem for us because src/xwalk/buildtools, which we fetch from
upstream, is at a revision that does not pass gclient's validation and
breaks the checkout process.
For now, just disable syntax validation to get things back to where they
were before.
BUG=XWALK-7528
> tools: Disable gclient syntax validation when fetching dependencies.
