crosswalk-project/crosswalk

- build/android/xwalkcore_library_template/project.properties
Require android-21 to compile to avoid build error.
BUG=https://crosswalk-project.org/jira/browse/XWALK-3238
> [Android] Update project.properties for xwalk core library

- runtime/browser/xwalk_browser_context.cc
- runtime/browser/xwalk_browser_context.h
- runtime/browser/xwalk_ssl_host_state_delegate.cc
- runtime/browser/xwalk_ssl_host_state_delegate.h
- xwalk.gyp
Fix bug XWALK-2498, Ssl Certification Error Alert.
> Fix bug XWALK-2498, Ssl Certification Error Alert

- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkCoreExtensionBridge.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkExtensionClient.java
> [Android] Expose entry points in XWalkExtensionClient class

- application/browser/application_system_tizen.cc
Pass only positional arguments to appcore (aul parameters).
Skip chromium flags.
Library libbundle expects even number of positional arguments is form:
__AUL_KEY__ __BASE64_VALUE__ [and so on...]
It crashes for odd number of parameters.
Passing chromium flags may results in parsing it wrong by appcore.
BUG=XWALK-3350
> [Tizen] Skip passing chromium flags to appcore_init

- xwalk_lzma.gypi
@halton please help review, thanks
> [Crosswalk-Mini][Android] add compressed library dependency

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/SetUserAgentStringTest.java
Implement API XWalkView.setUserAgentString for client to set it's own user agent.
BUG=XWALK-3306
> [Android] Implement XWalkView.setUserAgentString

- application/common/application_file_util.cc
Problem:    Whitespaces in some nodes and attributes values should be removed.
Solution:   Collapse and trim whitespaces at selected strings.
Links to specification:
http://www.w3.org/TR/widgets/#rule-for-getting-text-content-with-normalized-white-space-0
http://www.w3.org/TR/widgets/#rule-for-getting-a-single-attribute-value-0
BUG=XWALK-2775
> [Tizen] Fixed the parsing of widget manifest

- app/tools/android/make_apk.py
Need move compressed library into native_libs before packaging.
@halton @wang16 please help review, thanks!
> [Crosswalk-Mini][Android] Move libxwalkcore.so.$arch into native_libs

- DEPS.xwalk
5c5fbba Merge pull request #77 from huningxin/xwalk-3370
5574b6f Merge pull request #79 from huningxin/xwalk-3371-xwalk-11
e1840aa [SIMD.js] Optimize Emscripten generated load and store API
e575267 [SIMD.js] Add smi check in bounds check of SIMD load and store API
> Roll v8-crosswalk (11bb7b4 -> 5c5fbba)

- DEPS.xwalk
> DEPS.xwalk: Roll chromium-crosswalk (13ee6cc -> bfb8dc3).

- DEPS.xwalk
This is the latest stable release
> crosswalk-11: Roll Chromium 40.0.2214.91

- DEPS.xwalk
7260dea Merge pull request #229 from huningxin/fix_xwalk_3344
61ae689 Allow universal access from file if flag is set and url is file scheme.
> DEPS.xwalk: Roll chromium-crosswalk (bfb8dc3 -> 7260dea).

- DEPS.xwalk
178d7d3 Merge pull request #230 from huningxin/crosswalk-10
92bd952 Allow universal access from file if flag is set and url is file scheme.
> DEPS.xwalk: Roll chromium-crosswalk (9b9f7b6 -> 178d7d3)

- DEPS.xwalk
9a9776f Merge pull request #231 from huningxin/crosswalk-11
1fd40ce Allow universal access from file if flag is set and url is file scheme.
> DEPS.xwalk: Roll chromium-crosswalk (ed0646f -> 9a9776f)

- DEPS.xwalk
1a9e0ff Merge pull request #76 from huningxin/xwalk-3371
044b02d [SIMD.js] Optimize Emscripten generated load and store API
f9f8dea Merge pull request #73 from huningxin/xwalk-3117
2fcc9f4 Merge pull request #74 from huningxin/xwalk-3116
964fd50 Merge pull request #75 from huningxin/xwalk-3370
34ba798 [SIMD.js] Add smi check in bounds check of SIMD load and store API
0633aa5 [SIMD.js] Implement swizzle and shuffle APIs
61c20fc [SIMD.js] Rename the shift operations to include "ByScalar"
> DEPS.xwalk: Roll v8-crosswalk (11bb7b4 -> 1a9e0ff).

- application/extension/application_widget_api.js
- application/extension/application_widget_extension.cc
> Expose Widget interface object constructor

- application/common/tizen/signature_parser.cc
The value of URI attribute of signature files can be url encoded string.
But, SignatureValidator can't recongize url encoded 'uri' of signatures.
Add url decoding routine to SignatureParser.
BUG=XWALK-3479
> [Tizen] Add url decoding for 'uri' attribute of signatures

- DEPS.xwalk
- tizen/browser/media/media_webcontents_observer.cc
- tizen/browser/media/media_webcontents_observer.h
- tizen/renderer/media/mediaplayer_impl.cc
- tizen/renderer/media/mediaplayer_impl.h
Rebase Murphy support to M41 and fix build failures.
BUG=XWALK-3418
> [Tizen] Rebase Murphy support to M41.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
setBackgroundColor doesn't work before page loaded. This fix enabled setBackgroundColor for XWalkView.
BUG=XWALK-1910
> [Android] Fix issue with XWalkView::setBackgroundColor

- DEPS.xwalk
f9d87a6 [Android] WebCL support for Crosswalk.
> DEPS.xwalk: Roll blink-crosswalk (d79eb73 -> f9d87a6).

- DEPS.xwalk
This is the recent beta update
> Roll Chromium 41.0.2272.35

- DEPS.xwalk
b394589 [SIMD.js] Fix performance regression of mandelbrot benchmark
> DEPS.xwalk: Roll v8-crosswalk (ba5299d -> b394589)

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
Enable transparent XWalkView. Use XWalkView.setBackgroundColor(0) for transparent
BUG=XWALK-3308
> [Android] Enable transparent XWalkView

- DEPS.xwalk
921e4ad [Android] Fix WebCL fail to run on PowerVR GPU.
> DEPS.xwalk: Roll blink-crosswalk (20dcb32 -> 921e4ad).

- DEPS.xwalk
Just sync to a more recent Linux beta version. No files needed to be
adjusted.
> Move to Chromium 41.0.2272.74.

- app/tools/android/make_apk.py
- app/tools/android/make_apk_test.py
- app/tools/android/util.py
- xwalk.gyp
> [Android] Enable ARM 64-bit support for Crosswalk

- runtime/common/xwalk_runtime_features.cc
Code has been removed in 0c870aa13a139d93cf7e1e61e95097249156f733
> Remove dead experimental options.

- experimental/native_file_system/native_file_system_extension.cc
- experimental/native_file_system/virtual_root_provider.h
- experimental/native_file_system/virtual_root_provider_linux.cc
- experimental/native_file_system/virtual_root_provider_win.cc
- Get the folders from Windows APIs if they exists.
- Fixed few spelling errors when going through the code.
> Make native filesystem extension work on Windows.

- runtime/app/android/xwalk_entry_point.cc
- xwalk_android.gypi
1. Fix the missing include for mojo
2. Get rid of OnJNIOnload and OnLoadDelegate as per,
https://codereview.chromium.org/935413004
> Final round of Android build fixes

- DEPS.xwalk
b087d60 Merge pull request #245 from shaochangbin/fix-shared-build
71e30a3 Fix issue of build error for media shared library.
70df207 Merge pull request #244 from shaochangbin/proprietary-codec
672d42f Add the command line option to load proprietary codec library.
> DEPS.xwalk: Roll chromium-crosswalk (903b90a -> b087d60).

- runtime/android/core_shell/src/org/xwalk/core/xwview/shell/XWalkViewShellActivity.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/NavigateTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnLoadFinishedTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/TestHelperBridge.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
Fix the display for website's title after navigation and refine test case for getting title.
> [Android] Fix the display for the website's title after navigation.

- DEPS.xwalk
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnRequestFocusTest.java
also marked OnRequestFocusTest flaky because bug=XWALK-3863
> rebase to chromium 42.0.2311.68

- DEPS.xwalk
This is the latest M41 stable, released 2015-04-01.
> crosswalk-12: Roll Chromium 41.0.2272.118.

- application/browser/application_system.cc
- extensions/renderer/xwalk_module_system.cc
- extensions/test/data/cross_contexts_reference.html
- extensions/test/extension_in_iframe.cc
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkPreferencesInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettings.java
- runtime/android/sample/src/org/xwalk/core/sample/OnCreateWindowRequestedActivity.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnCreateWindowRequestedTest.java
Back port changes for BUG=https://crosswalk-project.org/jira/browse/XWALK-3575
> Back port changes for XWALK-3575 to Crosswalk 13

- application/browser/application_system.cc
- extensions/renderer/xwalk_module_system.cc
- extensions/test/data/cross_contexts_reference.html
- extensions/test/extension_in_iframe.cc
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkPreferencesInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettings.java
- runtime/android/sample/src/org/xwalk/core/sample/OnCreateWindowRequestedActivity.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnCreateWindowRequestedTest.java
Back port changes for BUG=https://crosswalk-project.org/jira/browse/XWALK-3575
> Back port changes for XWALK-3575 to Crosswalk 12

- runtime/android/core_internal/src/org/xwalk/core/internal/extension/api/contacts/ContactConstants.java
- runtime/android/core_internal/src/org/xwalk/core/internal/extension/api/contacts/ContactFinder.java
Correct the function name mapping, and check if  contacts list is empty.
BUG=XWALK-2451
> [Android] Fix failed to query contacts with "is" filter.

- app/OWNERS
- build/android/OWNERS
- runtime/android/OWNERS
- runtime/app/android/OWNERS
- runtime/browser/android/OWNERS
- runtime/common/android/OWNERS
- runtime/renderer/android/OWNERS
- test/android/OWNERS
Including 8 'OWNERS' files for android related sub folders.
> [Android] Add Halton and SunLin as owner for Android port

- DEPS.xwalk
dbc79b4 Merge pull request #97 from huningxin/simd-m43
3947dbf [SIMD.js] Optimize SIMD operations by CrankShaft
259436a Merge pull request #98 from rakuco/presubmit-xdk-fix
bee6196 XDK: Fix coding style for presubmit checks to pass.
4dfa981 [SIMD.js] Add SIMD128 types and operations
> DEPS.xwalk: Roll v8-crosswalk (0da5476 -> dbc79b4)

- runtime/browser/xwalk_browser_main_parts.cc
> Re-enable SIMD.js after M43 rebasing.

- runtime/browser/runtime_url_request_context_getter.cc
- runtime/common/xwalk_switches.cc
- runtime/common/xwalk_switches.h
Use the command line of "--disk-cache-size=1" to disable the disk cache.
(cherry picked from commit bdd1bd4bfc477dc7e0955790bf00200e72989950)
> [Android] Support disable disk cache

- build/common.gypi
- runtime/browser/runtime.cc
- runtime/browser/runtime_file_select_helper.cc
- runtime/browser/ui/browser_dialogs.h
- runtime/browser/ui/linux_webui/linux_webui.cc
- runtime/browser/ui/linux_webui/linux_webui.h
- runtime/browser/ui/linux_webui/select_file_dialog_impl_webui.cc
- runtime/browser/ui/linux_webui/select_file_dialog_impl_webui.h
- runtime/browser/ui/webui/file_picker/file_picker_ui.cc
- runtime/browser/ui/webui/file_picker/file_picker_ui.h
- runtime/browser/ui/webui/file_picker/file_picker_web_dialog.cc
- runtime/browser/ui/webui/file_picker/file_picker_web_dialog.h
- runtime/browser/ui/webui/xwalk_web_contents_handler.cc
- runtime/browser/ui/webui/xwalk_web_contents_handler.h
- runtime/browser/ui/webui/xwalk_web_ui_controller_factory.cc
- runtime/browser/ui/webui/xwalk_web_ui_controller_factory.h
- runtime/browser/ui/xwalk_web_dialog_view.cc
- runtime/browser/xwalk_browser_main_parts.cc
- runtime/browser/xwalk_browser_main_parts.h
- runtime/common/url_constants.cc
- runtime/common/url_constants.h
- runtime/resources/file_picker/file_picker.css
- runtime/resources/file_picker/file_picker.html
- runtime/resources/file_picker/file_picker.js
- runtime/resources/xwalk_resources.grd
- xwalk.gyp
> Add support for file-picker using WebUI

- application/browser/application.cc
- application/test/application_test.cc
- application/test/data/unsafe_start_URL/manifest.json
- application/test/data/web_start_URL/manifest.json
Before this change "start_url" filed only support local relative URL,
after this it will also support http/https web URLs
BUG=XWALK-3656
> Add manifest "start_url" field support for web URL.

- DEPS.xwalk
Fix debug build failure in runtime about XWALK-3517 and XWALK-3780
> DEPS.xwalk: Roll v8-crosswalk(f08c04f->108d89f)

- DEPS.xwalk
* b462d6f Gardening: adapt to https://codereview.chromium.org/1073573002
> DEPS.xwalk: Roll ozone-wayland (852cf10 -> b462d6f)

- third_party/lzma_sdk/download_lzma_sdk.py
Python code was using 'file' and 'tar' commands. These are not
available on Windows, we should use the Python classes instead.
> Fix build on Windows in relation of lzma.

- DEPS.xwalk
v8 blink and chromium can be found from my repos
> roll chromium 43.0.2357.52

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
This patch is to fix the filepicker crash issue on some customized ROMs.
In some ROMs, "/sdcard/Pictures" was removed, verify this directory
before create image file.
BUG=XWALK-3983
> [Android] Fix filepicker crash issue.

- resources/resource_ids
- runtime/app/xwalk_main_delegate.cc
- runtime/browser/ui/native_app_window_desktop.cc
- runtime/resources/locale/xwalk_strings_zh-CN.xtb
- runtime/resources/xwalk_resources.grd
- runtime/resources/xwalk_strings.grd
- xwalk.gyp
The xwalk_strings could also be used by other string localization usages.
> [Linux] Add locale support for minimal-ui buttons.

- DEPS.xwalk
7fb4d1c : Fix build on Windows 64 bits.
> DEPS.xwalk: Roll v8-crosswalk (41033a7 -> 6e8e484)

- runtime/browser/devtools/xwalk_devtools_delegate.cc
The Web UI doesn't have favicon, so don't need to show it in front-end.
And the reason of crash is that the delegate of 'WebContents' related with 'File Picker' is 'WeDialogView' rather than 'Runtime', so 'static_cast&lt;Runtime*&gt;' in 'GetFaviconDataURL' will cause problem.
With this patch the 'File Picker' can be debugged, like attached figure shows.
BUG=https://crosswalk-project.org/jira/browse/XWALK-4185
> [Linux] Crash when remote debugging with Web UI

- xwalk_core_library_android.gypi
This patch is to fix the error when generating Javadoc for embedding API
> [Android] Fix Javadoc error

- DEPS.xwalk
release. It contains some security fixes.
http://googlechromereleases.blogspot.com/2015/05/stable-channel-update_19.html
Thanks for rakuco for guiding through this
> Move to Chromium 43.0.2357.65, first stable M43

- DEPS.xwalk
release. It contains some security fixes.
http://googlechromereleases.blogspot.com/2015/05/stable-channel-update_19.html
Thanks for rakuco for guiding through this
>  Move to Chromium 43.0.2357.65, first stable M43

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryLoader.java
- runtime/android/core/strings/xwalk_app_strings.grd
Improve the message and button label to make the dialogs more clearly
BUG=XWALK-4220
> [Android] Normalizing the dialogs about the Crosswalk Project runtime

- app/tools/android/make_apk.py
fix the path issue in Crosswalk Lite
> Fix the path issue in make_apk.py

- runtime/browser/ui/native_app_window_desktop.cc
Remove redundant AddChildView call.
BUG=XWALK-4301
> Fix DCHECK failure on desktop minimal-UI.

- runtime/browser/runtime_ui_delegate.cc
So that minimal-ui controls actually work.
> [Windows] Use RuntimeUIDelegateDesktop

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkInitializer.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
The samples illustrate how to use XWalkActivity/XWalkInitializer to
work with the Crosswalk Project runtime.
> [Android] Add samples for new embedding API

- app/android/runtime_client/src/org/xwalk/app/runtime/extension/JsApi.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/JsCallback.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/JsStubGenerator.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/ReflectionHelper.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkExtensionClient.java
- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkRuntimeExtensionManager.java
- app/tools/android/customize.py
- app/tools/android/test_data/entry/echo-jsStub-generation.html
- app/tools/android/test_data/extensions/echoJsStubGenExtension/echoJsStubGenExtension.json
- app/tools/android/test_data/extensions/echoJsStubGenExtension/src/com/example/jsStub/Echo.java
- extensions/extensions_resources.grd
- extensions/renderer/xwalk_extension_renderer_controller.cc
- extensions/renderer/xwalk_js_stub_wrapper.js
- xwalk_android_app.gypi
Feature implementation and test case.
JIRA issue: https://crosswalk-project.org/jira/browse/XWALK-3969
> [Android] auto-generating js-stub based on annotations

- DEPS.xwalk
* dba41d8 Merge pull request #252 from fujunwei/local-storage
* 256bc7c localStorage: Aggressively flush to disk for Android WebView.
Required for actually making commit b2ce402 ("[Android] Aggressively
flush to disk") work.
> DEPS.xwalk: Roll chromium-crosswalk (fe59dbc -> dba41d8).

- DEPS.xwalk
- runtime/browser/xwalk_browser_main_parts.cc
> DEPS.xwalk: Roll v8-crosswalk(54dc21->efee9f)

- DEPS.xwalk
410929b Merge pull request #60 from hujiajie/webcl-4481
21fe2cf [Android] Fix an error in extracting WebCL kernel parameter list.
> DEPS.xwalk: Roll blink-crosswalk(0ffa650 -> 410929b)

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkCookieManagerInternal.java
- runtime/browser/android/cookie_manager.cc
- test/android/core/javatests/src/org/xwalk/core/xwview/test/CookieManagerTest.java
- tools/reflection_generator/reflection_generator.py
- xwalk_android.gypi
Crosswalk cordova plugin need this class to provide ability of accessing cookie in shared mode. Change the name of XWalkCookieManager to XWalkCookieManagerInternal for generating wrapper and bridge of the class.
> [Android] Export XWalkCookieManager

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkActivityDelegate.java
- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/XWalkDialogManager.java
- runtime/android/core/src/org/xwalk/core/XWalkInitializer.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryInterface.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryLoader.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkAPI.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- runtime/android/core_shell/src/org/xwalk/core/xwview/shell/XWalkViewShellActivity.java
- tools/reflection_generator/java_method.py
* Fixed crash when initializing embedded mode by default
* Fixed crash when launching XWalkCoreShell under lite mode
* Support setUIClient and setResourceClient before Crosswalk runtime
is ready
* Associate XWalkInitializer and XWalkUpdater to each single activity
BUG=XWALK-4072, XWALK-4388, XWALK-4503
> [Android] Fixed crash errors of shared mode

- runtime/android/core/src/org/xwalk/core/XWalkDialogManager.java
- runtime/android/core/strings/xwalk_app_strings.grd
Prompt the user explicitly to restart the app after installed the
Crosswalk Project runtime.
> [Android] Improve the prompt message of shared mode

- runtime/browser/ui/native_app_window_desktop.cc
- runtime/common/xwalk_runtime_features.cc
> Fix Coverity failure caused uninitialized class member.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkCookieManagerInternal.java
- runtime/browser/android/cookie_manager.cc
- test/android/core/javatests/src/org/xwalk/core/xwview/test/CookieManagerTest.java
- tools/reflection_generator/reflection_generator.py
- xwalk_android.gypi
Expose XWalkCookieManager to developer, Change the name of XWalkCookieManager
to XWalkCookieManagerInternal for generating wrapper and bridge of the class.
(cherry picked from commit c5504aa8376b80fd51877815ec69e85679f91ec7)
> [Android] Backport to export XWalkCookieManager

- runtime/browser/xwalk_browser_main_parts_android.cc
Copy the data of web storage directory to Crosswalk profile name for
Android Kitkat.
The KK webview and the pre-KK webview use different formate to store data,
but the storage database have implemented the mechanism that it will be upgraded
to V2(BLOB value column) if there was V1 (TEXT value column) database already.
BUG=XWALK-4349
> Preserve local storage when migrating from webview to Crosswalk

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkDownloadListenerImpl.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/DownloadListenerTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
This patch is to add the user agent to request header for download.
Modify test case to verify the identical with setting.
BUG=XWALK-4625
> [Android] Add the request header for download.

- build/android/generate_xwalk_core_library.py
- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkActivityDelegate.java
- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/XWalkInitializer.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryDecompressor.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryLoader.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkPreferencesInternal.java
- tools/reflection_generator/java_method.py
- tools/reflection_generator/wrapper_generator.py
- xwalk_core_library_android.gypi
Now the developrs can call XWalkPreferences.setValue() before the
Crosswalk Runtime is installed in shared mode.
> [Android] Support reserving static method before xwalk is ready

- build/common.gypi
- runtime/app/android/xwalk_jni_registrar.cc
- runtime/browser/xwalk_content_browser_client.cc
- runtime/browser/xwalk_runner.cc
- runtime/browser/xwalk_runner.h
- xwalk.gyp
- xwalk_android.gypi
Build with flag '-Ddisable_devtools=1' to turn on the switch.
> Add a swtich to exclude code of devtools

- DEPS.xwalk
- application/browser/application_protocols.cc
- sysapps/raw_socket/tcp_socket_object.cc
- sysapps/raw_socket/udp_socket_object.cc
> Move to Chromium 44.0.2403.107.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkDownloadListenerImpl.java
Do not get resources in the constructor of XWalkDownloadListenerImpl.
BUG=XWALK-4711
> [Android] Fixed crash error of XWalkRuntimeClientShell

- app/android/runtime_client_shell/res/raw/contacts_api.js
- app/android/runtime_client_shell/res/raw/device_capabilities_api.js
- app/android/runtime_client_shell/res/raw/messaging_api.js
- app/android/runtime_client_shell/res/raw/presentation_api.js
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkUIClientInternal.java
Added the api related javascripts to the apk of XWalkRuntimeClientShell
BUG=XWALK-4711
> [Android] Fixed test error or XWalkRuntimeClient

- runtime/browser/runtime_download_manager_delegate.cc
Use desktop's default downloand manner to download the item
> [Linux]Add download support

- DEPS.xwalk
855241 [Backport] Remove NOTIMPLEMENTED() logspam on Android clipboard actions.
BUG=XWALK-4608
> DEPS.xwalk: Roll chromium-crosswalk (1021d6->855241)

- DEPS.xwalk
Not needed anymore because same commit come by default.
> Remove terporary ffmped roll

- DEPS.xwalk
cd38a1 : Fix build on Windows when using components build.
> DEPS.xwalk: Roll chromium-crosswalk (6e988a->97959a)

- DEPS.xwalk
59d6385 Merge pull request #54 from hujiajie/webcl
db2095f [Android] Use RefPtr to ref the associated WebCLContext in WebCLObject.
> DEPS.xwalk: Roll blink-crosswalk(0afa83e -> 59d6385)

- extensions/common/xwalk_external_adapter.cc
- extensions/common/xwalk_external_adapter.h
- extensions/common/xwalk_external_extension.cc
- extensions/common/xwalk_external_extension.h
- extensions/common/xwalk_external_instance.cc
- extensions/common/xwalk_external_instance.h
- extensions/extensions.gyp
- extensions/external_extension_sample.gyp
- extensions/public/XW_Extension_Message_2.h
- extensions/test/data/echo_messaging_2.html
- extensions/test/echo_extension_messaging_2.c
- extensions/test/external_extension.cc
XW_MessagingInterface_2 adds the binary message support.
BUG=XWALK-4615
TEST=xwalk_extensions_browsertest
--gtest_filter=ExternalExtensionTest.ExternalExtensionMessaging2
> Add XW_MessagingInterface_2

- DEPS.xwalk
* b699def Merge pull request #70 from rakuco/webcl-move-webclexception-to-core
* e6ccb69 WebCL: Move WebCLException to core/webcl.
> DEPS.xwalk: Roll blink-crosswalk (59d6385 -> b699def).

- build/common.gypi
- gyp_xwalk
With flag "-Ddisable_web_video=1" the size is reduced by 180K.
> To disable WebVideo

- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
Fixed the error that only last setValue works when calling setValue
multiple times before xwalk is ready.
BUG=XWALK-4868
> [Android] Fixed XWalkPreference error before xwalk is ready

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkLaunchScreenManager.java
> [Android] Refine the code style.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkLaunchScreenManager.java
Press the back key continually when launches application, sometimes it
will lead to crash with null pointer.
BUG=XWALK-4778
> [Android] Fix the null pointer issue.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
This patch will case application crash when using XWalkActivity,
revert it temporarily for a better solution.
This reverts commit f8cb0458c9a59cc5658fd0907a9887ba1ecb9978.
> Revert "[Android] Add method to config XWalkView render backend"

- app/tools/android/test_data/entry/echo-jsStub-generation.html
Update the entry file for sample echo extension using js-stub generation.
> [Android] Update the entry file for sample echo extension

- DEPS.xwalk
> Update 'blink_crosswalk_rev' in DEPS.xwalk to 5ffd3f8

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkCookieManagerInternal.java
- xwalk_core_library_android.gypi
Document the API doc for XWalkCookieManager.
BUG=XWALK-3571
> Encode the data by base64 to load that as a data: URL

- app/android/app_template/res/values-v14/theme.xml
- app/android/app_template/src/org/xwalk/app/template/AppTemplateActivity.java
- app/android/runtime_activity/src/org/xwalk/app/XWalkRuntimeActivityBase.java
- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkCookieManagerInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- xwalk_core_library_android.gypi
2 commits are to fix the critical bug XWALK-4966. Another 2 commits are to update the API doc.
> Port the update about shared mode from master

- app/android/runtime_client_shell/res/raw/presentation_api.js
- test/android/data/displayAvailableTest.html
- test/android/data/remote.html
Override displayAvailableTest.html and add remote.html 
Change presentation_api.js  in app/android/runtime_client_shell/res/raw/
> Test case for Presentation API

- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/ExtensionEchoInternal.java
- test/android/data/echo_binary_java.html
> [Android] Fix Binary Message Interface instrumentation tests

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/UserAgentTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
Implement API XWalkView.getUserAgentString for client to get its user agent.
Refine test cases for setUserAgentString and getUserAgentString.
BUG=XWALK-4817,XWALK-4918
> [Android] Implement XWalkView.getUserAgentString and test case

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentView.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
rename onPerformLongClick to performLongClickDelegate for better naming and reformat the style.
> [Android] Refine the naming for better understanding

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettings.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- runtime/browser/android/xwalk_settings.cc
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnScaleChangedTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/SetInitialScaleTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/TestHelperBridge.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
This patch is to implement the embedding api for setInitialScale().
Add test case for setInitialScale().
BUG=XWALK-4304, XWALK-4365
> [Android] Implement the setInitialScale() API.

- DEPS.xwalk
- build/common.gypi
- gyp_xwalk
- runtime/browser/android/xwalk_contents_client_bridge.cc
Building with "-Ddisable_notifications=1" reduces size by 68K.
> To disable WebNotification for Crosswalk for Android

- DEPS.xwalk
e80d13b Merge pull request #115 from chuan9/XWALK-4766
7997cb4 Change type name from all lower case to first Character upper case in CrankShaft BUG=XWALK-4766
33446a9 Change type name from all lower case to first Character upper case in runtime BUG=XWALK-4766
BUG=XWALK-4766
> DEPS.xwalk: Roll v8-crosswalk (c1479b9->e80d13b).

- runtime/android/core/src/org/xwalk/core/XWalkLibraryLoader.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
This reverts commit dbab22de26da9649be62c400a8d00249729dab8b.
> Revert "[Android] Experimental silent download mode"

- DEPS.xwalk
f144986 Merge pull request #116 from huningxin/fix_arm64
8b30298 [SIMD.js] Fix the ARM64 and MIPS build after M45 rebasing
> DEPS.xwalk: Roll v8-crosswalk (e80d13b -> f144986)

- runtime/browser/runtime_url_request_context_getter.cc
Crosswalk does not work with the Proxy Auto-Config setting set.  There is some changes from https://codereview.chromium.org/742023003 that need to be applied to Crosswalk.  I have verified this change against a Nexus 7 (5.1.1) that has my corporate PAC set.  I also checked with a Nexus 5 (4.4.4)  that has a manual proxy set still works.
BUG=XWALK-5094
> [Android] PAC does not work with Crosswalk

- gyp_xwalk
@halton @heke123 
Enable thoese features as the demand of customers. Please help to merge so I can roll the DEPS.xwalk forward.
> Enable WebAudio and WebVideo by default.

- DEPS.xwalk
Chromium-Crosswalk:
f419e35e720cf43fd20dba71fbe39cfc8e401949
Make the <video> unknown for WebKit if WebVideo disabled
> Roll DEPS.xwalk

- app/android/runtime_client/src/org/xwalk/app/runtime/extension/XWalkRuntimeExtensionManager.java
Use correct method to get native library path.
BUG=XWALK-5219
> [Android][64-bit] Fix launching app crash.

- build/common.gypi
- gyp_xwalk
Reduced size = 230K
The pair patches are 
https://github.com/crosswalk-project/chromium-crosswalk/pull/288
and 
https://github.com/crosswalk-project/blink-crosswalk/pull/85
> To disable Indexed DB

- runtime/app/xwalk_main.cc
We need to make sure to mark the process as "DPI aware".
BUG=XWALK-5170
> Fix blurry rendering on high DPI screens.

- DEPS.xwalk
- build/common.gypi
- gyp_xwalk
This feature is about supporting disabled people, such as reading screen.
Since it's pretty independent in code, so it's harmless for the stability of code to disable it.
Reduced size = 72K
> To disable Accessibility support

- build/common.gypi
- gyp_xwalk
Reduce 26K with LZMA on,  add flag DISABLE_GEO_FEATURES
> [lite] disable geolocation and geofencing.

- app/tools/android/app_info.py
- app/tools/android/customize.py
- app/tools/android/make_apk.py
Insert meta-data in AndroidManifest to make web app running in
silent download mode.
> [Android] Add download mode support in web app packaging

- build/common.gypi
- gyp_xwalk
> [Lite] To disable Web Bluetooth

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkAPI.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- runtime/android/sample/AndroidManifest.xml
- runtime/android/sample/src/org/xwalk/core/sample/MultiXWalkViewOverlayActivity.java
- tools/reflection_generator/java_method.py
When multiple XWalkViews were set to overlay,
XWalkView.setVisibility(View.INVISIBLE) does not work, that is current
XWalkView was always showing. This patch is to fix this issue.
For the usage, please refer to the
sample:MultiXWalkViewOverlayActivity.java.
BUG=XWALK-5064
> [Android] Fix the display with overlayed multiple XWalkViews.

- build/common.gypi
- gyp_xwalk
38K binary size reduced.  
Add flag 'disable_webdatabase'
> [Lite] Disable WebDatabase.

- build/common.gypi
- gyp_xwalk
26K binary size reduced, add flag disable_webmidi
> [Lite] Disable webmidi

- app/android/app_template/AndroidManifest.xml
- app/android/runtime_client_embedded_shell/AndroidManifest.xml
- app/android/runtime_client_shell/AndroidManifest.xml
- app/tools/android/handle_permissions.py
- app/tools/android/make_apk_test.py
- build/android/generate_xwalk_core_library.py
- experimental/wifidirect/OWNERS
- experimental/wifidirect/wifidirect_api.js
- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
- runtime/android/core_internal/src/org/xwalk/core/internal/extension/BuiltinXWalkExtensions.java
- runtime/android/core_internal/src/org/xwalk/core/internal/extension/api/wifidirect/WifiDirect.java
- runtime/android/core_shell/AndroidManifest.xml
- xwalk_android.gypi
- xwalk_android_tests.gypi
First implementation supports Android. Windows support under work.
Manual test ready to be deployed to crowwsalk-test-suite/usecase
Mock test to be developed after and contributed here - added entries to test gyp files.
> Wifi Direct Experimental API initial contribution

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettings.java
- runtime/browser/android/xwalk_settings.cc
> [Android] Respect the system setting for password echoing.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettings.java
- runtime/browser/android/xwalk_settings.cc
BUG=XWALK-4298
(cherry picked from commit 7fd41ef72e1b7c5b624ecbf6b577e1ce1e713cc5)
> [Android] Backport patch to respect the system setting for password echoing.

- app/tools/android/test_data/extensions/contactextension/src/com/example/extension/ContactExtension.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryDecompressor.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/util/VideoTestWebServer.java
Close a few InputStream and Cursor instances that were currently
dangling.
> [Android] Close some leaking resources.

- app/tools/android/test_data/extensions/contactextension/src/com/example/extension/ContactExtension.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryDecompressor.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/util/VideoTestWebServer.java
Close a few InputStream and Cursor instances that were currently
dangling.
(cherry picked from commit 080e5ae90c43b3a221e4b506fc090c85621e59a4)
> crosswalk-16: [Android] Close some leaking resources.

- runtime/android/core/src/org/xwalk/core/XWalkActivityDelegate.java
Insert a meta-data named "xwalk_enable_download_mode" to AndroidManifest
to enable download mode.
Related to XWALK-5121
> [Android] Add download mode support in XWalkActivityDelegate

- app/android/runtime_client_embedded_shell/AndroidManifest.xml
- app/android/runtime_client_shell/AndroidManifest.xml
- app/tools/android/handle_permissions.py
- app/tools/android/make_apk_test.py
- build/android/generate_xwalk_core_library.py
- experimental/wifidirect/OWNERS
- experimental/wifidirect/wifidirect_api.js
- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
- runtime/android/core_internal/src/org/xwalk/core/internal/extension/BuiltinXWalkExtensions.java
- runtime/android/core_internal/src/org/xwalk/core/internal/extension/api/wifidirect/WifiDirect.java
- runtime/android/core_shell/AndroidManifest.xml
- xwalk_android.gypi
- xwalk_android_tests.gypi
…n" + fix
This reverts the revert #2c526ae Revert "Wifi Direct Experimental... " and fixes
the underlying revert issues: NullPointerException in .WifiDirect.onActivityStateChange
To make the review of this, the only change compared to original is this:
public void onActivityStateChange(Activity activity, int newState) {
+        if (mReceiver == null) {
+            return;
+        }
switch (newState) {
case ActivityState.RESUMED:
mActivity = activity;
> Wifi Direct Experimental API initial contribution second try + bugfix + permission fix

- DEPS.xwalk
- build/common.gypi
- gyp_xwalk
Flag = disable_plugins
Reduced size = 440K
> [Lite] To disable Plugin

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkResourceClientInternal.java
> [Android] Auth dialog password shown in plain text

- tools/reflection_generator/java_class.py
- tools/reflection_generator/java_method.py
Currently, reflection does not support Collection type parameter
or return value, such case happens in some API upgrade.
BUG=XWALK-5631
> [Android] Add support to Map type parameter

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- runtime/browser/android/xwalk_settings.cc
- test/android/core/javatests/src/org/xwalk/core/xwview/test/SettingsTest.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/SetAppCacheEnabledTest.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/SetDomStorageEnabledTest.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/UserAgentTest.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/XWalkViewInternalTestBase.java
- tools/reflection_generator/reflection_generator.py
- xwalk_android.gypi
- xwalk_core_library_android.gypi
Expose XWalkSettings to embedding API
BUG=XWALK-4395
> [Android] Make XWalkSettings public

- DEPS.xwalk
ae54f41 Merge pull request #119 from chuan9/4768
033fd71 Add maxNum and minNum for SIMD.Float32x4 in CrankShaft BUG=XWALK-4768
79163b6 Add maxNum and minNum for SIMD.Float32x4 in runtime BUG=XWALK-4768
8fd0061 Merge pull request #118 from chuan9/4767-runtime
a1fe099 Add replaceLane and extractLane for SIMD.Float32x4, Int32x4 and SIMD.Float64x2 in CrankShaft.
be7afe1 Add extractLane and replaceLane for SIMD.Float32x4, SIMD.Int32x4 and SIMD.Float64x2 in runtime. Remove lane property and Revise testcases.
> DEPS.xwalk: Roll v8-crosswalk(335bf02->ae54f41)

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Enable touch event intercept through onTouchListener on XWalkView by
installing the listener to ContentView.
BUG=XWALK-3888
> [Android] Enable touch event intercept through onTouchListener

- DEPS.xwalk
bbb0992 Merge pull request #122 from chuan9/v8-crosswalk16
a8139ce Add maxNum and minNum for SIMD.Float32x4 in CrankShaft BUG=XWALK-4768
8f80336 Add maxNum and minNum for SIMD.Float32x4 in runtime BUG=XWALK-4768
874891e Add replaceLane and extractLane for SIMD.Float32x4, Int32x4 and SIMD.Float64x2 in CrankShaft.
311fb3e Add extractLane and replaceLane for SIMD.Float32x4, SIMD.Int32x4 and SIMD.Float64x2 in runtime. Remove lane property and Revise testcases.
> DEPS.xwalk: Roll v8-crosswalk16(335bf02->bbb0992)

- application/browser/application.cc
- application/browser/application.h
- application/browser/application_security_policy.cc
- application/browser/application_security_policy.h
- runtime/browser/xwalk_presentation_service_delegate_win.cc
Presentation session should take into account the CSP rules applied for the parent application.
> [Windows] Presentation session security policy

- app/android/runtime_activity/src/org/xwalk/app/XWalkRuntimeActivityBase.java
Make XWalkRuntimeActivityBase use XWalkActivityDelegate directly instead
of extending from XWalkActivity and make it support download mode.
Related to XWALK-5121
> [Android] Refactor XWalkRuntimeActivityBase and make it support download mode

- DEPS.xwalk
- build/common.gypi
- gyp_xwalk
Flag = disable_mediastream
Reduced size = 30K
> [Lite] Add feature to disable Mediastream

- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
Signature check is enabled by default and it requires that the crosswalk runtime APK must be signed with the same key used in application APK signing. Developer can disable the signature check by inserting a meta-data in AndroidManifest.
Related to XWALK-5121
> [Android] Add integrity/signature check in download mode

- tools/reflection_generator/java_method.py
In reflection layer, for those callbacks from library side, if there's
no corresponding method in app side, the library will throw an exception
then the app crashes. This happens particularly when app's version is
older than library's. By this patch, it will try to invoke default
implementation in library side instead of throwing exception.
Related to XWALK-5796
> [Android] Fix crash of incompatible app

- DEPS.xwalk
326f968 Merge pull request #302 from pozdnyakov/presentation
fa04377 [Windows]Enable presentation API
> DEPS.xwalk: Roll chromium_crosswalk (3534ec8 -> 326f968)

- runtime/android/templates/XWalkAppVersion.template
- runtime/android/templates/XWalkCoreVersion.template
- tools/reflection_generator/reflection_generator.py
- xwalk_android.gypi
Add build version string to both XWalkAppVersion and XWalkCoreVersion.
This would be used to do auto update detection in download mode.
Related to XWALK-5681
> [Android] Add build version to XWalkAppVersion/XWalkCoreVersion

- runtime/browser/runtime.cc
- runtime/browser/ui/xwalk_javascript_native_dialog_factory.h
- runtime/browser/ui/xwalk_javascript_native_dialog_factory_views.cc
- runtime/browser/xwalk_browser_main_parts.cc
- xwalk.gyp
Leverage components app_modal's JavaScript modal dialog implementation.
BUG=XWALK-5819
> [Linux] Add JavaScript modal dialog

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/GetFaviconTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
Implement getFavicon API for users to get favicon on current page.
BUG=XWALK-4919
Signed-off-by: Yan, Shaobo <shaobo.yan@intel.com>
> [Android] Implement API getFavicon

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
As new shouldInterceptRequest has been implemented, the usage sample
also need to be updated.
BUG=XWALK-5956
> [Android] Update new shouldInterceptRequest usage sample

- runtime/android/core_shell/src/org/xwalk/core/xwview/test/XWalkViewTestRunnerActivity.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/ClearHistoryTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnPageFinishedTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnUpdateTitleTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/ReloadTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/SaveRestoreStateTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
- xwalk.gyp
- xwalk_android_tests.gypi
This reverts commit 608e0569c6f4270e71f5f4a1a8287e95eecae8f5
> Revert "[Android] Add test APKs for shared mode"

- DEPS.xwalk
- build/common.gypi
> [Windows] Add libpxc into DEPS.xwalk for RealSense camera support

- DEPS.xwalk
1270fb9 Merge pull request #310 from huningxin/vcd_rs_win_m48
65e5377 [Windows] M48 fixup for the Support RealSense Cameras patch
> DEPS.xwalk: Roll chromium-crosswalk (1072537 -> 1270fb9).

- DEPS.xwalk
> Roll chromium 	48.0.2564.82

- DEPS.xwalk
> Roll chromium 48.0.2564.97

- DEPS.xwalk
568e4ec Merge pull request #4 from huningxin/wm6
ba5eb7d Upgrade to 8.0.24.6528
31feceb Merge pull request #3 from halton/gn
fb93d61 Add BUILD.gn
BUG=XWALK-6227
> DEPS.xwalk: Roll libpxc (5ac4620 -> 568e4ec).

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkPreferencesInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
- runtime/browser/android/xwalk_settings.cc
- test/android/core/javatests/src/org/xwalk/core/xwview/test/SpatialNavigationTest.java
This patch is to implement the spatial navigation and provide an
embedding API for customer to enable or disable spatial navigation.
This code is ported from
https://github.com/crosswalk-project/crosswalk/pull/3378.
Author: jiangy@dsp.ac.cn
BUG=XWALK-4997, XWALK-6099
> [Android] Implement the spatial navigation.

- DEPS.xwalk
7fb34d0 Merge pull request #129 from chuan9/XWALK-4905
56ce786 [SIMD.js] Modify return type in deoptmization phase BUG=XWALK-4905
6f1c490 Merge pull request #132 from chuan9/xdk-style
246d110 XDK: Fix one presubmit style error
> DEPS.xwalk: Roll v8-crosswalk/master(28a1ef3->7fb34d0)

- DEPS.xwalk
> Roll Chromium 	48.0.2564.103

- DEPS.xwalk
> Roll 48.0.2564.103

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
The following code is allow the user to upload an image from stored files or by taking a photo using camera, but the Camcorder and Voice Recorder options should not be included.
```
<input id="file" type="file" name="file" accept="image/*">
```
BUG=XWALK-3750
> Show specail options with the accept attribute

- runtime/renderer/isolated_file_system.cc
Previous version is deprecated.
https://codereview.chromium.org/1526643002
> Use isolated version of v8::ObjectTemplate::New();

- DEPS.xwalk
> Roll 48.0.2564.109

- DEPS.xwalk
* 8e6a2d2 Merge pull request #319 from rakuco/revert-GetScreenOrientationDispatcherHost-commit
* 3b21142 Revert "Provide a ScreenOrientationDispatcherHost getter."
> DEPS.xwalk: Roll chromium-crosswalk (9a9d4c1 -> 8e6a2d2).

- DEPS.xwalk
73a16fe Merge pull request #140 from chuan9/XWALK-6279
4b838a5 [SIMD.js] Fix no defination of SIMD.Int32x4.load2
7f784b3 Merge pull request #138 from chuan9/crosswalk18/48.0.2564.109
f9cdb41 [SIMD.js] Modify return type in deoptmization phase BUG=XWALK-6278
BUG=XWALK-6279
> DEPS.xwalk: Roll v8-crosswalk(5db610c->73a16fe)

- DEPS.xwalk
> Roll 48.0.2564.116

- sysapps/sysapps_tests.gyp
- xwalk.gyp
This pull request contains several small patches that perform different
cleanups on our build system:
- Unnecessary checks in `conditions` blocks have been dropped.
- Similar checks have been coalesced into single blocks.
- Source list manipulations have been dropped where possible (i.e. when
they are already handled by `src/build/filename_rules.gypi`).
> gyp: Do some build system clean up.

- application/browser/application.cc
- application/common/application_manifest_constants.cc
- application/common/application_manifest_constants.h
- runtime/browser/runtime_platform_util.h
- runtime/browser/runtime_platform_util_android.cc
- runtime/browser/runtime_platform_util_linux.cc
- runtime/browser/runtime_platform_util_mac.mm
- runtime/browser/runtime_platform_util_win.cc
> Manifest, Windows: Support web manifest "orientation" field

- DEPS.xwalk
- 3b04582 : Screen orientation lock implementation for Windows
- 9e10775 : Page Visibility API: visibilitychange on Windows screen
lock/unlock
> DEPS.xwalk: Roll chromium-crosswalk (51665bd -> dfbc583).

- runtime/android/core_internal/src/org/xwalk/core/internal/ClientCertRequestHandlerInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/ClientCertRequestInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/OnReceivedClientCertRequestTest.java
- tools/reflection_generator/java_class.py
Add principals and KeyTypes for ClientCertRequest, provide two
APIs to get principals and key types.
Refine the test case for ClientCertRequest.
BUG=XWALK-6025
> [Android] Add two parameters for ClientCertRequest.

- runtime/android/core_internal/src/org/xwalk/core/internal/ClientCertLookupTable.java
- runtime/android/core_internal/src/org/xwalk/core/internal/ClientCertRequestHandlerInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClient.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
Adapt to https://codereview.chromium.org/1474603004.
BUG= XWALK-6492
> [Android] Replace AndroidPrivateKey with PrivateKey

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
Little change (simplification)
> Simplified XWalkContent.java

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentView.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Test case of these APIs will be covered by a sample in next PR.
BUG=XWALK-4394
> Implement computeHorizontalScrollRange related API

- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- tools/reflection_generator/bridge_generator.py
- tools/reflection_generator/code_generator.py
- tools/reflection_generator/java_method.py
- tools/reflection_generator/wrapper_generator.py
Now the Crosswalk app with shared mode can link to the prior version of
the runtime library.
> [Android] Add backward support for prior runtime library

- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/strings/xwalk_app_strings.grd
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
- tools/reflection_generator/java_method.py
Show friendly message when the runtime library is not compatible with
the CPU architecture of the device.
BUG=XWALK-6185,XWALK-6211,XWALK-6482
> [Android] Optimaze the message of shared mode

- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryInterface.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
Now the package name of the runtime library could vary by platform. The
app with shared mode can load multiple names of library.
> [Android] Shared mode supports multiple libraries

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Added new interface for XWalkView: load URL with specified HTTP headers.
BUG=XWALK-4921
> [Android] New API: Load URL with specified headers

- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/extension/XWalkExternalExtensionManagerImpl.java
- runtime/android/core/strings/xwalk_app_strings.grd
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
- tools/reflection_generator/bridge_generator.py
- tools/reflection_generator/code_generator.py
- tools/reflection_generator/java_method.py
- tools/reflection_generator/wrapper_generator.py
These commits fix the crash error when the app with shared mode running with prior version of runtime library
> Add backward support for prior runtime librar

- DEPS.xwalk
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentView.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
This PR is companied by [PR 330#](https://github.com/crosswalk-project/chromium-crosswalk/pull/330) in chromium-crosswalk.
BUG=XWALK-4871
BUG=XWALK-4894
> [Android] Enable onOverScrolled API in XWalkView. 

- DEPS.xwalk
* d18f5fd Merge pull request #148 from chuan9/bug-6736
* ef422a0 [SIMD.js] Fix no defination of SIMD.Int32x4.load2
* 7a5f344 Merge pull request #145 from chuan9/bug-6662
* 47cfd15 Add fake condition to deopt in opcode, move Deoptimize out to trigger this function in any case to set the environment used to avoid check failed.
BUG=XWALK-6272
BUG=XWALK-6736
RELATED BUG=XWALK-6662
> DEPS.xwalk: Roll v8-crosswalk (476c08e -> d18f5fd)

- DEPS.xwalk
* 9fad95a Merge pull request #342 from pozdnyakov/XWALK-6703
* b6065a8 Fix calling of AudioOutputStream::AudioSourceCallback API
BUG=XWALK-6703
> DEPS.xwalk: Roll chromium-crosswalk (58a9a9f -> 9fad95a)

- gyp_xwalk
Geolocation function is very popular, Re-enable it.
BUG=XWALK-6785
> Re-enable geolocation&geofencing API..

- runtime/browser/runtime_download_manager_delegate.cc
Chromium's coding style (as well as Google's) says using `wstring` is
frowned upon for multiple reasons. There is even a check in Chromium's
main `PRESUBMIT.py` that prevents new `wstring`s from being added in
crosswalk-platform code.
The only use was in code copied from content_shell in
2013 (`RuntimeDownloadManagerDelegate::ChooseDownloadPath()`), which
could be rewritten using only `base::FilePath`s and Chromium's
`OPENFILENAME` wrapper class. In any case, Crosswalk on Windows still
does not support downloads so the change cannot break anything (even
though I have verified it does build).
This change is another step towards enabling more PRESUBMIT checks for
our code.
> Stop using std::wstring in our code.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/GetContentHeightTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
Implement getContentHeight API for sync invoking to get content height.
BUG=XWALK-6521
> [Android] Implement getContentHeight API.

- CONTRIBUTING.md
- RELEASENOTES.md
This PR adds the full Crosswalk release notes (up to Crosswalk 19) to the source tree. Once this is merged, the process to update the release notes going forward would be something like:
- Anybody who submits new features is welcome and encouraged to add a description to the release notes in the same PR that implements the feature
- Latest before branching to beta the release notes are updated to reflect the content up to that point (my responsibility)
- Any notable bug fixes or changes done in the beta branch are updated in the branched release notes
The above will be communicated on crosswalk-dev once this PR is merged.
This first submission is huge because it includes all the release notes starting from Crosswalk 1 (collecting them was a nice trip down Memory Lane). That partly …
> Add release notes

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Implement overScrollBy API for XWalkView.
BUG=XWALK-4894
> [Android] Implement overScrollBy API.

- OWNERS
I've been proposed as a top-level owner in the crosswalk-owners mailing
list. Thankfully the other owners agree, so I'm fulfilling the
collective wish now.
> Add myself to the top-level OWNERS file.

- runtime/browser/android/xwalk_contents_client_bridge.cc
- runtime/browser/android/xwalk_dev_tools_server.cc
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/GeolocationPermissionTest.java
Fix test cases, as follows:
WebNotificationTest.*
GeolocationPermissionTest.*
EnableRemoteDebuggingTest.testEnableRemoteDebugging
BUG=XWALK-6857
> M50: Fix the failed test case.

- gyp_xwalk
enable-xxx flags can be added to GYP_DEFINES to control
which feature is enabled.
@halton @heke123 @PeterWangIntel
> [Lite] support enable-xxx flags defined in GYP_DEFINES

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkDialogManager.java
- runtime/android/core/src/org/xwalk/core/XWalkInitializer.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
Add more samples and more detailed description.
> [Android] Refine the class description of embedding API

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkActivityDelegate.java
Reverts crosswalk-project/crosswalk#3725
> Revert "[Android] Change the inteface for setting dialog manager"

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/GetCompositingSurfaceTypeTest.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/XWalkViewTestBase.java
Implement this API to get the rendering backend type of XWalkView.
BUG=XWALK-4867
> [Android] Implement embedding API: getCompositingSurfaceType()

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- tools/reflection_generator/java_class.py
In cordova-plugin-crosswalk-webview, the AttributeSet is null, please
look at [XWalkCordovaView.java#L55](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/blob/master/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java#L55), app will crash with null pointer.
Add the conditional for AttributeSet.
BUG=XWALK-6960
> [Android] Fix the crash issue when use the cordova plugin.

- runtime/browser/runtime.cc
- runtime/browser/runtime.h
- runtime/browser/xwalk_browser_context.cc
- runtime/browser/xwalk_browser_context.h
- runtime/renderer/xwalk_content_renderer_client.cc
- runtime/renderer/xwalk_content_renderer_client.h
So they can change color appropriately if you already navigated that URL.
Mostly borrowing the work already done for Android.
BUG=XWALK-6935
> [Linux][Windows] Implement navigation history of links.

- DEPS.xwalk
* fea8ed3 Merge pull request #356 from rakuco/remove-gclient
* 20594f7 Remove .gclient and .gclient_entries.
Related BUG=XWALK-6961
> DEPS.xwalk: Roll chromium-crosswalk (0732335 -> fea8ed3)

- runtime/browser/android/net_disk_cache_remover.cc
- runtime/browser/android/net_disk_cache_remover.h
- runtime/browser/android/xwalk_content.cc
- runtime/renderer/android/xwalk_render_process_observer.cc
- runtime/renderer/android/xwalk_render_process_observer.h
This PR will fix the failed test case of testClearCacheForSingleFile() and testSetNetworkAvailableTest().
BUG=XWALK-6998
> M51: Fix failed test case on Android

- experimental/wifidirect/XWalkExtension.cs
- experimental/wifidirect/XWalkExtensionInstance.cs
- experimental/wifidirect/wifidirect_extension.cc
- experimental/wifidirect/wifidirect_extension.csproj
- experimental/wifidirect/wifidirect_extension.gyp
- runtime/browser/application_component.cc
- runtime/browser/wifidirect_component_win.cc
- runtime/browser/wifidirect_component_win.h
- runtime/browser/xwalk_runner_win.cc
- runtime/browser/xwalk_runner_win.h
- runtime/common/xwalk_runtime_features.cc
- runtime/common/xwalk_runtime_features.h
- runtime/resources/xwalk_resources.grd
- tools/copy_rename.py
- xwalk.gyp
Initial implementation of WiFi Direct experimental API on Windows.
Supported only on Windows10 and Android.
JS API is the same as in Android.
BUG=XWALK-5752
> [Windows] WiFi Direct API

- DEPS.xwalk
* d02146a Merge pull request #156 from chuan9/xwalk-7000-20
* 525f801 Add Bool32x4ExtractLane on x64 Bug=XWALK-7000
BUG=XWALK-7000
> crosswalk-20: DEPS.xwalk: Roll v8-crosswalk (04e36ca -> d02146a)

- DEPS.xwalk
* ef1593c Merge pull request #155 from chuan9/xwalk-7000-19
* 6c12c9e Add Bool32x4ExtractLane on x64 Bug=XWALK-7000
BUG=XWALK-7000
> DEPS.xwalk: Roll v8-crosswalk (d18f5fd -> ef1593c)

- RELEASENOTES.md
Cherry-pick of commit 99e562ad729afbf8335c0df8c2e3368b884c1cf4 which updated the release notes for Crosswalk 19 stable
> Update release notes for Crosswalk stable

- CONTRIBUTING.md
- RELEASENOTES.md
Cherry picks the creation of the release notes and the update done when Crosswalk 19 became stable.
> Add release notes to Crosswalk 19

- experimental/wifidirect/XWalkExtension.cs
- experimental/wifidirect/XWalkExtensionInstance.cs
- experimental/wifidirect/wifidirect_extension.csproj
- experimental/wifidirect/wifidirect_extension.gyp
- runtime/browser/application_component.cc
- runtime/browser/wifidirect_component_win.cc
- runtime/browser/wifidirect_component_win.h
- runtime/browser/xwalk_runner_win.cc
- runtime/browser/xwalk_runner_win.h
- runtime/common/xwalk_runtime_features.cc
- runtime/common/xwalk_runtime_features.h
- runtime/resources/xwalk_resources.grd
- tools/copy_rename.py
- xwalk.gyp
Initial implementation of WiFi Direct experimental API on Windows.
Supported only on Windows10 and Android.
JS API is the same as in Android.
BUG=XWALK-5752
> Re-land: [Windows] WiFiDirect API

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
- test/android/core/javatests/src/org/xwalk/core/xwview/test/SettingsTest.java
XWalk already has the implementation of the two APIs,
there just expose them.
BUG=XWALK-7045
> Expose setSaveFormData/getSaveFormData in XWalkSettings

- build/common.gypi
Commit 7db2189 ("Fix the video play issue after M51 rebase") correctly
mentioned the reason for moving the `proprietary_codecs` assignment to a
`conditions` block, but needlessly checked for the `OS` variable instead
of just adding a check that is always true to better simulate what we
were doing before (an unconditional assignment).
Since gyp's evaluation rules are very confusing, also add more comments
to `common.gypi` explaining what is really going on.
BUG=XWALK-7032
> build: Generalize the |proprietary_codecs| check from 7db2189.

- runtime/android/core/src/org/xwalk/core/XWalkActivityDelegate.java
- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/XWalkDialogManager.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
- runtime/android/core/strings/xwalk_app_strings.grd
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
- Additional dialog for prompting the end-user which store support
Crosswalk Project.
- Fixed bugs when detecting runtime ABI.
> [Android] Improve the experience of getting Crosswalk

- RELEASENOTES.md
> Update release notes for Crosswalk 21

- RELEASENOTES.md
(cherry picked from commit 9521a536cb703d37e85216b27e96da5aaa04f9ae)
> crosswalk-20: Update release notes for Crosswalk 20

- runtime/browser/android/net/input_stream_impl.h
- runtime/browser/android/net/xwalk_cookie_store_wrapper.cc
- runtime/browser/android/net/xwalk_cookie_store_wrapper.h
- runtime/browser/runtime_url_request_context_getter.cc
- runtime/browser/xwalk_browser_main_parts_android.cc
- runtime/browser/xwalk_content_browser_client.cc
- runtime/browser/xwalk_presentation_service_helper_android.h
- runtime/common/xwalk_paths.cc
This pull request partly fixes android x64 build. There are some blink failures still, but I will fix them soon.
> [Android] Fixing android x64 build.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContent.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkHitTestResultInternal.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewInternal.java
- runtime/browser/android/renderer_host/xwalk_render_view_host_ext.cc
- runtime/browser/android/renderer_host/xwalk_render_view_host_ext.h
- runtime/browser/android/xwalk_content.cc
- runtime/browser/android/xwalk_content.h
- runtime/common/android/xwalk_render_view_messages.h
- runtime/renderer/android/xwalk_render_view_ext.cc
- runtime/renderer/android/xwalk_render_view_ext.h
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/HitTestTest.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/XWalkViewInternalTestTouchUtils.java
- test/android/core_internal/javatests/src/org/xwalk/core/internal/xwview/test/util/CommonResources.java
- tools/reflection_generator/reflection_generator.py
Implement this API to get result when hit the screen
BUG=XWALK-6878
> [Android] Implement embedding API: getHitTestResult()

- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
Support more outputs when detecting the CPU architecture of the device.
> [Android] Support more outputs of ABI

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
Correct some mistakes in XWalkSettings API annotation.
> [Android] Correct some mistakes in XWalkSettings API annotation

- runtime/browser/devtools/xwalk_devtools_frontend.cc
while retrieving CPU profile.
Do not pass object literals into dispatchMessage API. Always turn it into
a string.
> [Windows][Linux] DevTools: Fix Maximum call stack size exceeded error

- tools/reflection_generator/reflection_generator.py
Refine embedding API getHitTestResult
Change the order of XWalkHitTestResultInternal in reflection_generator.py
BUG=XWALK-6878
> [Android] Change the order of XWalkHitTestResultInternal

- runtime/android/core_internal/src/org/xwalk/core/internal/SslUtil.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkContentsClientBridge.java
- runtime/android/core_internal/strings/android_xwalk_strings.grd
- test/android/core/javatests/src/org/xwalk/core/xwview/test/ClearSslPreferenceTest.java
Some prompts are not right, fix it.
BUG=XWALK-6986
(cherry picked from commit 60026878e7d770412f2c8a6a6a0cedc261482b28)
> [Android] Fix the prompt issue.

- runtime/browser/xwalk_browser_main_parts.cc
Automatically try to find the manifest.json relative to the xwalk.exe path
in approot/ (which is the place for application files created using
crosswalk-app-tools). If it's not found then crosswalk doesn't start.
> [Windows] Autostart application if no paramaters are passed to xwalk.

- runtime/browser/android/xwalk_settings.cc
- test/android/runtime_client/javatests/src/org/xwalk/runtime/client/test/NativeFileSystemTest.java
- test/android/runtime_client_embedded/javatests/src/org/xwalk/runtime/client/embedded/test/NativeFileSystemTest.java
1. Adapt to https://codereview.chromium.org/1785953002
2. Add annotations for test cases.
BUG=XWALK-7104
> M52: Fix the failed test cases.

- runtime/android/core/src/org/xwalk/core/XWalkActivityDelegate.java
- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/XWalkDecompressor.java
- runtime/android/core/src/org/xwalk/core/XWalkDialogManager.java
- runtime/android/core/src/org/xwalk/core/XWalkEnvironment.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryLoader.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
- Fixed crash when installing downloaded Crosswalk APK on Android 6.0
image
- Fixed an issue where the download URL might be in wrong format after
appended the query of architecture
- Fixed an issue failed to extract native library due to wrong path
on some devices.
- Fixed an issue where the ABI detection might be inaccurate on some
devices.
BUG=XWALK-7105
BUG=XWALK-7106
BUG=XWALK-7115
BUG=XWALK-7128
> [Android] Bug fixes for shared mode and download mode

- runtime/android/core/src/org/xwalk/core/XWalkActivity.java
- runtime/android/core/src/org/xwalk/core/XWalkActivityDelegate.java
- runtime/android/core/src/org/xwalk/core/XWalkCoreWrapper.java
- runtime/android/core/src/org/xwalk/core/XWalkDecompressor.java
- runtime/android/core/src/org/xwalk/core/XWalkDialogManager.java
- runtime/android/core/src/org/xwalk/core/XWalkEnvironment.java
- runtime/android/core/src/org/xwalk/core/XWalkLibraryLoader.java
- runtime/android/core/src/org/xwalk/core/XWalkUpdater.java
- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkViewDelegate.java
[Android] Fixed bugs when detecting runtime ABI.
[Android] Support more outputs of ABI
[Android] Bug fixes for shared mode and download mode
[Android] Fixed the bug of getting wrong meta data
BUG=XWALK-7105
BUG=XWALK-7106
BUG=XWALK-7115
BUG=XWALK-7128
> Backport bug fixes and to Crosswalk-20

- sysapps/raw_socket/udp_socket_object.cc
Drop the check for whether it has returned the number of bytes we are
trying to send (which includes a comparison between a size_t and an
int) since it does not make much sense. We only need to contemplate 3
different cases:
1. SendTo returns ERR_IO_PENDING, which means it is still transmitting
all the data.
2. SendTo returns another negative value, so we just bail out.
3. SendTo returns a positive value, which means everything was
transmitted, otherwise ERR_IO_PENDING would have been returned.
> sysapps: Rewrite the check for UDPSocket::SendTo's return value.

- runtime/android/core_internal/src/org/xwalk/core/internal/XWalkSettingsInternal.java
Reverts crosswalk-project/crosswalk#3852
> Revert "[Android] Refine the default values of mUseWideViewport and mLoadWith…"

- RELEASENOTES.md
> Update release notes for Crosswalk 20 stable

- BUILD.gn
- build/libnotify/BUILD.gn
- tools/installer/BUILD.gn
- tools/installer/common/generate-changelog.py
- tools/installer/common/generate-changelog.sh
- tools/installer/common/installer.include
Add web_notification, xwalk_installer part of Crosswalk-Linux.
With this PR, GN conversion for Crosswalk-Linux is done.
BUG = XWALK-7180
> Add GN build files of web_notification, xwalk_installer for Crosswalk-Linux

- RELEASENOTES.md
> Add Crosswalk 21 promotion date

- application/browser/application_protocols.cc
Ever since commit 2bdc24a1 ("[Runtime] Return a "NOT FOUND" message if
the resource is invalid when using application scheme"), we are bailing
out early in `ApplicationProtocolHandler::MaybeCreateJob()` when there
is no `ApplicationData`.
This means we can remove all the further checks for `application.get()`
and get rid of `is_authority_match`, since by the time a
`UrlRequestApplicationJob` is created its value will always be true.
Not only does this make the code more readable, but it avoids a build
warning turned error in MSVC2015 when building the code with stricter
flags in GN:
application_protocols.cc(307): warning C4800: 'xwalk::application::ApplicationData *': forcing value to bool 'true' or 'false' (performance warning)
> ApplicationProtocolHandler: Remove |is_authority_match|.

- DEPS.xwalk
* 49772a4 Merge pull request #388 from rakuco/revert-webaudio-patches-xwalk-7030
* 7807ac7 Revert AudioDestinationNode.devicePosition commits
RELATED BUG=XWALK-7030
RELATED BUG=XWALK-7226
> DEPS.xwalk: Roll chromium-crosswalk (b53bd1c..49772a4)

- DEPS.xwalk
* 1e13f90 Merge pull request #389 from rakuco/xw22-revert-webaudio-patches-xwalk-7030
* e762df3 Revert AudioDestinationNode.devicePosition commits
RELATED BUG=XWALK-7030
RELATED BUG=XWALK-7226
> crosswalk-22: DEPS.xwalk: Roll chromium-crosswalk (7e0c695..1e13f90)

- DEPS.xwalk
* 3aee3b5 Merge pull request #390 from rakuco/xw21-revert-webaudio-patches-xwalk-7030
* a79ce6f Revert AudioDestinationNode.devicePosition commits
RELATED BUG=XWALK-7030
RELATED BUG=XWALK-7226
> crosswalk-21: DEPS.xwalk: Roll chromium-crosswalk (e9a937d..3aee3b5)

- DEPS.xwalk
* e6fb49d Merge pull request #394 from xzhan96/local_master
* 747ccca Revert "Replace WebAudio MediaCodec usage with FFmpeg" commi
RELATED BUG=XWALK-7307
> DEPS.xwalk: Roll chromium-crosswalk (ee335c1..e6fb49d)

- DEPS.xwalk
* dd39e4f Merge pull request #398 from xzhan96/revert_audio_ffmpeg
* b93971b Revert "Replace WebAudio MediaCodec usage with FFmpeg" commit
RELATED BUG=XWALK-7307
> DEPS.xwalk: Roll chromium-crosswalk (28e7279..dd39e4f)

- extensions/common/android/xwalk_extension_android.cc
- extensions/common/android/xwalk_native_extension_loader_android.cc
- runtime/android/core/tools/generate_javadoc.py
- runtime/browser/android/cookie_manager.cc
- runtime/browser/android/net/android_protocol_handler.cc
- runtime/browser/android/xwalk_contents_client_bridge.cc
- runtime/browser/android/xwalk_contents_client_bridge.h
- runtime/browser/android/xwalk_contents_client_bridge_base.h
- runtime/browser/android/xwalk_dev_tools_server.cc
- runtime/browser/android/xwalk_path_helper.cc
- runtime/browser/android/xwalk_presentation_host.cc
- runtime/browser/android/xwalk_view_delegate.cc
- runtime/browser/runtime_resource_dispatcher_host_delegate_android.cc
- runtime/browser/runtime_resource_dispatcher_host_delegate_android.h
> Fix some android rebasing issues

- runtime/browser/android/cookie_manager.cc
- runtime/browser/xwalk_browser_main_parts_android.cc
- runtime/browser/xwalk_browser_main_parts_android.h
CookieManger isn't used at starting crosswalk, so the datas need to be moved early.
https://codereview.chromium.org/71583002
BUG=XWALK-7368
> [Android] Move user data to profile directory

- runtime/browser/runtime_url_request_context_getter.cc
Chromium started enforcing some Certificate Transparency policies by default
in M53, and refuses to load certain websites when the CT verification fails
while establishing the TLS connection; this affected Crosswalk because we
were using the default CT verifier and policy enforcer, but we did not add
any of the logs approved by the Chromium project (see
net/cert/ct_known_logs_static-inc.h).
Instead of doing so, stop requiring websites to pass Chromium's Certificate
Transparency checks altogether after getting some clarification from
upstream. The biggest impediment to us following Chromium's policy is that
Crosswalk's release cycle would need to match Chromium's very closely to
avoid two risks:
1) Chromium approves new CT logs, they start being used in new certificates,
Crosswalk does not …
> Stop enforcing Certificate Transparency verification

- extensions/test/win/binary_extension/XWalkExtension.cs
- extensions/test/win/xwalk_dotnet_extension_unittest.cc
> [Windows] Fix .net extension unittests

- README.md
Make it clear that the project is not being developed anymore with a notice at the beginning of the README file.
> [docs] Add notice of project closure to README
